// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package systemmocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockPluginHealthChecker creates a new instance of MockPluginHealthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPluginHealthChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPluginHealthChecker {
	mock := &MockPluginHealthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPluginHealthChecker is an autogenerated mock type for the PluginHealthChecker type
type MockPluginHealthChecker struct {
	mock.Mock
}

type MockPluginHealthChecker_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPluginHealthChecker) EXPECT() *MockPluginHealthChecker_Expecter {
	return &MockPluginHealthChecker_Expecter{mock: &_m.Mock}
}

// HealthCheckAll provides a mock function for the type MockPluginHealthChecker
func (_mock *MockPluginHealthChecker) HealthCheckAll() map[string]error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheckAll")
	}

	var r0 map[string]error
	if returnFunc, ok := ret.Get(0).(func() map[string]error); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]error)
		}
	}
	return r0
}

// MockPluginHealthChecker_HealthCheckAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HealthCheckAll'
type MockPluginHealthChecker_HealthCheckAll_Call struct {
	*mock.Call
}

// HealthCheckAll is a helper method to define mock.On call
func (_e *MockPluginHealthChecker_Expecter) HealthCheckAll() *MockPluginHealthChecker_HealthCheckAll_Call {
	return &MockPluginHealthChecker_HealthCheckAll_Call{Call: _e.mock.On("HealthCheckAll")}
}

func (_c *MockPluginHealthChecker_HealthCheckAll_Call) Run(run func()) *MockPluginHealthChecker_HealthCheckAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPluginHealthChecker_HealthCheckAll_Call) Return(stringToErr map[string]error) *MockPluginHealthChecker_HealthCheckAll_Call {
	_c.Call.Return(stringToErr)
	return _c
}

func (_c *MockPluginHealthChecker_HealthCheckAll_Call) RunAndReturn(run func() map[string]error) *MockPluginHealthChecker_HealthCheckAll_Call {
	_c.Call.Return(run)
	return _c
}
