// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package systemmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSystemStore creates a new instance of MockSystemStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemStore {
	mock := &MockSystemStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSystemStore is an autogenerated mock type for the SystemStore type
type MockSystemStore struct {
	mock.Mock
}

type MockSystemStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemStore) EXPECT() *MockSystemStore_Expecter {
	return &MockSystemStore_Expecter{mock: &_m.Mock}
}

// AddBlockedHash provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) AddBlockedHash(hash string, reason string) error {
	ret := _mock.Called(hash, reason)

	if len(ret) == 0 {
		panic("no return value specified for AddBlockedHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(hash, reason)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemStore_AddBlockedHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddBlockedHash'
type MockSystemStore_AddBlockedHash_Call struct {
	*mock.Call
}

// AddBlockedHash is a helper method to define mock.On call
//   - hash string
//   - reason string
func (_e *MockSystemStore_Expecter) AddBlockedHash(hash interface{}, reason interface{}) *MockSystemStore_AddBlockedHash_Call {
	return &MockSystemStore_AddBlockedHash_Call{Call: _e.mock.On("AddBlockedHash", hash, reason)}
}

func (_c *MockSystemStore_AddBlockedHash_Call) Run(run func(hash string, reason string)) *MockSystemStore_AddBlockedHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemStore_AddBlockedHash_Call) Return(err error) *MockSystemStore_AddBlockedHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemStore_AddBlockedHash_Call) RunAndReturn(run func(hash string, reason string) error) *MockSystemStore_AddBlockedHash_Call {
	_c.Call.Return(run)
	return _c
}

// CountAuthors provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) CountAuthors() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountAuthors")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_CountAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAuthors'
type MockSystemStore_CountAuthors_Call struct {
	*mock.Call
}

// CountAuthors is a helper method to define mock.On call
func (_e *MockSystemStore_Expecter) CountAuthors() *MockSystemStore_CountAuthors_Call {
	return &MockSystemStore_CountAuthors_Call{Call: _e.mock.On("CountAuthors")}
}

func (_c *MockSystemStore_CountAuthors_Call) Run(run func()) *MockSystemStore_CountAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemStore_CountAuthors_Call) Return(n int, err error) *MockSystemStore_CountAuthors_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSystemStore_CountAuthors_Call) RunAndReturn(run func() (int, error)) *MockSystemStore_CountAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// CountBooks provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) CountBooks() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountBooks")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_CountBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBooks'
type MockSystemStore_CountBooks_Call struct {
	*mock.Call
}

// CountBooks is a helper method to define mock.On call
func (_e *MockSystemStore_Expecter) CountBooks() *MockSystemStore_CountBooks_Call {
	return &MockSystemStore_CountBooks_Call{Call: _e.mock.On("CountBooks")}
}

func (_c *MockSystemStore_CountBooks_Call) Run(run func()) *MockSystemStore_CountBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemStore_CountBooks_Call) Return(n int, err error) *MockSystemStore_CountBooks_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSystemStore_CountBooks_Call) RunAndReturn(run func() (int, error)) *MockSystemStore_CountBooks_Call {
	_c.Call.Return(run)
	return _c
}

// CountSeries provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) CountSeries() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountSeries")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_CountSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSeries'
type MockSystemStore_CountSeries_Call struct {
	*mock.Call
}

// CountSeries is a helper method to define mock.On call
func (_e *MockSystemStore_Expecter) CountSeries() *MockSystemStore_CountSeries_Call {
	return &MockSystemStore_CountSeries_Call{Call: _e.mock.On("CountSeries")}
}

func (_c *MockSystemStore_CountSeries_Call) Run(run func()) *MockSystemStore_CountSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemStore_CountSeries_Call) Return(n int, err error) *MockSystemStore_CountSeries_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSystemStore_CountSeries_Call) RunAndReturn(run func() (int, error)) *MockSystemStore_CountSeries_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSetting provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) DeleteSetting(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemStore_DeleteSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSetting'
type MockSystemStore_DeleteSetting_Call struct {
	*mock.Call
}

// DeleteSetting is a helper method to define mock.On call
//   - key string
func (_e *MockSystemStore_Expecter) DeleteSetting(key interface{}) *MockSystemStore_DeleteSetting_Call {
	return &MockSystemStore_DeleteSetting_Call{Call: _e.mock.On("DeleteSetting", key)}
}

func (_c *MockSystemStore_DeleteSetting_Call) Run(run func(key string)) *MockSystemStore_DeleteSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystemStore_DeleteSetting_Call) Return(err error) *MockSystemStore_DeleteSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemStore_DeleteSetting_Call) RunAndReturn(run func(key string) error) *MockSystemStore_DeleteSetting_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAuthors provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) GetAllAuthors() ([]database.Author, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllAuthors")
	}

	var r0 []database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Author, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Author); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_GetAllAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAuthors'
type MockSystemStore_GetAllAuthors_Call struct {
	*mock.Call
}

// GetAllAuthors is a helper method to define mock.On call
func (_e *MockSystemStore_Expecter) GetAllAuthors() *MockSystemStore_GetAllAuthors_Call {
	return &MockSystemStore_GetAllAuthors_Call{Call: _e.mock.On("GetAllAuthors")}
}

func (_c *MockSystemStore_GetAllAuthors_Call) Run(run func()) *MockSystemStore_GetAllAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemStore_GetAllAuthors_Call) Return(authors []database.Author, err error) *MockSystemStore_GetAllAuthors_Call {
	_c.Call.Return(authors, err)
	return _c
}

func (_c *MockSystemStore_GetAllAuthors_Call) RunAndReturn(run func() ([]database.Author, error)) *MockSystemStore_GetAllAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBlockedHashes provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) GetAllBlockedHashes() ([]database.DoNotImport, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllBlockedHashes")
	}

	var r0 []database.DoNotImport
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.DoNotImport, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.DoNotImport); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.DoNotImport)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_GetAllBlockedHashes_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBlockedHashes'
type MockSystemStore_GetAllBlockedHashes_Call struct {
	*mock.Call
}

// GetAllBlockedHashes is a helper method to define mock.On call
func (_e *MockSystemStore_Expecter) GetAllBlockedHashes() *MockSystemStore_GetAllBlockedHashes_Call {
	return &MockSystemStore_GetAllBlockedHashes_Call{Call: _e.mock.On("GetAllBlockedHashes")}
}

func (_c *MockSystemStore_GetAllBlockedHashes_Call) Run(run func()) *MockSystemStore_GetAllBlockedHashes_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemStore_GetAllBlockedHashes_Call) Return(doNotImports []database.DoNotImport, err error) *MockSystemStore_GetAllBlockedHashes_Call {
	_c.Call.Return(doNotImports, err)
	return _c
}

func (_c *MockSystemStore_GetAllBlockedHashes_Call) RunAndReturn(run func() ([]database.DoNotImport, error)) *MockSystemStore_GetAllBlockedHashes_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBooks provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) GetAllBooks(limit int, offset int) ([]database.Book, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBooks")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]database.Book, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []database.Book); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_GetAllBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBooks'
type MockSystemStore_GetAllBooks_Call struct {
	*mock.Call
}

// GetAllBooks is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockSystemStore_Expecter) GetAllBooks(limit interface{}, offset interface{}) *MockSystemStore_GetAllBooks_Call {
	return &MockSystemStore_GetAllBooks_Call{Call: _e.mock.On("GetAllBooks", limit, offset)}
}

func (_c *MockSystemStore_GetAllBooks_Call) Run(run func(limit int, offset int)) *MockSystemStore_GetAllBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemStore_GetAllBooks_Call) Return(books []database.Book, err error) *MockSystemStore_GetAllBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockSystemStore_GetAllBooks_Call) RunAndReturn(run func(limit int, offset int) ([]database.Book, error)) *MockSystemStore_GetAllBooks_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllSettings provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) GetAllSettings() ([]database.Setting, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllSettings")
	}

	var r0 []database.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Setting, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Setting); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Setting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_GetAllSettings_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllSettings'
type MockSystemStore_GetAllSettings_Call struct {
	*mock.Call
}

// GetAllSettings is a helper method to define mock.On call
func (_e *MockSystemStore_Expecter) GetAllSettings() *MockSystemStore_GetAllSettings_Call {
	return &MockSystemStore_GetAllSettings_Call{Call: _e.mock.On("GetAllSettings")}
}

func (_c *MockSystemStore_GetAllSettings_Call) Run(run func()) *MockSystemStore_GetAllSettings_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemStore_GetAllSettings_Call) Return(settings []database.Setting, err error) *MockSystemStore_GetAllSettings_Call {
	_c.Call.Return(settings, err)
	return _c
}

func (_c *MockSystemStore_GetAllSettings_Call) RunAndReturn(run func() ([]database.Setting, error)) *MockSystemStore_GetAllSettings_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByAuthorIDWithRole provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) GetBooksByAuthorIDWithRole(authorID int) ([]database.Book, error) {
	ret := _mock.Called(authorID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByAuthorIDWithRole")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.Book, error)); ok {
		return returnFunc(authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.Book); ok {
		r0 = returnFunc(authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_GetBooksByAuthorIDWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByAuthorIDWithRole'
type MockSystemStore_GetBooksByAuthorIDWithRole_Call struct {
	*mock.Call
}

// GetBooksByAuthorIDWithRole is a helper method to define mock.On call
//   - authorID int
func (_e *MockSystemStore_Expecter) GetBooksByAuthorIDWithRole(authorID interface{}) *MockSystemStore_GetBooksByAuthorIDWithRole_Call {
	return &MockSystemStore_GetBooksByAuthorIDWithRole_Call{Call: _e.mock.On("GetBooksByAuthorIDWithRole", authorID)}
}

func (_c *MockSystemStore_GetBooksByAuthorIDWithRole_Call) Run(run func(authorID int)) *MockSystemStore_GetBooksByAuthorIDWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystemStore_GetBooksByAuthorIDWithRole_Call) Return(books []database.Book, err error) *MockSystemStore_GetBooksByAuthorIDWithRole_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockSystemStore_GetBooksByAuthorIDWithRole_Call) RunAndReturn(run func(authorID int) ([]database.Book, error)) *MockSystemStore_GetBooksByAuthorIDWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetDashboardStats provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) GetDashboardStats() (*database.DashboardStats, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDashboardStats")
	}

	var r0 *database.DashboardStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*database.DashboardStats, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *database.DashboardStats); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.DashboardStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_GetDashboardStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDashboardStats'
type MockSystemStore_GetDashboardStats_Call struct {
	*mock.Call
}

// GetDashboardStats is a helper method to define mock.On call
func (_e *MockSystemStore_Expecter) GetDashboardStats() *MockSystemStore_GetDashboardStats_Call {
	return &MockSystemStore_GetDashboardStats_Call{Call: _e.mock.On("GetDashboardStats")}
}

func (_c *MockSystemStore_GetDashboardStats_Call) Run(run func()) *MockSystemStore_GetDashboardStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemStore_GetDashboardStats_Call) Return(v *database.DashboardStats, err error) *MockSystemStore_GetDashboardStats_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockSystemStore_GetDashboardStats_Call) RunAndReturn(run func() (*database.DashboardStats, error)) *MockSystemStore_GetDashboardStats_Call {
	_c.Call.Return(run)
	return _c
}

// GetRecentOperations provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) GetRecentOperations(limit int) ([]database.Operation, error) {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for GetRecentOperations")
	}

	var r0 []database.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.Operation, error)); ok {
		return returnFunc(limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.Operation); ok {
		r0 = returnFunc(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_GetRecentOperations_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRecentOperations'
type MockSystemStore_GetRecentOperations_Call struct {
	*mock.Call
}

// GetRecentOperations is a helper method to define mock.On call
//   - limit int
func (_e *MockSystemStore_Expecter) GetRecentOperations(limit interface{}) *MockSystemStore_GetRecentOperations_Call {
	return &MockSystemStore_GetRecentOperations_Call{Call: _e.mock.On("GetRecentOperations", limit)}
}

func (_c *MockSystemStore_GetRecentOperations_Call) Run(run func(limit int)) *MockSystemStore_GetRecentOperations_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystemStore_GetRecentOperations_Call) Return(operations []database.Operation, err error) *MockSystemStore_GetRecentOperations_Call {
	_c.Call.Return(operations, err)
	return _c
}

func (_c *MockSystemStore_GetRecentOperations_Call) RunAndReturn(run func(limit int) ([]database.Operation, error)) *MockSystemStore_GetRecentOperations_Call {
	_c.Call.Return(run)
	return _c
}

// GetSetting provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) GetSetting(key string) (*database.Setting, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetSetting")
	}

	var r0 *database.Setting
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Setting, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Setting); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Setting)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_GetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSetting'
type MockSystemStore_GetSetting_Call struct {
	*mock.Call
}

// GetSetting is a helper method to define mock.On call
//   - key string
func (_e *MockSystemStore_Expecter) GetSetting(key interface{}) *MockSystemStore_GetSetting_Call {
	return &MockSystemStore_GetSetting_Call{Call: _e.mock.On("GetSetting", key)}
}

func (_c *MockSystemStore_GetSetting_Call) Run(run func(key string)) *MockSystemStore_GetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystemStore_GetSetting_Call) Return(setting *database.Setting, err error) *MockSystemStore_GetSetting_Call {
	_c.Call.Return(setting, err)
	return _c
}

func (_c *MockSystemStore_GetSetting_Call) RunAndReturn(run func(key string) (*database.Setting, error)) *MockSystemStore_GetSetting_Call {
	_c.Call.Return(run)
	return _c
}

// GetSystemActivityLogs provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) GetSystemActivityLogs(source string, limit int) ([]database.SystemActivityLog, error) {
	ret := _mock.Called(source, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetSystemActivityLogs")
	}

	var r0 []database.SystemActivityLog
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) ([]database.SystemActivityLog, error)); ok {
		return returnFunc(source, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) []database.SystemActivityLog); ok {
		r0 = returnFunc(source, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.SystemActivityLog)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(source, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_GetSystemActivityLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSystemActivityLogs'
type MockSystemStore_GetSystemActivityLogs_Call struct {
	*mock.Call
}

// GetSystemActivityLogs is a helper method to define mock.On call
//   - source string
//   - limit int
func (_e *MockSystemStore_Expecter) GetSystemActivityLogs(source interface{}, limit interface{}) *MockSystemStore_GetSystemActivityLogs_Call {
	return &MockSystemStore_GetSystemActivityLogs_Call{Call: _e.mock.On("GetSystemActivityLogs", source, limit)}
}

func (_c *MockSystemStore_GetSystemActivityLogs_Call) Run(run func(source string, limit int)) *MockSystemStore_GetSystemActivityLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemStore_GetSystemActivityLogs_Call) Return(systemActivityLogs []database.SystemActivityLog, err error) *MockSystemStore_GetSystemActivityLogs_Call {
	_c.Call.Return(systemActivityLogs, err)
	return _c
}

func (_c *MockSystemStore_GetSystemActivityLogs_Call) RunAndReturn(run func(source string, limit int) ([]database.SystemActivityLog, error)) *MockSystemStore_GetSystemActivityLogs_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPreference provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) GetUserPreference(key string) (*database.UserPreference, error) {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPreference")
	}

	var r0 *database.UserPreference
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.UserPreference, error)); ok {
		return returnFunc(key)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.UserPreference); ok {
		r0 = returnFunc(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserPreference)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(key)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemStore_GetUserPreference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPreference'
type MockSystemStore_GetUserPreference_Call struct {
	*mock.Call
}

// GetUserPreference is a helper method to define mock.On call
//   - key string
func (_e *MockSystemStore_Expecter) GetUserPreference(key interface{}) *MockSystemStore_GetUserPreference_Call {
	return &MockSystemStore_GetUserPreference_Call{Call: _e.mock.On("GetUserPreference", key)}
}

func (_c *MockSystemStore_GetUserPreference_Call) Run(run func(key string)) *MockSystemStore_GetUserPreference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystemStore_GetUserPreference_Call) Return(userPreference *database.UserPreference, err error) *MockSystemStore_GetUserPreference_Call {
	_c.Call.Return(userPreference, err)
	return _c
}

func (_c *MockSystemStore_GetUserPreference_Call) RunAndReturn(run func(key string) (*database.UserPreference, error)) *MockSystemStore_GetUserPreference_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateLibraryStats provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) InvalidateLibraryStats() {
	_mock.Called()
	return
}

// MockSystemStore_InvalidateLibraryStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateLibraryStats'
type MockSystemStore_InvalidateLibraryStats_Call struct {
	*mock.Call
}

// InvalidateLibraryStats is a helper method to define mock.On call
func (_e *MockSystemStore_Expecter) InvalidateLibraryStats() *MockSystemStore_InvalidateLibraryStats_Call {
	return &MockSystemStore_InvalidateLibraryStats_Call{Call: _e.mock.On("InvalidateLibraryStats")}
}

func (_c *MockSystemStore_InvalidateLibraryStats_Call) Run(run func()) *MockSystemStore_InvalidateLibraryStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemStore_InvalidateLibraryStats_Call) Return() *MockSystemStore_InvalidateLibraryStats_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockSystemStore_InvalidateLibraryStats_Call) RunAndReturn(run func()) *MockSystemStore_InvalidateLibraryStats_Call {
	_c.Run(run)
	return _c
}

// RemoveBlockedHash provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) RemoveBlockedHash(hash string) error {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for RemoveBlockedHash")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(hash)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemStore_RemoveBlockedHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveBlockedHash'
type MockSystemStore_RemoveBlockedHash_Call struct {
	*mock.Call
}

// RemoveBlockedHash is a helper method to define mock.On call
//   - hash string
func (_e *MockSystemStore_Expecter) RemoveBlockedHash(hash interface{}) *MockSystemStore_RemoveBlockedHash_Call {
	return &MockSystemStore_RemoveBlockedHash_Call{Call: _e.mock.On("RemoveBlockedHash", hash)}
}

func (_c *MockSystemStore_RemoveBlockedHash_Call) Run(run func(hash string)) *MockSystemStore_RemoveBlockedHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSystemStore_RemoveBlockedHash_Call) Return(err error) *MockSystemStore_RemoveBlockedHash_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemStore_RemoveBlockedHash_Call) RunAndReturn(run func(hash string) error) *MockSystemStore_RemoveBlockedHash_Call {
	_c.Call.Return(run)
	return _c
}

// Reset provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) Reset() error {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Reset")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func() error); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemStore_Reset_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Reset'
type MockSystemStore_Reset_Call struct {
	*mock.Call
}

// Reset is a helper method to define mock.On call
func (_e *MockSystemStore_Expecter) Reset() *MockSystemStore_Reset_Call {
	return &MockSystemStore_Reset_Call{Call: _e.mock.On("Reset")}
}

func (_c *MockSystemStore_Reset_Call) Run(run func()) *MockSystemStore_Reset_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemStore_Reset_Call) Return(err error) *MockSystemStore_Reset_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemStore_Reset_Call) RunAndReturn(run func() error) *MockSystemStore_Reset_Call {
	_c.Call.Return(run)
	return _c
}

// SetSetting provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) SetSetting(key string, value string, typ string, isSecret bool) error {
	ret := _mock.Called(key, value, typ, isSecret)

	if len(ret) == 0 {
		panic("no return value specified for SetSetting")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, bool) error); ok {
		r0 = returnFunc(key, value, typ, isSecret)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemStore_SetSetting_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetSetting'
type MockSystemStore_SetSetting_Call struct {
	*mock.Call
}

// SetSetting is a helper method to define mock.On call
//   - key string
//   - value string
//   - typ string
//   - isSecret bool
func (_e *MockSystemStore_Expecter) SetSetting(key interface{}, value interface{}, typ interface{}, isSecret interface{}) *MockSystemStore_SetSetting_Call {
	return &MockSystemStore_SetSetting_Call{Call: _e.mock.On("SetSetting", key, value, typ, isSecret)}
}

func (_c *MockSystemStore_SetSetting_Call) Run(run func(key string, value string, typ string, isSecret bool)) *MockSystemStore_SetSetting_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSystemStore_SetSetting_Call) Return(err error) *MockSystemStore_SetSetting_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemStore_SetSetting_Call) RunAndReturn(run func(key string, value string, typ string, isSecret bool) error) *MockSystemStore_SetSetting_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserPreference provides a mock function for the type MockSystemStore
func (_mock *MockSystemStore) SetUserPreference(key string, value string) error {
	ret := _mock.Called(key, value)

	if len(ret) == 0 {
		panic("no return value specified for SetUserPreference")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(key, value)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSystemStore_SetUserPreference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserPreference'
type MockSystemStore_SetUserPreference_Call struct {
	*mock.Call
}

// SetUserPreference is a helper method to define mock.On call
//   - key string
//   - value string
func (_e *MockSystemStore_Expecter) SetUserPreference(key interface{}, value interface{}) *MockSystemStore_SetUserPreference_Call {
	return &MockSystemStore_SetUserPreference_Call{Call: _e.mock.On("SetUserPreference", key, value)}
}

func (_c *MockSystemStore_SetUserPreference_Call) Run(run func(key string, value string)) *MockSystemStore_SetUserPreference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockSystemStore_SetUserPreference_Call) Return(err error) *MockSystemStore_SetUserPreference_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSystemStore_SetUserPreference_Call) RunAndReturn(run func(key string, value string) error) *MockSystemStore_SetUserPreference_Call {
	_c.Call.Return(run)
	return _c
}
