// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package systemmocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOperationLogsProvider creates a new instance of MockOperationLogsProvider. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationLogsProvider(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationLogsProvider {
	mock := &MockOperationLogsProvider{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperationLogsProvider is an autogenerated mock type for the OperationLogsProvider type
type MockOperationLogsProvider struct {
	mock.Mock
}

type MockOperationLogsProvider_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationLogsProvider) EXPECT() *MockOperationLogsProvider_Expecter {
	return &MockOperationLogsProvider_Expecter{mock: &_m.Mock}
}

// GetOperationLogs provides a mock function for the type MockOperationLogsProvider
func (_mock *MockOperationLogsProvider) GetOperationLogs(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockOperationLogsProvider_GetOperationLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperationLogs'
type MockOperationLogsProvider_GetOperationLogs_Call struct {
	*mock.Call
}

// GetOperationLogs is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockOperationLogsProvider_Expecter) GetOperationLogs(c interface{}) *MockOperationLogsProvider_GetOperationLogs_Call {
	return &MockOperationLogsProvider_GetOperationLogs_Call{Call: _e.mock.On("GetOperationLogs", c)}
}

func (_c *MockOperationLogsProvider_GetOperationLogs_Call) Run(run func(c *gin.Context)) *MockOperationLogsProvider_GetOperationLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationLogsProvider_GetOperationLogs_Call) Return() *MockOperationLogsProvider_GetOperationLogs_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockOperationLogsProvider_GetOperationLogs_Call) RunAndReturn(run func(c *gin.Context)) *MockOperationLogsProvider_GetOperationLogs_Call {
	_c.Run(run)
	return _c
}
