// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package systemmocks

import (
	"github.com/gin-gonic/gin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventStreamer creates a new instance of MockEventStreamer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventStreamer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventStreamer {
	mock := &MockEventStreamer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventStreamer is an autogenerated mock type for the EventStreamer type
type MockEventStreamer struct {
	mock.Mock
}

type MockEventStreamer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventStreamer) EXPECT() *MockEventStreamer_Expecter {
	return &MockEventStreamer_Expecter{mock: &_m.Mock}
}

// HandleSSE provides a mock function for the type MockEventStreamer
func (_mock *MockEventStreamer) HandleSSE(c *gin.Context) {
	_mock.Called(c)
	return
}

// MockEventStreamer_HandleSSE_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HandleSSE'
type MockEventStreamer_HandleSSE_Call struct {
	*mock.Call
}

// HandleSSE is a helper method to define mock.On call
//   - c *gin.Context
func (_e *MockEventStreamer_Expecter) HandleSSE(c interface{}) *MockEventStreamer_HandleSSE_Call {
	return &MockEventStreamer_HandleSSE_Call{Call: _e.mock.On("HandleSSE", c)}
}

func (_c *MockEventStreamer_HandleSSE_Call) Run(run func(c *gin.Context)) *MockEventStreamer_HandleSSE_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *gin.Context
		if args[0] != nil {
			arg0 = args[0].(*gin.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEventStreamer_HandleSSE_Call) Return() *MockEventStreamer_HandleSSE_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventStreamer_HandleSSE_Call) RunAndReturn(run func(c *gin.Context)) *MockEventStreamer_HandleSSE_Call {
	_c.Run(run)
	return _c
}
