// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package systemmocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/sysinfo"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSystemService creates a new instance of MockSystemService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSystemService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSystemService {
	mock := &MockSystemService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSystemService is an autogenerated mock type for the SystemService type
type MockSystemService struct {
	mock.Mock
}

type MockSystemService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSystemService) EXPECT() *MockSystemService_Expecter {
	return &MockSystemService_Expecter{mock: &_m.Mock}
}

// CollectSystemLogs provides a mock function for the type MockSystemService
func (_mock *MockSystemService) CollectSystemLogs(level string, search string, limit int, offset int) ([]sysinfo.SystemLogEntry, int, error) {
	ret := _mock.Called(level, search, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for CollectSystemLogs")
	}

	var r0 []sysinfo.SystemLogEntry
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) ([]sysinfo.SystemLogEntry, int, error)); ok {
		return returnFunc(level, search, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) []sysinfo.SystemLogEntry); ok {
		r0 = returnFunc(level, search, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]sysinfo.SystemLogEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int, int) int); ok {
		r1 = returnFunc(level, search, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string, string, int, int) error); ok {
		r2 = returnFunc(level, search, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSystemService_CollectSystemLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectSystemLogs'
type MockSystemService_CollectSystemLogs_Call struct {
	*mock.Call
}

// CollectSystemLogs is a helper method to define mock.On call
//   - level string
//   - search string
//   - limit int
//   - offset int
func (_e *MockSystemService_Expecter) CollectSystemLogs(level interface{}, search interface{}, limit interface{}, offset interface{}) *MockSystemService_CollectSystemLogs_Call {
	return &MockSystemService_CollectSystemLogs_Call{Call: _e.mock.On("CollectSystemLogs", level, search, limit, offset)}
}

func (_c *MockSystemService_CollectSystemLogs_Call) Run(run func(level string, search string, limit int, offset int)) *MockSystemService_CollectSystemLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockSystemService_CollectSystemLogs_Call) Return(systemLogEntrys []sysinfo.SystemLogEntry, n int, err error) *MockSystemService_CollectSystemLogs_Call {
	_c.Call.Return(systemLogEntrys, n, err)
	return _c
}

func (_c *MockSystemService_CollectSystemLogs_Call) RunAndReturn(run func(level string, search string, limit int, offset int) ([]sysinfo.SystemLogEntry, int, error)) *MockSystemService_CollectSystemLogs_Call {
	_c.Call.Return(run)
	return _c
}

// CollectSystemStatus provides a mock function for the type MockSystemService
func (_mock *MockSystemService) CollectSystemStatus() (*sysinfo.SystemStatus, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CollectSystemStatus")
	}

	var r0 *sysinfo.SystemStatus
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*sysinfo.SystemStatus, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *sysinfo.SystemStatus); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*sysinfo.SystemStatus)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSystemService_CollectSystemStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectSystemStatus'
type MockSystemService_CollectSystemStatus_Call struct {
	*mock.Call
}

// CollectSystemStatus is a helper method to define mock.On call
func (_e *MockSystemService_Expecter) CollectSystemStatus() *MockSystemService_CollectSystemStatus_Call {
	return &MockSystemService_CollectSystemStatus_Call{Call: _e.mock.On("CollectSystemStatus")}
}

func (_c *MockSystemService_CollectSystemStatus_Call) Run(run func()) *MockSystemService_CollectSystemStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSystemService_CollectSystemStatus_Call) Return(systemStatus *sysinfo.SystemStatus, err error) *MockSystemService_CollectSystemStatus_Call {
	_c.Call.Return(systemStatus, err)
	return _c
}

func (_c *MockSystemService_CollectSystemStatus_Call) RunAndReturn(run func() (*sysinfo.SystemStatus, error)) *MockSystemService_CollectSystemStatus_Call {
	_c.Call.Return(run)
	return _c
}
