// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/metadata"
	mock "github.com/stretchr/testify/mock"
)

// NewMockContextualSearch creates a new instance of MockContextualSearch. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockContextualSearch(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockContextualSearch {
	mock := &MockContextualSearch{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockContextualSearch is an autogenerated mock type for the ContextualSearch type
type MockContextualSearch struct {
	mock.Mock
}

type MockContextualSearch_Expecter struct {
	mock *mock.Mock
}

func (_m *MockContextualSearch) EXPECT() *MockContextualSearch_Expecter {
	return &MockContextualSearch_Expecter{mock: &_m.Mock}
}

// SearchByContext provides a mock function for the type MockContextualSearch
func (_mock *MockContextualSearch) SearchByContext(ctx *metadata.SearchContext) ([]metadata.BookMetadata, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for SearchByContext")
	}

	var r0 []metadata.BookMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*metadata.SearchContext) ([]metadata.BookMetadata, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(*metadata.SearchContext) []metadata.BookMetadata); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metadata.BookMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*metadata.SearchContext) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockContextualSearch_SearchByContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByContext'
type MockContextualSearch_SearchByContext_Call struct {
	*mock.Call
}

// SearchByContext is a helper method to define mock.On call
//   - ctx *metadata.SearchContext
func (_e *MockContextualSearch_Expecter) SearchByContext(ctx interface{}) *MockContextualSearch_SearchByContext_Call {
	return &MockContextualSearch_SearchByContext_Call{Call: _e.mock.On("SearchByContext", ctx)}
}

func (_c *MockContextualSearch_SearchByContext_Call) Run(run func(ctx *metadata.SearchContext)) *MockContextualSearch_SearchByContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *metadata.SearchContext
		if args[0] != nil {
			arg0 = args[0].(*metadata.SearchContext)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockContextualSearch_SearchByContext_Call) Return(bookMetadatas []metadata.BookMetadata, err error) *MockContextualSearch_SearchByContext_Call {
	_c.Call.Return(bookMetadatas, err)
	return _c
}

func (_c *MockContextualSearch_SearchByContext_Call) RunAndReturn(run func(ctx *metadata.SearchContext) ([]metadata.BookMetadata, error)) *MockContextualSearch_SearchByContext_Call {
	_c.Call.Return(run)
	return _c
}
