// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/falkcorp/audiobook-organizer/internal/metadata"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetadataSource creates a new instance of MockMetadataSource. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataSource(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataSource {
	mock := &MockMetadataSource{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataSource is an autogenerated mock type for the MetadataSource type
type MockMetadataSource struct {
	mock.Mock
}

type MockMetadataSource_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataSource) EXPECT() *MockMetadataSource_Expecter {
	return &MockMetadataSource_Expecter{mock: &_m.Mock}
}

// Name provides a mock function for the type MockMetadataSource
func (_mock *MockMetadataSource) Name() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Name")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockMetadataSource_Name_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Name'
type MockMetadataSource_Name_Call struct {
	*mock.Call
}

// Name is a helper method to define mock.On call
func (_e *MockMetadataSource_Expecter) Name() *MockMetadataSource_Name_Call {
	return &MockMetadataSource_Name_Call{Call: _e.mock.On("Name")}
}

func (_c *MockMetadataSource_Name_Call) Run(run func()) *MockMetadataSource_Name_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockMetadataSource_Name_Call) Return(s string) *MockMetadataSource_Name_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockMetadataSource_Name_Call) RunAndReturn(run func() string) *MockMetadataSource_Name_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByTitle provides a mock function for the type MockMetadataSource
func (_mock *MockMetadataSource) SearchByTitle(ctx context.Context, title string) ([]metadata.BookMetadata, error) {
	ret := _mock.Called(ctx, title)

	if len(ret) == 0 {
		panic("no return value specified for SearchByTitle")
	}

	var r0 []metadata.BookMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]metadata.BookMetadata, error)); ok {
		return returnFunc(ctx, title)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []metadata.BookMetadata); ok {
		r0 = returnFunc(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metadata.BookMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, title)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataSource_SearchByTitle_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByTitle'
type MockMetadataSource_SearchByTitle_Call struct {
	*mock.Call
}

// SearchByTitle is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
func (_e *MockMetadataSource_Expecter) SearchByTitle(ctx interface{}, title interface{}) *MockMetadataSource_SearchByTitle_Call {
	return &MockMetadataSource_SearchByTitle_Call{Call: _e.mock.On("SearchByTitle", ctx, title)}
}

func (_c *MockMetadataSource_SearchByTitle_Call) Run(run func(ctx context.Context, title string)) *MockMetadataSource_SearchByTitle_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataSource_SearchByTitle_Call) Return(bookMetadatas []metadata.BookMetadata, err error) *MockMetadataSource_SearchByTitle_Call {
	_c.Call.Return(bookMetadatas, err)
	return _c
}

func (_c *MockMetadataSource_SearchByTitle_Call) RunAndReturn(run func(ctx context.Context, title string) ([]metadata.BookMetadata, error)) *MockMetadataSource_SearchByTitle_Call {
	_c.Call.Return(run)
	return _c
}

// SearchByTitleAndAuthor provides a mock function for the type MockMetadataSource
func (_mock *MockMetadataSource) SearchByTitleAndAuthor(ctx context.Context, title string, author string) ([]metadata.BookMetadata, error) {
	ret := _mock.Called(ctx, title, author)

	if len(ret) == 0 {
		panic("no return value specified for SearchByTitleAndAuthor")
	}

	var r0 []metadata.BookMetadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) ([]metadata.BookMetadata, error)); ok {
		return returnFunc(ctx, title, author)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) []metadata.BookMetadata); ok {
		r0 = returnFunc(ctx, title, author)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]metadata.BookMetadata)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, title, author)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataSource_SearchByTitleAndAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchByTitleAndAuthor'
type MockMetadataSource_SearchByTitleAndAuthor_Call struct {
	*mock.Call
}

// SearchByTitleAndAuthor is a helper method to define mock.On call
//   - ctx context.Context
//   - title string
//   - author string
func (_e *MockMetadataSource_Expecter) SearchByTitleAndAuthor(ctx interface{}, title interface{}, author interface{}) *MockMetadataSource_SearchByTitleAndAuthor_Call {
	return &MockMetadataSource_SearchByTitleAndAuthor_Call{Call: _e.mock.On("SearchByTitleAndAuthor", ctx, title, author)}
}

func (_c *MockMetadataSource_SearchByTitleAndAuthor_Call) Run(run func(ctx context.Context, title string, author string)) *MockMetadataSource_SearchByTitleAndAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataSource_SearchByTitleAndAuthor_Call) Return(bookMetadatas []metadata.BookMetadata, err error) *MockMetadataSource_SearchByTitleAndAuthor_Call {
	_c.Call.Return(bookMetadatas, err)
	return _c
}

func (_c *MockMetadataSource_SearchByTitleAndAuthor_Call) RunAndReturn(run func(ctx context.Context, title string, author string) ([]metadata.BookMetadata, error)) *MockMetadataSource_SearchByTitleAndAuthor_Call {
	_c.Call.Return(run)
	return _c
}
