// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/metadata"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetadataExtractor creates a new instance of MockMetadataExtractor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataExtractor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataExtractor {
	mock := &MockMetadataExtractor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataExtractor is an autogenerated mock type for the MetadataExtractor type
type MockMetadataExtractor struct {
	mock.Mock
}

type MockMetadataExtractor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataExtractor) EXPECT() *MockMetadataExtractor_Expecter {
	return &MockMetadataExtractor_Expecter{mock: &_m.Mock}
}

// ExtractMetadata provides a mock function for the type MockMetadataExtractor
func (_mock *MockMetadataExtractor) ExtractMetadata(filePath string) (metadata.Metadata, error) {
	ret := _mock.Called(filePath)

	if len(ret) == 0 {
		panic("no return value specified for ExtractMetadata")
	}

	var r0 metadata.Metadata
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (metadata.Metadata, error)); ok {
		return returnFunc(filePath)
	}
	if returnFunc, ok := ret.Get(0).(func(string) metadata.Metadata); ok {
		r0 = returnFunc(filePath)
	} else {
		r0 = ret.Get(0).(metadata.Metadata)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(filePath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataExtractor_ExtractMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ExtractMetadata'
type MockMetadataExtractor_ExtractMetadata_Call struct {
	*mock.Call
}

// ExtractMetadata is a helper method to define mock.On call
//   - filePath string
func (_e *MockMetadataExtractor_Expecter) ExtractMetadata(filePath interface{}) *MockMetadataExtractor_ExtractMetadata_Call {
	return &MockMetadataExtractor_ExtractMetadata_Call{Call: _e.mock.On("ExtractMetadata", filePath)}
}

func (_c *MockMetadataExtractor_ExtractMetadata_Call) Run(run func(filePath string)) *MockMetadataExtractor_ExtractMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataExtractor_ExtractMetadata_Call) Return(metadata1 metadata.Metadata, err error) *MockMetadataExtractor_ExtractMetadata_Call {
	_c.Call.Return(metadata1, err)
	return _c
}

func (_c *MockMetadataExtractor_ExtractMetadata_Call) RunAndReturn(run func(filePath string) (metadata.Metadata, error)) *MockMetadataExtractor_ExtractMetadata_Call {
	_c.Call.Return(run)
	return _c
}
