# file: .github/trivy-secret.yaml
# version: 1.0.0
# guid: 3c4d5e6f-7a8b-9c0d-1e2f-3a4b5c6d7e8f

# Trivy Secret Scanning Configuration
# Customize secret detection rules

# Enable/disable secret scanning rules
rules:
  # AWS Access Key
  - id: aws-access-key
    enabled: true

  # AWS Secret Key
  - id: aws-secret-key
    enabled: true

  # GitHub Token
  - id: github-token
    enabled: true

  # GitHub Personal Access Token
  - id: github-pat
    enabled: true

  # Private Key (SSH, RSA, etc.)
  - id: private-key
    enabled: true

  # Generic API Key
  - id: generic-api-key
    enabled: true

# Path exclusions for secret scanning
exclude-paths:
  - "**/test/**"
  - "**/tests/**"
  - "**/*.test.js"
  - "**/*.spec.js"
  - "**/*.test.ts"
  - "**/*.spec.ts"
  - "**/node_modules/**"
  - "**/vendor/**"
  - "**/.git/**"
  - "**/build/**"
  - "**/dist/**"

# Allow specific patterns (false positives)
allow-patterns:
  # Example: Allow test API keys with specific prefix
  # - "test_api_key_.*"
  # - "demo_.*"
