# file: .mockery.yaml
# version: 1.1.0
# guid: 9a0b1c2d-3e4f-5a6b-7c8d-9e0f1a2b3c4d

# Mockery v3 configuration
packages:
  github.com/jdfalk/audiobook-organizer/internal/database:
    interfaces:
      Store:
