// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package duplicatesmocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/merge"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMergeService creates a new instance of MockMergeService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMergeService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMergeService {
	mock := &MockMergeService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMergeService is an autogenerated mock type for the MergeService type
type MockMergeService struct {
	mock.Mock
}

type MockMergeService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMergeService) EXPECT() *MockMergeService_Expecter {
	return &MockMergeService_Expecter{mock: &_m.Mock}
}

// MergeBooks provides a mock function for the type MockMergeService
func (_mock *MockMergeService) MergeBooks(bookIDs []string, primaryID string) (*merge.Result, error) {
	ret := _mock.Called(bookIDs, primaryID)

	if len(ret) == 0 {
		panic("no return value specified for MergeBooks")
	}

	var r0 *merge.Result
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string, string) (*merge.Result, error)); ok {
		return returnFunc(bookIDs, primaryID)
	}
	if returnFunc, ok := ret.Get(0).(func([]string, string) *merge.Result); ok {
		r0 = returnFunc(bookIDs, primaryID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*merge.Result)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string, string) error); ok {
		r1 = returnFunc(bookIDs, primaryID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMergeService_MergeBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MergeBooks'
type MockMergeService_MergeBooks_Call struct {
	*mock.Call
}

// MergeBooks is a helper method to define mock.On call
//   - bookIDs []string
//   - primaryID string
func (_e *MockMergeService_Expecter) MergeBooks(bookIDs interface{}, primaryID interface{}) *MockMergeService_MergeBooks_Call {
	return &MockMergeService_MergeBooks_Call{Call: _e.mock.On("MergeBooks", bookIDs, primaryID)}
}

func (_c *MockMergeService_MergeBooks_Call) Run(run func(bookIDs []string, primaryID string)) *MockMergeService_MergeBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMergeService_MergeBooks_Call) Return(result *merge.Result, err error) *MockMergeService_MergeBooks_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockMergeService_MergeBooks_Call) RunAndReturn(run func(bookIDs []string, primaryID string) (*merge.Result, error)) *MockMergeService_MergeBooks_Call {
	_c.Call.Return(run)
	return _c
}
