// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package duplicatesmocks

import (
	"context"

	"github.com/falkcorp/audiobook-organizer/internal/audiobooks"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAudiobookService creates a new instance of MockAudiobookService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudiobookService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudiobookService {
	mock := &MockAudiobookService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAudiobookService is an autogenerated mock type for the AudiobookService type
type MockAudiobookService struct {
	mock.Mock
}

type MockAudiobookService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudiobookService) EXPECT() *MockAudiobookService_Expecter {
	return &MockAudiobookService_Expecter{mock: &_m.Mock}
}

// GetDuplicateBooks provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) GetDuplicateBooks(ctx context.Context) (*audiobooks.DuplicatesResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetDuplicateBooks")
	}

	var r0 *audiobooks.DuplicatesResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (*audiobooks.DuplicatesResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) *audiobooks.DuplicatesResult); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*audiobooks.DuplicatesResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_GetDuplicateBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuplicateBooks'
type MockAudiobookService_GetDuplicateBooks_Call struct {
	*mock.Call
}

// GetDuplicateBooks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAudiobookService_Expecter) GetDuplicateBooks(ctx interface{}) *MockAudiobookService_GetDuplicateBooks_Call {
	return &MockAudiobookService_GetDuplicateBooks_Call{Call: _e.mock.On("GetDuplicateBooks", ctx)}
}

func (_c *MockAudiobookService_GetDuplicateBooks_Call) Run(run func(ctx context.Context)) *MockAudiobookService_GetDuplicateBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAudiobookService_GetDuplicateBooks_Call) Return(duplicatesResult *audiobooks.DuplicatesResult, err error) *MockAudiobookService_GetDuplicateBooks_Call {
	_c.Call.Return(duplicatesResult, err)
	return _c
}

func (_c *MockAudiobookService_GetDuplicateBooks_Call) RunAndReturn(run func(ctx context.Context) (*audiobooks.DuplicatesResult, error)) *MockAudiobookService_GetDuplicateBooks_Call {
	_c.Call.Return(run)
	return _c
}
