// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRetentionStore creates a new instance of MockRetentionStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRetentionStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRetentionStore {
	mock := &MockRetentionStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRetentionStore is an autogenerated mock type for the RetentionStore type
type MockRetentionStore struct {
	mock.Mock
}

type MockRetentionStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRetentionStore) EXPECT() *MockRetentionStore_Expecter {
	return &MockRetentionStore_Expecter{mock: &_m.Mock}
}

// PruneOperationChanges provides a mock function for the type MockRetentionStore
func (_mock *MockRetentionStore) PruneOperationChanges(olderThan time.Time) (int, error) {
	ret := _mock.Called(olderThan)

	if len(ret) == 0 {
		panic("no return value specified for PruneOperationChanges")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) (int, error)); ok {
		return returnFunc(olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) int); ok {
		r0 = returnFunc(olderThan)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRetentionStore_PruneOperationChanges_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneOperationChanges'
type MockRetentionStore_PruneOperationChanges_Call struct {
	*mock.Call
}

// PruneOperationChanges is a helper method to define mock.On call
//   - olderThan time.Time
func (_e *MockRetentionStore_Expecter) PruneOperationChanges(olderThan interface{}) *MockRetentionStore_PruneOperationChanges_Call {
	return &MockRetentionStore_PruneOperationChanges_Call{Call: _e.mock.On("PruneOperationChanges", olderThan)}
}

func (_c *MockRetentionStore_PruneOperationChanges_Call) Run(run func(olderThan time.Time)) *MockRetentionStore_PruneOperationChanges_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRetentionStore_PruneOperationChanges_Call) Return(n int, err error) *MockRetentionStore_PruneOperationChanges_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRetentionStore_PruneOperationChanges_Call) RunAndReturn(run func(olderThan time.Time) (int, error)) *MockRetentionStore_PruneOperationChanges_Call {
	_c.Call.Return(run)
	return _c
}

// PruneOperationLogs provides a mock function for the type MockRetentionStore
func (_mock *MockRetentionStore) PruneOperationLogs(olderThan time.Time) (int, error) {
	ret := _mock.Called(olderThan)

	if len(ret) == 0 {
		panic("no return value specified for PruneOperationLogs")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) (int, error)); ok {
		return returnFunc(olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) int); ok {
		r0 = returnFunc(olderThan)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRetentionStore_PruneOperationLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneOperationLogs'
type MockRetentionStore_PruneOperationLogs_Call struct {
	*mock.Call
}

// PruneOperationLogs is a helper method to define mock.On call
//   - olderThan time.Time
func (_e *MockRetentionStore_Expecter) PruneOperationLogs(olderThan interface{}) *MockRetentionStore_PruneOperationLogs_Call {
	return &MockRetentionStore_PruneOperationLogs_Call{Call: _e.mock.On("PruneOperationLogs", olderThan)}
}

func (_c *MockRetentionStore_PruneOperationLogs_Call) Run(run func(olderThan time.Time)) *MockRetentionStore_PruneOperationLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRetentionStore_PruneOperationLogs_Call) Return(n int, err error) *MockRetentionStore_PruneOperationLogs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRetentionStore_PruneOperationLogs_Call) RunAndReturn(run func(olderThan time.Time) (int, error)) *MockRetentionStore_PruneOperationLogs_Call {
	_c.Call.Return(run)
	return _c
}

// PruneSystemActivityLogs provides a mock function for the type MockRetentionStore
func (_mock *MockRetentionStore) PruneSystemActivityLogs(olderThan time.Time) (int, error) {
	ret := _mock.Called(olderThan)

	if len(ret) == 0 {
		panic("no return value specified for PruneSystemActivityLogs")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(time.Time) (int, error)); ok {
		return returnFunc(olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(time.Time) int); ok {
		r0 = returnFunc(olderThan)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(time.Time) error); ok {
		r1 = returnFunc(olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRetentionStore_PruneSystemActivityLogs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PruneSystemActivityLogs'
type MockRetentionStore_PruneSystemActivityLogs_Call struct {
	*mock.Call
}

// PruneSystemActivityLogs is a helper method to define mock.On call
//   - olderThan time.Time
func (_e *MockRetentionStore_Expecter) PruneSystemActivityLogs(olderThan interface{}) *MockRetentionStore_PruneSystemActivityLogs_Call {
	return &MockRetentionStore_PruneSystemActivityLogs_Call{Call: _e.mock.On("PruneSystemActivityLogs", olderThan)}
}

func (_c *MockRetentionStore_PruneSystemActivityLogs_Call) Run(run func(olderThan time.Time)) *MockRetentionStore_PruneSystemActivityLogs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 time.Time
		if args[0] != nil {
			arg0 = args[0].(time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRetentionStore_PruneSystemActivityLogs_Call) Return(n int, err error) *MockRetentionStore_PruneSystemActivityLogs_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockRetentionStore_PruneSystemActivityLogs_Call) RunAndReturn(run func(olderThan time.Time) (int, error)) *MockRetentionStore_PruneSystemActivityLogs_Call {
	_c.Call.Return(run)
	return _c
}
