// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metadatamocks

import (
	"context"

	"github.com/falkcorp/audiobook-organizer/internal/database"
	"github.com/falkcorp/audiobook-organizer/internal/metadata"
	"github.com/falkcorp/audiobook-organizer/internal/metafetch"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMetadataFetchService creates a new instance of MockMetadataFetchService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMetadataFetchService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMetadataFetchService {
	mock := &MockMetadataFetchService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMetadataFetchService is an autogenerated mock type for the MetadataFetchService type
type MockMetadataFetchService struct {
	mock.Mock
}

type MockMetadataFetchService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMetadataFetchService) EXPECT() *MockMetadataFetchService_Expecter {
	return &MockMetadataFetchService_Expecter{mock: &_m.Mock}
}

// ApplyMetadataCandidate provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) ApplyMetadataCandidate(id string, candidate metafetch.MetadataCandidate, fields []string) (*metafetch.FetchMetadataResponse, error) {
	ret := _mock.Called(id, candidate, fields)

	if len(ret) == 0 {
		panic("no return value specified for ApplyMetadataCandidate")
	}

	var r0 *metafetch.FetchMetadataResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, metafetch.MetadataCandidate, []string) (*metafetch.FetchMetadataResponse, error)); ok {
		return returnFunc(id, candidate, fields)
	}
	if returnFunc, ok := ret.Get(0).(func(string, metafetch.MetadataCandidate, []string) *metafetch.FetchMetadataResponse); ok {
		r0 = returnFunc(id, candidate, fields)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metafetch.FetchMetadataResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, metafetch.MetadataCandidate, []string) error); ok {
		r1 = returnFunc(id, candidate, fields)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataFetchService_ApplyMetadataCandidate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyMetadataCandidate'
type MockMetadataFetchService_ApplyMetadataCandidate_Call struct {
	*mock.Call
}

// ApplyMetadataCandidate is a helper method to define mock.On call
//   - id string
//   - candidate metafetch.MetadataCandidate
//   - fields []string
func (_e *MockMetadataFetchService_Expecter) ApplyMetadataCandidate(id interface{}, candidate interface{}, fields interface{}) *MockMetadataFetchService_ApplyMetadataCandidate_Call {
	return &MockMetadataFetchService_ApplyMetadataCandidate_Call{Call: _e.mock.On("ApplyMetadataCandidate", id, candidate, fields)}
}

func (_c *MockMetadataFetchService_ApplyMetadataCandidate_Call) Run(run func(id string, candidate metafetch.MetadataCandidate, fields []string)) *MockMetadataFetchService_ApplyMetadataCandidate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 metafetch.MetadataCandidate
		if args[1] != nil {
			arg1 = args[1].(metafetch.MetadataCandidate)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_ApplyMetadataCandidate_Call) Return(fetchMetadataResponse *metafetch.FetchMetadataResponse, err error) *MockMetadataFetchService_ApplyMetadataCandidate_Call {
	_c.Call.Return(fetchMetadataResponse, err)
	return _c
}

func (_c *MockMetadataFetchService_ApplyMetadataCandidate_Call) RunAndReturn(run func(id string, candidate metafetch.MetadataCandidate, fields []string) (*metafetch.FetchMetadataResponse, error)) *MockMetadataFetchService_ApplyMetadataCandidate_Call {
	_c.Call.Return(run)
	return _c
}

// ApplyMetadataFileIO provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) ApplyMetadataFileIO(id string) {
	_mock.Called(id)
	return
}

// MockMetadataFetchService_ApplyMetadataFileIO_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyMetadataFileIO'
type MockMetadataFetchService_ApplyMetadataFileIO_Call struct {
	*mock.Call
}

// ApplyMetadataFileIO is a helper method to define mock.On call
//   - id string
func (_e *MockMetadataFetchService_Expecter) ApplyMetadataFileIO(id interface{}) *MockMetadataFetchService_ApplyMetadataFileIO_Call {
	return &MockMetadataFetchService_ApplyMetadataFileIO_Call{Call: _e.mock.On("ApplyMetadataFileIO", id)}
}

func (_c *MockMetadataFetchService_ApplyMetadataFileIO_Call) Run(run func(id string)) *MockMetadataFetchService_ApplyMetadataFileIO_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_ApplyMetadataFileIO_Call) Return() *MockMetadataFetchService_ApplyMetadataFileIO_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetadataFetchService_ApplyMetadataFileIO_Call) RunAndReturn(run func(id string)) *MockMetadataFetchService_ApplyMetadataFileIO_Call {
	_c.Run(run)
	return _c
}

// ApplyMetadataSystemTags provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) ApplyMetadataSystemTags(bookID string, sourceName string, language string) {
	_mock.Called(bookID, sourceName, language)
	return
}

// MockMetadataFetchService_ApplyMetadataSystemTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyMetadataSystemTags'
type MockMetadataFetchService_ApplyMetadataSystemTags_Call struct {
	*mock.Call
}

// ApplyMetadataSystemTags is a helper method to define mock.On call
//   - bookID string
//   - sourceName string
//   - language string
func (_e *MockMetadataFetchService_Expecter) ApplyMetadataSystemTags(bookID interface{}, sourceName interface{}, language interface{}) *MockMetadataFetchService_ApplyMetadataSystemTags_Call {
	return &MockMetadataFetchService_ApplyMetadataSystemTags_Call{Call: _e.mock.On("ApplyMetadataSystemTags", bookID, sourceName, language)}
}

func (_c *MockMetadataFetchService_ApplyMetadataSystemTags_Call) Run(run func(bookID string, sourceName string, language string)) *MockMetadataFetchService_ApplyMetadataSystemTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_ApplyMetadataSystemTags_Call) Return() *MockMetadataFetchService_ApplyMetadataSystemTags_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetadataFetchService_ApplyMetadataSystemTags_Call) RunAndReturn(run func(bookID string, sourceName string, language string)) *MockMetadataFetchService_ApplyMetadataSystemTags_Call {
	_c.Run(run)
	return _c
}

// FetchAndCache provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) FetchAndCache(ctx context.Context, bookID string, query string, author string, narrator string, series string, opts metafetch.SearchOptions) (*metafetch.MetadataCandidateCache, error) {
	ret := _mock.Called(ctx, bookID, query, author, narrator, series, opts)

	if len(ret) == 0 {
		panic("no return value specified for FetchAndCache")
	}

	var r0 *metafetch.MetadataCandidateCache
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, metafetch.SearchOptions) (*metafetch.MetadataCandidateCache, error)); ok {
		return returnFunc(ctx, bookID, query, author, narrator, series, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string, string, string, metafetch.SearchOptions) *metafetch.MetadataCandidateCache); ok {
		r0 = returnFunc(ctx, bookID, query, author, narrator, series, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metafetch.MetadataCandidateCache)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string, string, string, metafetch.SearchOptions) error); ok {
		r1 = returnFunc(ctx, bookID, query, author, narrator, series, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataFetchService_FetchAndCache_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchAndCache'
type MockMetadataFetchService_FetchAndCache_Call struct {
	*mock.Call
}

// FetchAndCache is a helper method to define mock.On call
//   - ctx context.Context
//   - bookID string
//   - query string
//   - author string
//   - narrator string
//   - series string
//   - opts metafetch.SearchOptions
func (_e *MockMetadataFetchService_Expecter) FetchAndCache(ctx interface{}, bookID interface{}, query interface{}, author interface{}, narrator interface{}, series interface{}, opts interface{}) *MockMetadataFetchService_FetchAndCache_Call {
	return &MockMetadataFetchService_FetchAndCache_Call{Call: _e.mock.On("FetchAndCache", ctx, bookID, query, author, narrator, series, opts)}
}

func (_c *MockMetadataFetchService_FetchAndCache_Call) Run(run func(ctx context.Context, bookID string, query string, author string, narrator string, series string, opts metafetch.SearchOptions)) *MockMetadataFetchService_FetchAndCache_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		var arg6 metafetch.SearchOptions
		if args[6] != nil {
			arg6 = args[6].(metafetch.SearchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_FetchAndCache_Call) Return(v *metafetch.MetadataCandidateCache, err error) *MockMetadataFetchService_FetchAndCache_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockMetadataFetchService_FetchAndCache_Call) RunAndReturn(run func(ctx context.Context, bookID string, query string, author string, narrator string, series string, opts metafetch.SearchOptions) (*metafetch.MetadataCandidateCache, error)) *MockMetadataFetchService_FetchAndCache_Call {
	_c.Call.Return(run)
	return _c
}

// FetchMetadataForBook provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) FetchMetadataForBook(id string) (*metafetch.FetchMetadataResponse, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for FetchMetadataForBook")
	}

	var r0 *metafetch.FetchMetadataResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*metafetch.FetchMetadataResponse, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *metafetch.FetchMetadataResponse); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metafetch.FetchMetadataResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataFetchService_FetchMetadataForBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FetchMetadataForBook'
type MockMetadataFetchService_FetchMetadataForBook_Call struct {
	*mock.Call
}

// FetchMetadataForBook is a helper method to define mock.On call
//   - id string
func (_e *MockMetadataFetchService_Expecter) FetchMetadataForBook(id interface{}) *MockMetadataFetchService_FetchMetadataForBook_Call {
	return &MockMetadataFetchService_FetchMetadataForBook_Call{Call: _e.mock.On("FetchMetadataForBook", id)}
}

func (_c *MockMetadataFetchService_FetchMetadataForBook_Call) Run(run func(id string)) *MockMetadataFetchService_FetchMetadataForBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_FetchMetadataForBook_Call) Return(fetchMetadataResponse *metafetch.FetchMetadataResponse, err error) *MockMetadataFetchService_FetchMetadataForBook_Call {
	_c.Call.Return(fetchMetadataResponse, err)
	return _c
}

func (_c *MockMetadataFetchService_FetchMetadataForBook_Call) RunAndReturn(run func(id string) (*metafetch.FetchMetadataResponse, error)) *MockMetadataFetchService_FetchMetadataForBook_Call {
	_c.Call.Return(run)
	return _c
}

// GetCachedCandidates provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) GetCachedCandidates(bookID string) (*metafetch.MetadataCandidateCache, bool, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetCachedCandidates")
	}

	var r0 *metafetch.MetadataCandidateCache
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string) (*metafetch.MetadataCandidateCache, bool, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *metafetch.MetadataCandidateCache); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metafetch.MetadataCandidateCache)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(string) error); ok {
		r2 = returnFunc(bookID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockMetadataFetchService_GetCachedCandidates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCachedCandidates'
type MockMetadataFetchService_GetCachedCandidates_Call struct {
	*mock.Call
}

// GetCachedCandidates is a helper method to define mock.On call
//   - bookID string
func (_e *MockMetadataFetchService_Expecter) GetCachedCandidates(bookID interface{}) *MockMetadataFetchService_GetCachedCandidates_Call {
	return &MockMetadataFetchService_GetCachedCandidates_Call{Call: _e.mock.On("GetCachedCandidates", bookID)}
}

func (_c *MockMetadataFetchService_GetCachedCandidates_Call) Run(run func(bookID string)) *MockMetadataFetchService_GetCachedCandidates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_GetCachedCandidates_Call) Return(v *metafetch.MetadataCandidateCache, b bool, err error) *MockMetadataFetchService_GetCachedCandidates_Call {
	_c.Call.Return(v, b, err)
	return _c
}

func (_c *MockMetadataFetchService_GetCachedCandidates_Call) RunAndReturn(run func(bookID string) (*metafetch.MetadataCandidateCache, bool, error)) *MockMetadataFetchService_GetCachedCandidates_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateCachedCandidates provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) InvalidateCachedCandidates(bookID string) error {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for InvalidateCachedCandidates")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(bookID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataFetchService_InvalidateCachedCandidates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateCachedCandidates'
type MockMetadataFetchService_InvalidateCachedCandidates_Call struct {
	*mock.Call
}

// InvalidateCachedCandidates is a helper method to define mock.On call
//   - bookID string
func (_e *MockMetadataFetchService_Expecter) InvalidateCachedCandidates(bookID interface{}) *MockMetadataFetchService_InvalidateCachedCandidates_Call {
	return &MockMetadataFetchService_InvalidateCachedCandidates_Call{Call: _e.mock.On("InvalidateCachedCandidates", bookID)}
}

func (_c *MockMetadataFetchService_InvalidateCachedCandidates_Call) Run(run func(bookID string)) *MockMetadataFetchService_InvalidateCachedCandidates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_InvalidateCachedCandidates_Call) Return(err error) *MockMetadataFetchService_InvalidateCachedCandidates_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataFetchService_InvalidateCachedCandidates_Call) RunAndReturn(run func(bookID string) error) *MockMetadataFetchService_InvalidateCachedCandidates_Call {
	_c.Call.Return(run)
	return _c
}

// MarkNoMatch provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) MarkNoMatch(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for MarkNoMatch")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataFetchService_MarkNoMatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkNoMatch'
type MockMetadataFetchService_MarkNoMatch_Call struct {
	*mock.Call
}

// MarkNoMatch is a helper method to define mock.On call
//   - id string
func (_e *MockMetadataFetchService_Expecter) MarkNoMatch(id interface{}) *MockMetadataFetchService_MarkNoMatch_Call {
	return &MockMetadataFetchService_MarkNoMatch_Call{Call: _e.mock.On("MarkNoMatch", id)}
}

func (_c *MockMetadataFetchService_MarkNoMatch_Call) Run(run func(id string)) *MockMetadataFetchService_MarkNoMatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_MarkNoMatch_Call) Return(err error) *MockMetadataFetchService_MarkNoMatch_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataFetchService_MarkNoMatch_Call) RunAndReturn(run func(id string) error) *MockMetadataFetchService_MarkNoMatch_Call {
	_c.Call.Return(run)
	return _c
}

// RecordChangeHistory provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) RecordChangeHistory(book *database.Book, meta metadata.BookMetadata, sourceName string) {
	_mock.Called(book, meta, sourceName)
	return
}

// MockMetadataFetchService_RecordChangeHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecordChangeHistory'
type MockMetadataFetchService_RecordChangeHistory_Call struct {
	*mock.Call
}

// RecordChangeHistory is a helper method to define mock.On call
//   - book *database.Book
//   - meta metadata.BookMetadata
//   - sourceName string
func (_e *MockMetadataFetchService_Expecter) RecordChangeHistory(book interface{}, meta interface{}, sourceName interface{}) *MockMetadataFetchService_RecordChangeHistory_Call {
	return &MockMetadataFetchService_RecordChangeHistory_Call{Call: _e.mock.On("RecordChangeHistory", book, meta, sourceName)}
}

func (_c *MockMetadataFetchService_RecordChangeHistory_Call) Run(run func(book *database.Book, meta metadata.BookMetadata, sourceName string)) *MockMetadataFetchService_RecordChangeHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.Book
		if args[0] != nil {
			arg0 = args[0].(*database.Book)
		}
		var arg1 metadata.BookMetadata
		if args[1] != nil {
			arg1 = args[1].(metadata.BookMetadata)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_RecordChangeHistory_Call) Return() *MockMetadataFetchService_RecordChangeHistory_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockMetadataFetchService_RecordChangeHistory_Call) RunAndReturn(run func(book *database.Book, meta metadata.BookMetadata, sourceName string)) *MockMetadataFetchService_RecordChangeHistory_Call {
	_c.Run(run)
	return _c
}

// RunApplyPipelineRenameOnly provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) RunApplyPipelineRenameOnly(id string, book *database.Book) error {
	ret := _mock.Called(id, book)

	if len(ret) == 0 {
		panic("no return value specified for RunApplyPipelineRenameOnly")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) error); ok {
		r0 = returnFunc(id, book)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockMetadataFetchService_RunApplyPipelineRenameOnly_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunApplyPipelineRenameOnly'
type MockMetadataFetchService_RunApplyPipelineRenameOnly_Call struct {
	*mock.Call
}

// RunApplyPipelineRenameOnly is a helper method to define mock.On call
//   - id string
//   - book *database.Book
func (_e *MockMetadataFetchService_Expecter) RunApplyPipelineRenameOnly(id interface{}, book interface{}) *MockMetadataFetchService_RunApplyPipelineRenameOnly_Call {
	return &MockMetadataFetchService_RunApplyPipelineRenameOnly_Call{Call: _e.mock.On("RunApplyPipelineRenameOnly", id, book)}
}

func (_c *MockMetadataFetchService_RunApplyPipelineRenameOnly_Call) Run(run func(id string, book *database.Book)) *MockMetadataFetchService_RunApplyPipelineRenameOnly_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *database.Book
		if args[1] != nil {
			arg1 = args[1].(*database.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_RunApplyPipelineRenameOnly_Call) Return(err error) *MockMetadataFetchService_RunApplyPipelineRenameOnly_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockMetadataFetchService_RunApplyPipelineRenameOnly_Call) RunAndReturn(run func(id string, book *database.Book) error) *MockMetadataFetchService_RunApplyPipelineRenameOnly_Call {
	_c.Call.Return(run)
	return _c
}

// SearchMetadataForBookWithOptions provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) SearchMetadataForBookWithOptions(id string, query string, author string, narrator string, series string, opts metafetch.SearchOptions) (*metafetch.SearchMetadataResponse, error) {
	ret := _mock.Called(id, query, author, narrator, series, opts)

	if len(ret) == 0 {
		panic("no return value specified for SearchMetadataForBookWithOptions")
	}

	var r0 *metafetch.SearchMetadataResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string, metafetch.SearchOptions) (*metafetch.SearchMetadataResponse, error)); ok {
		return returnFunc(id, query, author, narrator, series, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, string, string, metafetch.SearchOptions) *metafetch.SearchMetadataResponse); ok {
		r0 = returnFunc(id, query, author, narrator, series, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*metafetch.SearchMetadataResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, string, string, metafetch.SearchOptions) error); ok {
		r1 = returnFunc(id, query, author, narrator, series, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataFetchService_SearchMetadataForBookWithOptions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchMetadataForBookWithOptions'
type MockMetadataFetchService_SearchMetadataForBookWithOptions_Call struct {
	*mock.Call
}

// SearchMetadataForBookWithOptions is a helper method to define mock.On call
//   - id string
//   - query string
//   - author string
//   - narrator string
//   - series string
//   - opts metafetch.SearchOptions
func (_e *MockMetadataFetchService_Expecter) SearchMetadataForBookWithOptions(id interface{}, query interface{}, author interface{}, narrator interface{}, series interface{}, opts interface{}) *MockMetadataFetchService_SearchMetadataForBookWithOptions_Call {
	return &MockMetadataFetchService_SearchMetadataForBookWithOptions_Call{Call: _e.mock.On("SearchMetadataForBookWithOptions", id, query, author, narrator, series, opts)}
}

func (_c *MockMetadataFetchService_SearchMetadataForBookWithOptions_Call) Run(run func(id string, query string, author string, narrator string, series string, opts metafetch.SearchOptions)) *MockMetadataFetchService_SearchMetadataForBookWithOptions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 metafetch.SearchOptions
		if args[5] != nil {
			arg5 = args[5].(metafetch.SearchOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_SearchMetadataForBookWithOptions_Call) Return(searchMetadataResponse *metafetch.SearchMetadataResponse, err error) *MockMetadataFetchService_SearchMetadataForBookWithOptions_Call {
	_c.Call.Return(searchMetadataResponse, err)
	return _c
}

func (_c *MockMetadataFetchService_SearchMetadataForBookWithOptions_Call) RunAndReturn(run func(id string, query string, author string, narrator string, series string, opts metafetch.SearchOptions) (*metafetch.SearchMetadataResponse, error)) *MockMetadataFetchService_SearchMetadataForBookWithOptions_Call {
	_c.Call.Return(run)
	return _c
}

// WriteBackMetadataForBook provides a mock function for the type MockMetadataFetchService
func (_mock *MockMetadataFetchService) WriteBackMetadataForBook(id string, segmentFilter ...[]string) (int, error) {
	var tmpRet mock.Arguments
	if len(segmentFilter) > 0 {
		tmpRet = _mock.Called(id, segmentFilter)
	} else {
		tmpRet = _mock.Called(id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for WriteBackMetadataForBook")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, ...[]string) (int, error)); ok {
		return returnFunc(id, segmentFilter...)
	}
	if returnFunc, ok := ret.Get(0).(func(string, ...[]string) int); ok {
		r0 = returnFunc(id, segmentFilter...)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string, ...[]string) error); ok {
		r1 = returnFunc(id, segmentFilter...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMetadataFetchService_WriteBackMetadataForBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteBackMetadataForBook'
type MockMetadataFetchService_WriteBackMetadataForBook_Call struct {
	*mock.Call
}

// WriteBackMetadataForBook is a helper method to define mock.On call
//   - id string
//   - segmentFilter ...[]string
func (_e *MockMetadataFetchService_Expecter) WriteBackMetadataForBook(id interface{}, segmentFilter ...interface{}) *MockMetadataFetchService_WriteBackMetadataForBook_Call {
	return &MockMetadataFetchService_WriteBackMetadataForBook_Call{Call: _e.mock.On("WriteBackMetadataForBook",
		append([]interface{}{id}, segmentFilter...)...)}
}

func (_c *MockMetadataFetchService_WriteBackMetadataForBook_Call) Run(run func(id string, segmentFilter ...[]string)) *MockMetadataFetchService_WriteBackMetadataForBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 [][]string
		var variadicArgs [][]string
		if len(args) > 1 {
			variadicArgs = args[1].([][]string)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockMetadataFetchService_WriteBackMetadataForBook_Call) Return(n int, err error) *MockMetadataFetchService_WriteBackMetadataForBook_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockMetadataFetchService_WriteBackMetadataForBook_Call) RunAndReturn(run func(id string, segmentFilter ...[]string) (int, error)) *MockMetadataFetchService_WriteBackMetadataForBook_Call {
	_c.Call.Return(run)
	return _c
}
