// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package metadatamocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileIOPool creates a new instance of MockFileIOPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileIOPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileIOPool {
	mock := &MockFileIOPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileIOPool is an autogenerated mock type for the FileIOPool type
type MockFileIOPool struct {
	mock.Mock
}

type MockFileIOPool_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileIOPool) EXPECT() *MockFileIOPool_Expecter {
	return &MockFileIOPool_Expecter{mock: &_m.Mock}
}

// Submit provides a mock function for the type MockFileIOPool
func (_mock *MockFileIOPool) Submit(bookID string, fn func()) {
	_mock.Called(bookID, fn)
	return
}

// MockFileIOPool_Submit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Submit'
type MockFileIOPool_Submit_Call struct {
	*mock.Call
}

// Submit is a helper method to define mock.On call
//   - bookID string
//   - fn func()
func (_e *MockFileIOPool_Expecter) Submit(bookID interface{}, fn interface{}) *MockFileIOPool_Submit_Call {
	return &MockFileIOPool_Submit_Call{Call: _e.mock.On("Submit", bookID, fn)}
}

func (_c *MockFileIOPool_Submit_Call) Run(run func(bookID string, fn func())) *MockFileIOPool_Submit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 func()
		if args[1] != nil {
			arg1 = args[1].(func())
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFileIOPool_Submit_Call) Return() *MockFileIOPool_Submit_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockFileIOPool_Submit_Call) RunAndReturn(run func(bookID string, fn func())) *MockFileIOPool_Submit_Call {
	_c.Run(run)
	return _c
}
