// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package operationsmocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAIScanLister creates a new instance of MockAIScanLister. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAIScanLister(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAIScanLister {
	mock := &MockAIScanLister{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAIScanLister is an autogenerated mock type for the AIScanLister type
type MockAIScanLister struct {
	mock.Mock
}

type MockAIScanLister_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAIScanLister) EXPECT() *MockAIScanLister_Expecter {
	return &MockAIScanLister_Expecter{mock: &_m.Mock}
}

// ListScans provides a mock function for the type MockAIScanLister
func (_mock *MockAIScanLister) ListScans() ([]database.Scan, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListScans")
	}

	var r0 []database.Scan
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Scan, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Scan); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Scan)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAIScanLister_ListScans_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListScans'
type MockAIScanLister_ListScans_Call struct {
	*mock.Call
}

// ListScans is a helper method to define mock.On call
func (_e *MockAIScanLister_Expecter) ListScans() *MockAIScanLister_ListScans_Call {
	return &MockAIScanLister_ListScans_Call{Call: _e.mock.On("ListScans")}
}

func (_c *MockAIScanLister_ListScans_Call) Run(run func()) *MockAIScanLister_ListScans_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAIScanLister_ListScans_Call) Return(scans []database.Scan, err error) *MockAIScanLister_ListScans_Call {
	_c.Call.Return(scans, err)
	return _c
}

func (_c *MockAIScanLister_ListScans_Call) RunAndReturn(run func() ([]database.Scan, error)) *MockAIScanLister_ListScans_Call {
	_c.Call.Return(run)
	return _c
}
