// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package operationsmocks

import (
	"context"

	"github.com/jdfalk/audiobook-organizer/internal/operations/registry"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOperationsRegistry creates a new instance of MockOperationsRegistry. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationsRegistry(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationsRegistry {
	mock := &MockOperationsRegistry{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperationsRegistry is an autogenerated mock type for the OperationsRegistry type
type MockOperationsRegistry struct {
	mock.Mock
}

type MockOperationsRegistry_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationsRegistry) EXPECT() *MockOperationsRegistry_Expecter {
	return &MockOperationsRegistry_Expecter{mock: &_m.Mock}
}

// Cancel provides a mock function for the type MockOperationsRegistry
func (_mock *MockOperationsRegistry) Cancel(opID string) error {
	ret := _mock.Called(opID)

	if len(ret) == 0 {
		panic("no return value specified for Cancel")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(opID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOperationsRegistry_Cancel_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Cancel'
type MockOperationsRegistry_Cancel_Call struct {
	*mock.Call
}

// Cancel is a helper method to define mock.On call
//   - opID string
func (_e *MockOperationsRegistry_Expecter) Cancel(opID interface{}) *MockOperationsRegistry_Cancel_Call {
	return &MockOperationsRegistry_Cancel_Call{Call: _e.mock.On("Cancel", opID)}
}

func (_c *MockOperationsRegistry_Cancel_Call) Run(run func(opID string)) *MockOperationsRegistry_Cancel_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockOperationsRegistry_Cancel_Call) Return(err error) *MockOperationsRegistry_Cancel_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOperationsRegistry_Cancel_Call) RunAndReturn(run func(opID string) error) *MockOperationsRegistry_Cancel_Call {
	_c.Call.Return(run)
	return _c
}

// EnqueueOp provides a mock function for the type MockOperationsRegistry
func (_mock *MockOperationsRegistry) EnqueueOp(ctx context.Context, defID string, params any, opts ...registry.EnqueueOption) (string, error) {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, defID, params, opts)
	} else {
		tmpRet = _mock.Called(ctx, defID, params)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for EnqueueOp")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...registry.EnqueueOption) (string, error)); ok {
		return returnFunc(ctx, defID, params, opts...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, any, ...registry.EnqueueOption) string); ok {
		r0 = returnFunc(ctx, defID, params, opts...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, any, ...registry.EnqueueOption) error); ok {
		r1 = returnFunc(ctx, defID, params, opts...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOperationsRegistry_EnqueueOp_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnqueueOp'
type MockOperationsRegistry_EnqueueOp_Call struct {
	*mock.Call
}

// EnqueueOp is a helper method to define mock.On call
//   - ctx context.Context
//   - defID string
//   - params any
//   - opts ...registry.EnqueueOption
func (_e *MockOperationsRegistry_Expecter) EnqueueOp(ctx interface{}, defID interface{}, params interface{}, opts ...interface{}) *MockOperationsRegistry_EnqueueOp_Call {
	return &MockOperationsRegistry_EnqueueOp_Call{Call: _e.mock.On("EnqueueOp",
		append([]interface{}{ctx, defID, params}, opts...)...)}
}

func (_c *MockOperationsRegistry_EnqueueOp_Call) Run(run func(ctx context.Context, defID string, params any, opts ...registry.EnqueueOption)) *MockOperationsRegistry_EnqueueOp_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 any
		if args[2] != nil {
			arg2 = args[2].(any)
		}
		var arg3 []registry.EnqueueOption
		var variadicArgs []registry.EnqueueOption
		if len(args) > 3 {
			variadicArgs = args[3].([]registry.EnqueueOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockOperationsRegistry_EnqueueOp_Call) Return(s string, err error) *MockOperationsRegistry_EnqueueOp_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOperationsRegistry_EnqueueOp_Call) RunAndReturn(run func(ctx context.Context, defID string, params any, opts ...registry.EnqueueOption) (string, error)) *MockOperationsRegistry_EnqueueOp_Call {
	_c.Call.Return(run)
	return _c
}
