// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package operationsmocks

import (
	"context"

	"github.com/jdfalk/audiobook-organizer/internal/database"
	"github.com/jdfalk/audiobook-organizer/internal/scheduler"
	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduler creates a new instance of MockScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduler {
	mock := &MockScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduler is an autogenerated mock type for the Scheduler type
type MockScheduler struct {
	mock.Mock
}

type MockScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduler) EXPECT() *MockScheduler_Expecter {
	return &MockScheduler_Expecter{mock: &_m.Mock}
}

// GetLastMaintenanceRunDate provides a mock function for the type MockScheduler
func (_mock *MockScheduler) GetLastMaintenanceRunDate() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetLastMaintenanceRunDate")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockScheduler_GetLastMaintenanceRunDate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLastMaintenanceRunDate'
type MockScheduler_GetLastMaintenanceRunDate_Call struct {
	*mock.Call
}

// GetLastMaintenanceRunDate is a helper method to define mock.On call
func (_e *MockScheduler_Expecter) GetLastMaintenanceRunDate() *MockScheduler_GetLastMaintenanceRunDate_Call {
	return &MockScheduler_GetLastMaintenanceRunDate_Call{Call: _e.mock.On("GetLastMaintenanceRunDate")}
}

func (_c *MockScheduler_GetLastMaintenanceRunDate_Call) Run(run func()) *MockScheduler_GetLastMaintenanceRunDate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScheduler_GetLastMaintenanceRunDate_Call) Return(s string) *MockScheduler_GetLastMaintenanceRunDate_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockScheduler_GetLastMaintenanceRunDate_Call) RunAndReturn(run func() string) *MockScheduler_GetLastMaintenanceRunDate_Call {
	_c.Call.Return(run)
	return _c
}

// IsMaintenanceRunning provides a mock function for the type MockScheduler
func (_mock *MockScheduler) IsMaintenanceRunning() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsMaintenanceRunning")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockScheduler_IsMaintenanceRunning_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsMaintenanceRunning'
type MockScheduler_IsMaintenanceRunning_Call struct {
	*mock.Call
}

// IsMaintenanceRunning is a helper method to define mock.On call
func (_e *MockScheduler_Expecter) IsMaintenanceRunning() *MockScheduler_IsMaintenanceRunning_Call {
	return &MockScheduler_IsMaintenanceRunning_Call{Call: _e.mock.On("IsMaintenanceRunning")}
}

func (_c *MockScheduler_IsMaintenanceRunning_Call) Run(run func()) *MockScheduler_IsMaintenanceRunning_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScheduler_IsMaintenanceRunning_Call) Return(b bool) *MockScheduler_IsMaintenanceRunning_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockScheduler_IsMaintenanceRunning_Call) RunAndReturn(run func() bool) *MockScheduler_IsMaintenanceRunning_Call {
	_c.Call.Return(run)
	return _c
}

// ListTasks provides a mock function for the type MockScheduler
func (_mock *MockScheduler) ListTasks() []scheduler.TaskInfo {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListTasks")
	}

	var r0 []scheduler.TaskInfo
	if returnFunc, ok := ret.Get(0).(func() []scheduler.TaskInfo); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]scheduler.TaskInfo)
		}
	}
	return r0
}

// MockScheduler_ListTasks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListTasks'
type MockScheduler_ListTasks_Call struct {
	*mock.Call
}

// ListTasks is a helper method to define mock.On call
func (_e *MockScheduler_Expecter) ListTasks() *MockScheduler_ListTasks_Call {
	return &MockScheduler_ListTasks_Call{Call: _e.mock.On("ListTasks")}
}

func (_c *MockScheduler_ListTasks_Call) Run(run func()) *MockScheduler_ListTasks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockScheduler_ListTasks_Call) Return(taskInfos []scheduler.TaskInfo) *MockScheduler_ListTasks_Call {
	_c.Call.Return(taskInfos)
	return _c
}

func (_c *MockScheduler_ListTasks_Call) RunAndReturn(run func() []scheduler.TaskInfo) *MockScheduler_ListTasks_Call {
	_c.Call.Return(run)
	return _c
}

// RunMaintenanceWindow provides a mock function for the type MockScheduler
func (_mock *MockScheduler) RunMaintenanceWindow(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RunMaintenanceWindow")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockScheduler_RunMaintenanceWindow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunMaintenanceWindow'
type MockScheduler_RunMaintenanceWindow_Call struct {
	*mock.Call
}

// RunMaintenanceWindow is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockScheduler_Expecter) RunMaintenanceWindow(ctx interface{}) *MockScheduler_RunMaintenanceWindow_Call {
	return &MockScheduler_RunMaintenanceWindow_Call{Call: _e.mock.On("RunMaintenanceWindow", ctx)}
}

func (_c *MockScheduler_RunMaintenanceWindow_Call) Run(run func(ctx context.Context)) *MockScheduler_RunMaintenanceWindow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduler_RunMaintenanceWindow_Call) Return(err error) *MockScheduler_RunMaintenanceWindow_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockScheduler_RunMaintenanceWindow_Call) RunAndReturn(run func(ctx context.Context) error) *MockScheduler_RunMaintenanceWindow_Call {
	_c.Call.Return(run)
	return _c
}

// RunTaskManual provides a mock function for the type MockScheduler
func (_mock *MockScheduler) RunTaskManual(name string) (*database.Operation, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for RunTaskManual")
	}

	var r0 *database.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Operation, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Operation); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockScheduler_RunTaskManual_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunTaskManual'
type MockScheduler_RunTaskManual_Call struct {
	*mock.Call
}

// RunTaskManual is a helper method to define mock.On call
//   - name string
func (_e *MockScheduler_Expecter) RunTaskManual(name interface{}) *MockScheduler_RunTaskManual_Call {
	return &MockScheduler_RunTaskManual_Call{Call: _e.mock.On("RunTaskManual", name)}
}

func (_c *MockScheduler_RunTaskManual_Call) Run(run func(name string)) *MockScheduler_RunTaskManual_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduler_RunTaskManual_Call) Return(operation *database.Operation, err error) *MockScheduler_RunTaskManual_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockScheduler_RunTaskManual_Call) RunAndReturn(run func(name string) (*database.Operation, error)) *MockScheduler_RunTaskManual_Call {
	_c.Call.Return(run)
	return _c
}
