// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package entitiesmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEntitiesStore creates a new instance of MockEntitiesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEntitiesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEntitiesStore {
	mock := &MockEntitiesStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEntitiesStore is an autogenerated mock type for the EntitiesStore type
type MockEntitiesStore struct {
	mock.Mock
}

type MockEntitiesStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEntitiesStore) EXPECT() *MockEntitiesStore_Expecter {
	return &MockEntitiesStore_Expecter{mock: &_m.Mock}
}

// CountAuthors provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) CountAuthors() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountAuthors")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_CountAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAuthors'
type MockEntitiesStore_CountAuthors_Call struct {
	*mock.Call
}

// CountAuthors is a helper method to define mock.On call
func (_e *MockEntitiesStore_Expecter) CountAuthors() *MockEntitiesStore_CountAuthors_Call {
	return &MockEntitiesStore_CountAuthors_Call{Call: _e.mock.On("CountAuthors")}
}

func (_c *MockEntitiesStore_CountAuthors_Call) Run(run func()) *MockEntitiesStore_CountAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntitiesStore_CountAuthors_Call) Return(n int, err error) *MockEntitiesStore_CountAuthors_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockEntitiesStore_CountAuthors_Call) RunAndReturn(run func() (int, error)) *MockEntitiesStore_CountAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// CountSeries provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) CountSeries() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountSeries")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_CountSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountSeries'
type MockEntitiesStore_CountSeries_Call struct {
	*mock.Call
}

// CountSeries is a helper method to define mock.On call
func (_e *MockEntitiesStore_Expecter) CountSeries() *MockEntitiesStore_CountSeries_Call {
	return &MockEntitiesStore_CountSeries_Call{Call: _e.mock.On("CountSeries")}
}

func (_c *MockEntitiesStore_CountSeries_Call) Run(run func()) *MockEntitiesStore_CountSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntitiesStore_CountSeries_Call) Return(n int, err error) *MockEntitiesStore_CountSeries_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockEntitiesStore_CountSeries_Call) RunAndReturn(run func() (int, error)) *MockEntitiesStore_CountSeries_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAuthor provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) CreateAuthor(name string) (*database.Author, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthor")
	}

	var r0 *database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Author, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Author); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_CreateAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthor'
type MockEntitiesStore_CreateAuthor_Call struct {
	*mock.Call
}

// CreateAuthor is a helper method to define mock.On call
//   - name string
func (_e *MockEntitiesStore_Expecter) CreateAuthor(name interface{}) *MockEntitiesStore_CreateAuthor_Call {
	return &MockEntitiesStore_CreateAuthor_Call{Call: _e.mock.On("CreateAuthor", name)}
}

func (_c *MockEntitiesStore_CreateAuthor_Call) Run(run func(name string)) *MockEntitiesStore_CreateAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_CreateAuthor_Call) Return(author *database.Author, err error) *MockEntitiesStore_CreateAuthor_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockEntitiesStore_CreateAuthor_Call) RunAndReturn(run func(name string) (*database.Author, error)) *MockEntitiesStore_CreateAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// CreateAuthorAlias provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) CreateAuthorAlias(authorID int, aliasName string, aliasType string) (*database.AuthorAlias, error) {
	ret := _mock.Called(authorID, aliasName, aliasType)

	if len(ret) == 0 {
		panic("no return value specified for CreateAuthorAlias")
	}

	var r0 *database.AuthorAlias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, string, string) (*database.AuthorAlias, error)); ok {
		return returnFunc(authorID, aliasName, aliasType)
	}
	if returnFunc, ok := ret.Get(0).(func(int, string, string) *database.AuthorAlias); ok {
		r0 = returnFunc(authorID, aliasName, aliasType)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.AuthorAlias)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, string, string) error); ok {
		r1 = returnFunc(authorID, aliasName, aliasType)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_CreateAuthorAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateAuthorAlias'
type MockEntitiesStore_CreateAuthorAlias_Call struct {
	*mock.Call
}

// CreateAuthorAlias is a helper method to define mock.On call
//   - authorID int
//   - aliasName string
//   - aliasType string
func (_e *MockEntitiesStore_Expecter) CreateAuthorAlias(authorID interface{}, aliasName interface{}, aliasType interface{}) *MockEntitiesStore_CreateAuthorAlias_Call {
	return &MockEntitiesStore_CreateAuthorAlias_Call{Call: _e.mock.On("CreateAuthorAlias", authorID, aliasName, aliasType)}
}

func (_c *MockEntitiesStore_CreateAuthorAlias_Call) Run(run func(authorID int, aliasName string, aliasType string)) *MockEntitiesStore_CreateAuthorAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_CreateAuthorAlias_Call) Return(authorAlias *database.AuthorAlias, err error) *MockEntitiesStore_CreateAuthorAlias_Call {
	_c.Call.Return(authorAlias, err)
	return _c
}

func (_c *MockEntitiesStore_CreateAuthorAlias_Call) RunAndReturn(run func(authorID int, aliasName string, aliasType string) (*database.AuthorAlias, error)) *MockEntitiesStore_CreateAuthorAlias_Call {
	_c.Call.Return(run)
	return _c
}

// CreateNarrator provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) CreateNarrator(name string) (*database.Narrator, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for CreateNarrator")
	}

	var r0 *database.Narrator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Narrator, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Narrator); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Narrator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_CreateNarrator_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateNarrator'
type MockEntitiesStore_CreateNarrator_Call struct {
	*mock.Call
}

// CreateNarrator is a helper method to define mock.On call
//   - name string
func (_e *MockEntitiesStore_Expecter) CreateNarrator(name interface{}) *MockEntitiesStore_CreateNarrator_Call {
	return &MockEntitiesStore_CreateNarrator_Call{Call: _e.mock.On("CreateNarrator", name)}
}

func (_c *MockEntitiesStore_CreateNarrator_Call) Run(run func(name string)) *MockEntitiesStore_CreateNarrator_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_CreateNarrator_Call) Return(narrator *database.Narrator, err error) *MockEntitiesStore_CreateNarrator_Call {
	_c.Call.Return(narrator, err)
	return _c
}

func (_c *MockEntitiesStore_CreateNarrator_Call) RunAndReturn(run func(name string) (*database.Narrator, error)) *MockEntitiesStore_CreateNarrator_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOperation provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) CreateOperation(id string, opType string, folderPath *string) (*database.Operation, error) {
	ret := _mock.Called(id, opType, folderPath)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperation")
	}

	var r0 *database.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) (*database.Operation, error)); ok {
		return returnFunc(id, opType, folderPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) *database.Operation); ok {
		r0 = returnFunc(id, opType, folderPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *string) error); ok {
		r1 = returnFunc(id, opType, folderPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_CreateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOperation'
type MockEntitiesStore_CreateOperation_Call struct {
	*mock.Call
}

// CreateOperation is a helper method to define mock.On call
//   - id string
//   - opType string
//   - folderPath *string
func (_e *MockEntitiesStore_Expecter) CreateOperation(id interface{}, opType interface{}, folderPath interface{}) *MockEntitiesStore_CreateOperation_Call {
	return &MockEntitiesStore_CreateOperation_Call{Call: _e.mock.On("CreateOperation", id, opType, folderPath)}
}

func (_c *MockEntitiesStore_CreateOperation_Call) Run(run func(id string, opType string, folderPath *string)) *MockEntitiesStore_CreateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_CreateOperation_Call) Return(operation *database.Operation, err error) *MockEntitiesStore_CreateOperation_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockEntitiesStore_CreateOperation_Call) RunAndReturn(run func(id string, opType string, folderPath *string) (*database.Operation, error)) *MockEntitiesStore_CreateOperation_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSeries provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) CreateSeries(name string, authorID *int) (*database.Series, error) {
	ret := _mock.Called(name, authorID)

	if len(ret) == 0 {
		panic("no return value specified for CreateSeries")
	}

	var r0 *database.Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *int) (*database.Series, error)); ok {
		return returnFunc(name, authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *int) *database.Series); ok {
		r0 = returnFunc(name, authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Series)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *int) error); ok {
		r1 = returnFunc(name, authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_CreateSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSeries'
type MockEntitiesStore_CreateSeries_Call struct {
	*mock.Call
}

// CreateSeries is a helper method to define mock.On call
//   - name string
//   - authorID *int
func (_e *MockEntitiesStore_Expecter) CreateSeries(name interface{}, authorID interface{}) *MockEntitiesStore_CreateSeries_Call {
	return &MockEntitiesStore_CreateSeries_Call{Call: _e.mock.On("CreateSeries", name, authorID)}
}

func (_c *MockEntitiesStore_CreateSeries_Call) Run(run func(name string, authorID *int)) *MockEntitiesStore_CreateSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *int
		if args[1] != nil {
			arg1 = args[1].(*int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_CreateSeries_Call) Return(series *database.Series, err error) *MockEntitiesStore_CreateSeries_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *MockEntitiesStore_CreateSeries_Call) RunAndReturn(run func(name string, authorID *int) (*database.Series, error)) *MockEntitiesStore_CreateSeries_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAuthor provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) DeleteAuthor(id int) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAuthor")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntitiesStore_DeleteAuthor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAuthor'
type MockEntitiesStore_DeleteAuthor_Call struct {
	*mock.Call
}

// DeleteAuthor is a helper method to define mock.On call
//   - id int
func (_e *MockEntitiesStore_Expecter) DeleteAuthor(id interface{}) *MockEntitiesStore_DeleteAuthor_Call {
	return &MockEntitiesStore_DeleteAuthor_Call{Call: _e.mock.On("DeleteAuthor", id)}
}

func (_c *MockEntitiesStore_DeleteAuthor_Call) Run(run func(id int)) *MockEntitiesStore_DeleteAuthor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_DeleteAuthor_Call) Return(err error) *MockEntitiesStore_DeleteAuthor_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntitiesStore_DeleteAuthor_Call) RunAndReturn(run func(id int) error) *MockEntitiesStore_DeleteAuthor_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAuthorAlias provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) DeleteAuthorAlias(id int) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAuthorAlias")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntitiesStore_DeleteAuthorAlias_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAuthorAlias'
type MockEntitiesStore_DeleteAuthorAlias_Call struct {
	*mock.Call
}

// DeleteAuthorAlias is a helper method to define mock.On call
//   - id int
func (_e *MockEntitiesStore_Expecter) DeleteAuthorAlias(id interface{}) *MockEntitiesStore_DeleteAuthorAlias_Call {
	return &MockEntitiesStore_DeleteAuthorAlias_Call{Call: _e.mock.On("DeleteAuthorAlias", id)}
}

func (_c *MockEntitiesStore_DeleteAuthorAlias_Call) Run(run func(id int)) *MockEntitiesStore_DeleteAuthorAlias_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_DeleteAuthorAlias_Call) Return(err error) *MockEntitiesStore_DeleteAuthorAlias_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntitiesStore_DeleteAuthorAlias_Call) RunAndReturn(run func(id int) error) *MockEntitiesStore_DeleteAuthorAlias_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteSeries provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) DeleteSeries(id int) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteSeries")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntitiesStore_DeleteSeries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteSeries'
type MockEntitiesStore_DeleteSeries_Call struct {
	*mock.Call
}

// DeleteSeries is a helper method to define mock.On call
//   - id int
func (_e *MockEntitiesStore_Expecter) DeleteSeries(id interface{}) *MockEntitiesStore_DeleteSeries_Call {
	return &MockEntitiesStore_DeleteSeries_Call{Call: _e.mock.On("DeleteSeries", id)}
}

func (_c *MockEntitiesStore_DeleteSeries_Call) Run(run func(id int)) *MockEntitiesStore_DeleteSeries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_DeleteSeries_Call) Return(err error) *MockEntitiesStore_DeleteSeries_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntitiesStore_DeleteSeries_Call) RunAndReturn(run func(id int) error) *MockEntitiesStore_DeleteSeries_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllWorkBookCounts provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetAllWorkBookCounts() (map[string]int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllWorkBookCounts")
	}

	var r0 map[string]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (map[string]int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() map[string]int); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetAllWorkBookCounts_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllWorkBookCounts'
type MockEntitiesStore_GetAllWorkBookCounts_Call struct {
	*mock.Call
}

// GetAllWorkBookCounts is a helper method to define mock.On call
func (_e *MockEntitiesStore_Expecter) GetAllWorkBookCounts() *MockEntitiesStore_GetAllWorkBookCounts_Call {
	return &MockEntitiesStore_GetAllWorkBookCounts_Call{Call: _e.mock.On("GetAllWorkBookCounts")}
}

func (_c *MockEntitiesStore_GetAllWorkBookCounts_Call) Run(run func()) *MockEntitiesStore_GetAllWorkBookCounts_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntitiesStore_GetAllWorkBookCounts_Call) Return(stringToInt map[string]int, err error) *MockEntitiesStore_GetAllWorkBookCounts_Call {
	_c.Call.Return(stringToInt, err)
	return _c
}

func (_c *MockEntitiesStore_GetAllWorkBookCounts_Call) RunAndReturn(run func() (map[string]int, error)) *MockEntitiesStore_GetAllWorkBookCounts_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllWorks provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetAllWorks() ([]database.Work, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllWorks")
	}

	var r0 []database.Work
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Work, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Work); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Work)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetAllWorks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllWorks'
type MockEntitiesStore_GetAllWorks_Call struct {
	*mock.Call
}

// GetAllWorks is a helper method to define mock.On call
func (_e *MockEntitiesStore_Expecter) GetAllWorks() *MockEntitiesStore_GetAllWorks_Call {
	return &MockEntitiesStore_GetAllWorks_Call{Call: _e.mock.On("GetAllWorks")}
}

func (_c *MockEntitiesStore_GetAllWorks_Call) Run(run func()) *MockEntitiesStore_GetAllWorks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntitiesStore_GetAllWorks_Call) Return(works []database.Work, err error) *MockEntitiesStore_GetAllWorks_Call {
	_c.Call.Return(works, err)
	return _c
}

func (_c *MockEntitiesStore_GetAllWorks_Call) RunAndReturn(run func() ([]database.Work, error)) *MockEntitiesStore_GetAllWorks_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorAliases provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetAuthorAliases(authorID int) ([]database.AuthorAlias, error) {
	ret := _mock.Called(authorID)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorAliases")
	}

	var r0 []database.AuthorAlias
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.AuthorAlias, error)); ok {
		return returnFunc(authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.AuthorAlias); ok {
		r0 = returnFunc(authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.AuthorAlias)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetAuthorAliases_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorAliases'
type MockEntitiesStore_GetAuthorAliases_Call struct {
	*mock.Call
}

// GetAuthorAliases is a helper method to define mock.On call
//   - authorID int
func (_e *MockEntitiesStore_Expecter) GetAuthorAliases(authorID interface{}) *MockEntitiesStore_GetAuthorAliases_Call {
	return &MockEntitiesStore_GetAuthorAliases_Call{Call: _e.mock.On("GetAuthorAliases", authorID)}
}

func (_c *MockEntitiesStore_GetAuthorAliases_Call) Run(run func(authorID int)) *MockEntitiesStore_GetAuthorAliases_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetAuthorAliases_Call) Return(authorAliass []database.AuthorAlias, err error) *MockEntitiesStore_GetAuthorAliases_Call {
	_c.Call.Return(authorAliass, err)
	return _c
}

func (_c *MockEntitiesStore_GetAuthorAliases_Call) RunAndReturn(run func(authorID int) ([]database.AuthorAlias, error)) *MockEntitiesStore_GetAuthorAliases_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorByID provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetAuthorByID(id int) (*database.Author, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByID")
	}

	var r0 *database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*database.Author, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *database.Author); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetAuthorByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorByID'
type MockEntitiesStore_GetAuthorByID_Call struct {
	*mock.Call
}

// GetAuthorByID is a helper method to define mock.On call
//   - id int
func (_e *MockEntitiesStore_Expecter) GetAuthorByID(id interface{}) *MockEntitiesStore_GetAuthorByID_Call {
	return &MockEntitiesStore_GetAuthorByID_Call{Call: _e.mock.On("GetAuthorByID", id)}
}

func (_c *MockEntitiesStore_GetAuthorByID_Call) Run(run func(id int)) *MockEntitiesStore_GetAuthorByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetAuthorByID_Call) Return(author *database.Author, err error) *MockEntitiesStore_GetAuthorByID_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockEntitiesStore_GetAuthorByID_Call) RunAndReturn(run func(id int) (*database.Author, error)) *MockEntitiesStore_GetAuthorByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorByName provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetAuthorByName(name string) (*database.Author, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByName")
	}

	var r0 *database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Author, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Author); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetAuthorByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorByName'
type MockEntitiesStore_GetAuthorByName_Call struct {
	*mock.Call
}

// GetAuthorByName is a helper method to define mock.On call
//   - name string
func (_e *MockEntitiesStore_Expecter) GetAuthorByName(name interface{}) *MockEntitiesStore_GetAuthorByName_Call {
	return &MockEntitiesStore_GetAuthorByName_Call{Call: _e.mock.On("GetAuthorByName", name)}
}

func (_c *MockEntitiesStore_GetAuthorByName_Call) Run(run func(name string)) *MockEntitiesStore_GetAuthorByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetAuthorByName_Call) Return(author *database.Author, err error) *MockEntitiesStore_GetAuthorByName_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockEntitiesStore_GetAuthorByName_Call) RunAndReturn(run func(name string) (*database.Author, error)) *MockEntitiesStore_GetAuthorByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookAuthors provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetBookAuthors(bookID string) ([]database.BookAuthor, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookAuthors")
	}

	var r0 []database.BookAuthor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.BookAuthor, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.BookAuthor); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookAuthor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetBookAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookAuthors'
type MockEntitiesStore_GetBookAuthors_Call struct {
	*mock.Call
}

// GetBookAuthors is a helper method to define mock.On call
//   - bookID string
func (_e *MockEntitiesStore_Expecter) GetBookAuthors(bookID interface{}) *MockEntitiesStore_GetBookAuthors_Call {
	return &MockEntitiesStore_GetBookAuthors_Call{Call: _e.mock.On("GetBookAuthors", bookID)}
}

func (_c *MockEntitiesStore_GetBookAuthors_Call) Run(run func(bookID string)) *MockEntitiesStore_GetBookAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetBookAuthors_Call) Return(bookAuthors []database.BookAuthor, err error) *MockEntitiesStore_GetBookAuthors_Call {
	_c.Call.Return(bookAuthors, err)
	return _c
}

func (_c *MockEntitiesStore_GetBookAuthors_Call) RunAndReturn(run func(bookID string) ([]database.BookAuthor, error)) *MockEntitiesStore_GetBookAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByID provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetBookByID(id string) (*database.Book, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockEntitiesStore_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - id string
func (_e *MockEntitiesStore_Expecter) GetBookByID(id interface{}) *MockEntitiesStore_GetBookByID_Call {
	return &MockEntitiesStore_GetBookByID_Call{Call: _e.mock.On("GetBookByID", id)}
}

func (_c *MockEntitiesStore_GetBookByID_Call) Run(run func(id string)) *MockEntitiesStore_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetBookByID_Call) Return(book *database.Book, err error) *MockEntitiesStore_GetBookByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockEntitiesStore_GetBookByID_Call) RunAndReturn(run func(id string) (*database.Book, error)) *MockEntitiesStore_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookNarrators provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetBookNarrators(bookID string) ([]database.BookNarrator, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookNarrators")
	}

	var r0 []database.BookNarrator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.BookNarrator, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.BookNarrator); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookNarrator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetBookNarrators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookNarrators'
type MockEntitiesStore_GetBookNarrators_Call struct {
	*mock.Call
}

// GetBookNarrators is a helper method to define mock.On call
//   - bookID string
func (_e *MockEntitiesStore_Expecter) GetBookNarrators(bookID interface{}) *MockEntitiesStore_GetBookNarrators_Call {
	return &MockEntitiesStore_GetBookNarrators_Call{Call: _e.mock.On("GetBookNarrators", bookID)}
}

func (_c *MockEntitiesStore_GetBookNarrators_Call) Run(run func(bookID string)) *MockEntitiesStore_GetBookNarrators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetBookNarrators_Call) Return(bookNarrators []database.BookNarrator, err error) *MockEntitiesStore_GetBookNarrators_Call {
	_c.Call.Return(bookNarrators, err)
	return _c
}

func (_c *MockEntitiesStore_GetBookNarrators_Call) RunAndReturn(run func(bookID string) ([]database.BookNarrator, error)) *MockEntitiesStore_GetBookNarrators_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByAuthorID provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetBooksByAuthorID(authorID int) ([]database.Book, error) {
	ret := _mock.Called(authorID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByAuthorID")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.Book, error)); ok {
		return returnFunc(authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.Book); ok {
		r0 = returnFunc(authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetBooksByAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByAuthorID'
type MockEntitiesStore_GetBooksByAuthorID_Call struct {
	*mock.Call
}

// GetBooksByAuthorID is a helper method to define mock.On call
//   - authorID int
func (_e *MockEntitiesStore_Expecter) GetBooksByAuthorID(authorID interface{}) *MockEntitiesStore_GetBooksByAuthorID_Call {
	return &MockEntitiesStore_GetBooksByAuthorID_Call{Call: _e.mock.On("GetBooksByAuthorID", authorID)}
}

func (_c *MockEntitiesStore_GetBooksByAuthorID_Call) Run(run func(authorID int)) *MockEntitiesStore_GetBooksByAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetBooksByAuthorID_Call) Return(books []database.Book, err error) *MockEntitiesStore_GetBooksByAuthorID_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockEntitiesStore_GetBooksByAuthorID_Call) RunAndReturn(run func(authorID int) ([]database.Book, error)) *MockEntitiesStore_GetBooksByAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByAuthorIDWithRole provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetBooksByAuthorIDWithRole(authorID int) ([]database.Book, error) {
	ret := _mock.Called(authorID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByAuthorIDWithRole")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.Book, error)); ok {
		return returnFunc(authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.Book); ok {
		r0 = returnFunc(authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetBooksByAuthorIDWithRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByAuthorIDWithRole'
type MockEntitiesStore_GetBooksByAuthorIDWithRole_Call struct {
	*mock.Call
}

// GetBooksByAuthorIDWithRole is a helper method to define mock.On call
//   - authorID int
func (_e *MockEntitiesStore_Expecter) GetBooksByAuthorIDWithRole(authorID interface{}) *MockEntitiesStore_GetBooksByAuthorIDWithRole_Call {
	return &MockEntitiesStore_GetBooksByAuthorIDWithRole_Call{Call: _e.mock.On("GetBooksByAuthorIDWithRole", authorID)}
}

func (_c *MockEntitiesStore_GetBooksByAuthorIDWithRole_Call) Run(run func(authorID int)) *MockEntitiesStore_GetBooksByAuthorIDWithRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetBooksByAuthorIDWithRole_Call) Return(books []database.Book, err error) *MockEntitiesStore_GetBooksByAuthorIDWithRole_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockEntitiesStore_GetBooksByAuthorIDWithRole_Call) RunAndReturn(run func(authorID int) ([]database.Book, error)) *MockEntitiesStore_GetBooksByAuthorIDWithRole_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksBySeriesID provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetBooksBySeriesID(seriesID int) ([]database.Book, error) {
	ret := _mock.Called(seriesID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksBySeriesID")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.Book, error)); ok {
		return returnFunc(seriesID)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.Book); ok {
		r0 = returnFunc(seriesID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(seriesID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetBooksBySeriesID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksBySeriesID'
type MockEntitiesStore_GetBooksBySeriesID_Call struct {
	*mock.Call
}

// GetBooksBySeriesID is a helper method to define mock.On call
//   - seriesID int
func (_e *MockEntitiesStore_Expecter) GetBooksBySeriesID(seriesID interface{}) *MockEntitiesStore_GetBooksBySeriesID_Call {
	return &MockEntitiesStore_GetBooksBySeriesID_Call{Call: _e.mock.On("GetBooksBySeriesID", seriesID)}
}

func (_c *MockEntitiesStore_GetBooksBySeriesID_Call) Run(run func(seriesID int)) *MockEntitiesStore_GetBooksBySeriesID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetBooksBySeriesID_Call) Return(books []database.Book, err error) *MockEntitiesStore_GetBooksBySeriesID_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockEntitiesStore_GetBooksBySeriesID_Call) RunAndReturn(run func(seriesID int) ([]database.Book, error)) *MockEntitiesStore_GetBooksBySeriesID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByWorkID provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetBooksByWorkID(workID string) ([]database.Book, error) {
	ret := _mock.Called(workID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByWorkID")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.Book, error)); ok {
		return returnFunc(workID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.Book); ok {
		r0 = returnFunc(workID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(workID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetBooksByWorkID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByWorkID'
type MockEntitiesStore_GetBooksByWorkID_Call struct {
	*mock.Call
}

// GetBooksByWorkID is a helper method to define mock.On call
//   - workID string
func (_e *MockEntitiesStore_Expecter) GetBooksByWorkID(workID interface{}) *MockEntitiesStore_GetBooksByWorkID_Call {
	return &MockEntitiesStore_GetBooksByWorkID_Call{Call: _e.mock.On("GetBooksByWorkID", workID)}
}

func (_c *MockEntitiesStore_GetBooksByWorkID_Call) Run(run func(workID string)) *MockEntitiesStore_GetBooksByWorkID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetBooksByWorkID_Call) Return(books []database.Book, err error) *MockEntitiesStore_GetBooksByWorkID_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockEntitiesStore_GetBooksByWorkID_Call) RunAndReturn(run func(workID string) ([]database.Book, error)) *MockEntitiesStore_GetBooksByWorkID_Call {
	_c.Call.Return(run)
	return _c
}

// GetNarratorByName provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetNarratorByName(name string) (*database.Narrator, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetNarratorByName")
	}

	var r0 *database.Narrator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Narrator, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Narrator); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Narrator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetNarratorByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetNarratorByName'
type MockEntitiesStore_GetNarratorByName_Call struct {
	*mock.Call
}

// GetNarratorByName is a helper method to define mock.On call
//   - name string
func (_e *MockEntitiesStore_Expecter) GetNarratorByName(name interface{}) *MockEntitiesStore_GetNarratorByName_Call {
	return &MockEntitiesStore_GetNarratorByName_Call{Call: _e.mock.On("GetNarratorByName", name)}
}

func (_c *MockEntitiesStore_GetNarratorByName_Call) Run(run func(name string)) *MockEntitiesStore_GetNarratorByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetNarratorByName_Call) Return(narrator *database.Narrator, err error) *MockEntitiesStore_GetNarratorByName_Call {
	_c.Call.Return(narrator, err)
	return _c
}

func (_c *MockEntitiesStore_GetNarratorByName_Call) RunAndReturn(run func(name string) (*database.Narrator, error)) *MockEntitiesStore_GetNarratorByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetSeriesByID provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) GetSeriesByID(id int) (*database.Series, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetSeriesByID")
	}

	var r0 *database.Series
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*database.Series, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *database.Series); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Series)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_GetSeriesByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSeriesByID'
type MockEntitiesStore_GetSeriesByID_Call struct {
	*mock.Call
}

// GetSeriesByID is a helper method to define mock.On call
//   - id int
func (_e *MockEntitiesStore_Expecter) GetSeriesByID(id interface{}) *MockEntitiesStore_GetSeriesByID_Call {
	return &MockEntitiesStore_GetSeriesByID_Call{Call: _e.mock.On("GetSeriesByID", id)}
}

func (_c *MockEntitiesStore_GetSeriesByID_Call) Run(run func(id int)) *MockEntitiesStore_GetSeriesByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_GetSeriesByID_Call) Return(series *database.Series, err error) *MockEntitiesStore_GetSeriesByID_Call {
	_c.Call.Return(series, err)
	return _c
}

func (_c *MockEntitiesStore_GetSeriesByID_Call) RunAndReturn(run func(id int) (*database.Series, error)) *MockEntitiesStore_GetSeriesByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListNarrators provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) ListNarrators() ([]database.Narrator, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListNarrators")
	}

	var r0 []database.Narrator
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Narrator, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Narrator); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Narrator)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_ListNarrators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListNarrators'
type MockEntitiesStore_ListNarrators_Call struct {
	*mock.Call
}

// ListNarrators is a helper method to define mock.On call
func (_e *MockEntitiesStore_Expecter) ListNarrators() *MockEntitiesStore_ListNarrators_Call {
	return &MockEntitiesStore_ListNarrators_Call{Call: _e.mock.On("ListNarrators")}
}

func (_c *MockEntitiesStore_ListNarrators_Call) Run(run func()) *MockEntitiesStore_ListNarrators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEntitiesStore_ListNarrators_Call) Return(narrators []database.Narrator, err error) *MockEntitiesStore_ListNarrators_Call {
	_c.Call.Return(narrators, err)
	return _c
}

func (_c *MockEntitiesStore_ListNarrators_Call) RunAndReturn(run func() ([]database.Narrator, error)) *MockEntitiesStore_ListNarrators_Call {
	_c.Call.Return(run)
	return _c
}

// SetBookAuthors provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) SetBookAuthors(bookID string, authors []database.BookAuthor) error {
	ret := _mock.Called(bookID, authors)

	if len(ret) == 0 {
		panic("no return value specified for SetBookAuthors")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []database.BookAuthor) error); ok {
		r0 = returnFunc(bookID, authors)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntitiesStore_SetBookAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBookAuthors'
type MockEntitiesStore_SetBookAuthors_Call struct {
	*mock.Call
}

// SetBookAuthors is a helper method to define mock.On call
//   - bookID string
//   - authors []database.BookAuthor
func (_e *MockEntitiesStore_Expecter) SetBookAuthors(bookID interface{}, authors interface{}) *MockEntitiesStore_SetBookAuthors_Call {
	return &MockEntitiesStore_SetBookAuthors_Call{Call: _e.mock.On("SetBookAuthors", bookID, authors)}
}

func (_c *MockEntitiesStore_SetBookAuthors_Call) Run(run func(bookID string, authors []database.BookAuthor)) *MockEntitiesStore_SetBookAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []database.BookAuthor
		if args[1] != nil {
			arg1 = args[1].([]database.BookAuthor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_SetBookAuthors_Call) Return(err error) *MockEntitiesStore_SetBookAuthors_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntitiesStore_SetBookAuthors_Call) RunAndReturn(run func(bookID string, authors []database.BookAuthor) error) *MockEntitiesStore_SetBookAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// SetBookNarrators provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) SetBookNarrators(bookID string, narrators []database.BookNarrator) error {
	ret := _mock.Called(bookID, narrators)

	if len(ret) == 0 {
		panic("no return value specified for SetBookNarrators")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []database.BookNarrator) error); ok {
		r0 = returnFunc(bookID, narrators)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntitiesStore_SetBookNarrators_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBookNarrators'
type MockEntitiesStore_SetBookNarrators_Call struct {
	*mock.Call
}

// SetBookNarrators is a helper method to define mock.On call
//   - bookID string
//   - narrators []database.BookNarrator
func (_e *MockEntitiesStore_Expecter) SetBookNarrators(bookID interface{}, narrators interface{}) *MockEntitiesStore_SetBookNarrators_Call {
	return &MockEntitiesStore_SetBookNarrators_Call{Call: _e.mock.On("SetBookNarrators", bookID, narrators)}
}

func (_c *MockEntitiesStore_SetBookNarrators_Call) Run(run func(bookID string, narrators []database.BookNarrator)) *MockEntitiesStore_SetBookNarrators_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []database.BookNarrator
		if args[1] != nil {
			arg1 = args[1].([]database.BookNarrator)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_SetBookNarrators_Call) Return(err error) *MockEntitiesStore_SetBookNarrators_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntitiesStore_SetBookNarrators_Call) RunAndReturn(run func(bookID string, narrators []database.BookNarrator) error) *MockEntitiesStore_SetBookNarrators_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateAuthorName provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) UpdateAuthorName(id int, name string) error {
	ret := _mock.Called(id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAuthorName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = returnFunc(id, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntitiesStore_UpdateAuthorName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAuthorName'
type MockEntitiesStore_UpdateAuthorName_Call struct {
	*mock.Call
}

// UpdateAuthorName is a helper method to define mock.On call
//   - id int
//   - name string
func (_e *MockEntitiesStore_Expecter) UpdateAuthorName(id interface{}, name interface{}) *MockEntitiesStore_UpdateAuthorName_Call {
	return &MockEntitiesStore_UpdateAuthorName_Call{Call: _e.mock.On("UpdateAuthorName", id, name)}
}

func (_c *MockEntitiesStore_UpdateAuthorName_Call) Run(run func(id int, name string)) *MockEntitiesStore_UpdateAuthorName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_UpdateAuthorName_Call) Return(err error) *MockEntitiesStore_UpdateAuthorName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntitiesStore_UpdateAuthorName_Call) RunAndReturn(run func(id int, name string) error) *MockEntitiesStore_UpdateAuthorName_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBook provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) UpdateBook(id string, book *database.Book) (*database.Book, error) {
	ret := _mock.Called(id, book)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) (*database.Book, error)); ok {
		return returnFunc(id, book)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) *database.Book); ok {
		r0 = returnFunc(id, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *database.Book) error); ok {
		r1 = returnFunc(id, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEntitiesStore_UpdateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBook'
type MockEntitiesStore_UpdateBook_Call struct {
	*mock.Call
}

// UpdateBook is a helper method to define mock.On call
//   - id string
//   - book *database.Book
func (_e *MockEntitiesStore_Expecter) UpdateBook(id interface{}, book interface{}) *MockEntitiesStore_UpdateBook_Call {
	return &MockEntitiesStore_UpdateBook_Call{Call: _e.mock.On("UpdateBook", id, book)}
}

func (_c *MockEntitiesStore_UpdateBook_Call) Run(run func(id string, book *database.Book)) *MockEntitiesStore_UpdateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *database.Book
		if args[1] != nil {
			arg1 = args[1].(*database.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_UpdateBook_Call) Return(book1 *database.Book, err error) *MockEntitiesStore_UpdateBook_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockEntitiesStore_UpdateBook_Call) RunAndReturn(run func(id string, book *database.Book) (*database.Book, error)) *MockEntitiesStore_UpdateBook_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateSeriesName provides a mock function for the type MockEntitiesStore
func (_mock *MockEntitiesStore) UpdateSeriesName(id int, name string) error {
	ret := _mock.Called(id, name)

	if len(ret) == 0 {
		panic("no return value specified for UpdateSeriesName")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, string) error); ok {
		r0 = returnFunc(id, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEntitiesStore_UpdateSeriesName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateSeriesName'
type MockEntitiesStore_UpdateSeriesName_Call struct {
	*mock.Call
}

// UpdateSeriesName is a helper method to define mock.On call
//   - id int
//   - name string
func (_e *MockEntitiesStore_Expecter) UpdateSeriesName(id interface{}, name interface{}) *MockEntitiesStore_UpdateSeriesName_Call {
	return &MockEntitiesStore_UpdateSeriesName_Call{Call: _e.mock.On("UpdateSeriesName", id, name)}
}

func (_c *MockEntitiesStore_UpdateSeriesName_Call) Run(run func(id int, name string)) *MockEntitiesStore_UpdateSeriesName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEntitiesStore_UpdateSeriesName_Call) Return(err error) *MockEntitiesStore_UpdateSeriesName_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEntitiesStore_UpdateSeriesName_Call) RunAndReturn(run func(id int, name string) error) *MockEntitiesStore_UpdateSeriesName_Call {
	_c.Call.Return(run)
	return _c
}
