// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockProgressReporter creates a new instance of MockProgressReporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProgressReporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProgressReporter {
	mock := &MockProgressReporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProgressReporter is an autogenerated mock type for the ProgressReporter type
type MockProgressReporter struct {
	mock.Mock
}

type MockProgressReporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProgressReporter) EXPECT() *MockProgressReporter_Expecter {
	return &MockProgressReporter_Expecter{mock: &_m.Mock}
}

// IsCanceled provides a mock function for the type MockProgressReporter
func (_mock *MockProgressReporter) IsCanceled() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsCanceled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProgressReporter_IsCanceled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsCanceled'
type MockProgressReporter_IsCanceled_Call struct {
	*mock.Call
}

// IsCanceled is a helper method to define mock.On call
func (_e *MockProgressReporter_Expecter) IsCanceled() *MockProgressReporter_IsCanceled_Call {
	return &MockProgressReporter_IsCanceled_Call{Call: _e.mock.On("IsCanceled")}
}

func (_c *MockProgressReporter_IsCanceled_Call) Run(run func()) *MockProgressReporter_IsCanceled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProgressReporter_IsCanceled_Call) Return(b bool) *MockProgressReporter_IsCanceled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProgressReporter_IsCanceled_Call) RunAndReturn(run func() bool) *MockProgressReporter_IsCanceled_Call {
	_c.Call.Return(run)
	return _c
}

// Log provides a mock function for the type MockProgressReporter
func (_mock *MockProgressReporter) Log(level string, message string, details *string) error {
	ret := _mock.Called(level, message, details)

	if len(ret) == 0 {
		panic("no return value specified for Log")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) error); ok {
		r0 = returnFunc(level, message, details)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProgressReporter_Log_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Log'
type MockProgressReporter_Log_Call struct {
	*mock.Call
}

// Log is a helper method to define mock.On call
//   - level string
//   - message string
//   - details *string
func (_e *MockProgressReporter_Expecter) Log(level interface{}, message interface{}, details interface{}) *MockProgressReporter_Log_Call {
	return &MockProgressReporter_Log_Call{Call: _e.mock.On("Log", level, message, details)}
}

func (_c *MockProgressReporter_Log_Call) Run(run func(level string, message string, details *string)) *MockProgressReporter_Log_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProgressReporter_Log_Call) Return(err error) *MockProgressReporter_Log_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProgressReporter_Log_Call) RunAndReturn(run func(level string, message string, details *string) error) *MockProgressReporter_Log_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateProgress provides a mock function for the type MockProgressReporter
func (_mock *MockProgressReporter) UpdateProgress(current int, total int, message string) error {
	ret := _mock.Called(current, total, message)

	if len(ret) == 0 {
		panic("no return value specified for UpdateProgress")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, int, string) error); ok {
		r0 = returnFunc(current, total, message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockProgressReporter_UpdateProgress_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateProgress'
type MockProgressReporter_UpdateProgress_Call struct {
	*mock.Call
}

// UpdateProgress is a helper method to define mock.On call
//   - current int
//   - total int
//   - message string
func (_e *MockProgressReporter_Expecter) UpdateProgress(current interface{}, total interface{}, message interface{}) *MockProgressReporter_UpdateProgress_Call {
	return &MockProgressReporter_UpdateProgress_Call{Call: _e.mock.On("UpdateProgress", current, total, message)}
}

func (_c *MockProgressReporter_UpdateProgress_Call) Run(run func(current int, total int, message string)) *MockProgressReporter_UpdateProgress_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockProgressReporter_UpdateProgress_Call) Return(err error) *MockProgressReporter_UpdateProgress_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockProgressReporter_UpdateProgress_Call) RunAndReturn(run func(current int, total int, message string) error) *MockProgressReporter_UpdateProgress_Call {
	_c.Call.Return(run)
	return _c
}
