// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockITunesStore creates a new instance of MockITunesStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITunesStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITunesStore {
	mock := &MockITunesStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITunesStore is an autogenerated mock type for the ITunesStore type
type MockITunesStore struct {
	mock.Mock
}

type MockITunesStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITunesStore) EXPECT() *MockITunesStore_Expecter {
	return &MockITunesStore_Expecter{mock: &_m.Mock}
}

// CreateOperation provides a mock function for the type MockITunesStore
func (_mock *MockITunesStore) CreateOperation(id string, opType string, folderPath *string) (*database.Operation, error) {
	ret := _mock.Called(id, opType, folderPath)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperation")
	}

	var r0 *database.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) (*database.Operation, error)); ok {
		return returnFunc(id, opType, folderPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) *database.Operation); ok {
		r0 = returnFunc(id, opType, folderPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *string) error); ok {
		r1 = returnFunc(id, opType, folderPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITunesStore_CreateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOperation'
type MockITunesStore_CreateOperation_Call struct {
	*mock.Call
}

// CreateOperation is a helper method to define mock.On call
//   - id string
//   - opType string
//   - folderPath *string
func (_e *MockITunesStore_Expecter) CreateOperation(id interface{}, opType interface{}, folderPath interface{}) *MockITunesStore_CreateOperation_Call {
	return &MockITunesStore_CreateOperation_Call{Call: _e.mock.On("CreateOperation", id, opType, folderPath)}
}

func (_c *MockITunesStore_CreateOperation_Call) Run(run func(id string, opType string, folderPath *string)) *MockITunesStore_CreateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITunesStore_CreateOperation_Call) Return(operation *database.Operation, err error) *MockITunesStore_CreateOperation_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockITunesStore_CreateOperation_Call) RunAndReturn(run func(id string, opType string, folderPath *string) (*database.Operation, error)) *MockITunesStore_CreateOperation_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorByID provides a mock function for the type MockITunesStore
func (_mock *MockITunesStore) GetAuthorByID(id int) (*database.Author, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorByID")
	}

	var r0 *database.Author
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*database.Author, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *database.Author); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Author)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITunesStore_GetAuthorByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorByID'
type MockITunesStore_GetAuthorByID_Call struct {
	*mock.Call
}

// GetAuthorByID is a helper method to define mock.On call
//   - id int
func (_e *MockITunesStore_Expecter) GetAuthorByID(id interface{}) *MockITunesStore_GetAuthorByID_Call {
	return &MockITunesStore_GetAuthorByID_Call{Call: _e.mock.On("GetAuthorByID", id)}
}

func (_c *MockITunesStore_GetAuthorByID_Call) Run(run func(id int)) *MockITunesStore_GetAuthorByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockITunesStore_GetAuthorByID_Call) Return(author *database.Author, err error) *MockITunesStore_GetAuthorByID_Call {
	_c.Call.Return(author, err)
	return _c
}

func (_c *MockITunesStore_GetAuthorByID_Call) RunAndReturn(run func(id int) (*database.Author, error)) *MockITunesStore_GetAuthorByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByID provides a mock function for the type MockITunesStore
func (_mock *MockITunesStore) GetBookByID(id string) (*database.Book, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITunesStore_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockITunesStore_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - id string
func (_e *MockITunesStore_Expecter) GetBookByID(id interface{}) *MockITunesStore_GetBookByID_Call {
	return &MockITunesStore_GetBookByID_Call{Call: _e.mock.On("GetBookByID", id)}
}

func (_c *MockITunesStore_GetBookByID_Call) Run(run func(id string)) *MockITunesStore_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockITunesStore_GetBookByID_Call) Return(book *database.Book, err error) *MockITunesStore_GetBookByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockITunesStore_GetBookByID_Call) RunAndReturn(run func(id string) (*database.Book, error)) *MockITunesStore_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetLibraryFingerprint provides a mock function for the type MockITunesStore
func (_mock *MockITunesStore) GetLibraryFingerprint(path string) (*database.LibraryFingerprintRecord, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetLibraryFingerprint")
	}

	var r0 *database.LibraryFingerprintRecord
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.LibraryFingerprintRecord, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.LibraryFingerprintRecord); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.LibraryFingerprintRecord)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITunesStore_GetLibraryFingerprint_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetLibraryFingerprint'
type MockITunesStore_GetLibraryFingerprint_Call struct {
	*mock.Call
}

// GetLibraryFingerprint is a helper method to define mock.On call
//   - path string
func (_e *MockITunesStore_Expecter) GetLibraryFingerprint(path interface{}) *MockITunesStore_GetLibraryFingerprint_Call {
	return &MockITunesStore_GetLibraryFingerprint_Call{Call: _e.mock.On("GetLibraryFingerprint", path)}
}

func (_c *MockITunesStore_GetLibraryFingerprint_Call) Run(run func(path string)) *MockITunesStore_GetLibraryFingerprint_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockITunesStore_GetLibraryFingerprint_Call) Return(libraryFingerprintRecord *database.LibraryFingerprintRecord, err error) *MockITunesStore_GetLibraryFingerprint_Call {
	_c.Call.Return(libraryFingerprintRecord, err)
	return _c
}

func (_c *MockITunesStore_GetLibraryFingerprint_Call) RunAndReturn(run func(path string) (*database.LibraryFingerprintRecord, error)) *MockITunesStore_GetLibraryFingerprint_Call {
	_c.Call.Return(run)
	return _c
}

// GetOperationByID provides a mock function for the type MockITunesStore
func (_mock *MockITunesStore) GetOperationByID(id string) (*database.Operation, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetOperationByID")
	}

	var r0 *database.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Operation, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Operation); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITunesStore_GetOperationByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetOperationByID'
type MockITunesStore_GetOperationByID_Call struct {
	*mock.Call
}

// GetOperationByID is a helper method to define mock.On call
//   - id string
func (_e *MockITunesStore_Expecter) GetOperationByID(id interface{}) *MockITunesStore_GetOperationByID_Call {
	return &MockITunesStore_GetOperationByID_Call{Call: _e.mock.On("GetOperationByID", id)}
}

func (_c *MockITunesStore_GetOperationByID_Call) Run(run func(id string)) *MockITunesStore_GetOperationByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockITunesStore_GetOperationByID_Call) Return(operation *database.Operation, err error) *MockITunesStore_GetOperationByID_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockITunesStore_GetOperationByID_Call) RunAndReturn(run func(id string) (*database.Operation, error)) *MockITunesStore_GetOperationByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListBooksByITunesPID provides a mock function for the type MockITunesStore
func (_mock *MockITunesStore) ListBooksByITunesPID(limit int, offset int) ([]database.Book, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListBooksByITunesPID")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]database.Book, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []database.Book); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITunesStore_ListBooksByITunesPID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBooksByITunesPID'
type MockITunesStore_ListBooksByITunesPID_Call struct {
	*mock.Call
}

// ListBooksByITunesPID is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockITunesStore_Expecter) ListBooksByITunesPID(limit interface{}, offset interface{}) *MockITunesStore_ListBooksByITunesPID_Call {
	return &MockITunesStore_ListBooksByITunesPID_Call{Call: _e.mock.On("ListBooksByITunesPID", limit, offset)}
}

func (_c *MockITunesStore_ListBooksByITunesPID_Call) Run(run func(limit int, offset int)) *MockITunesStore_ListBooksByITunesPID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockITunesStore_ListBooksByITunesPID_Call) Return(books []database.Book, err error) *MockITunesStore_ListBooksByITunesPID_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockITunesStore_ListBooksByITunesPID_Call) RunAndReturn(run func(limit int, offset int) ([]database.Book, error)) *MockITunesStore_ListBooksByITunesPID_Call {
	_c.Call.Return(run)
	return _c
}

// MarkITunesSynced provides a mock function for the type MockITunesStore
func (_mock *MockITunesStore) MarkITunesSynced(bookIDs []string) (int64, error) {
	ret := _mock.Called(bookIDs)

	if len(ret) == 0 {
		panic("no return value specified for MarkITunesSynced")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) (int64, error)); ok {
		return returnFunc(bookIDs)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) int64); ok {
		r0 = returnFunc(bookIDs)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(bookIDs)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITunesStore_MarkITunesSynced_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkITunesSynced'
type MockITunesStore_MarkITunesSynced_Call struct {
	*mock.Call
}

// MarkITunesSynced is a helper method to define mock.On call
//   - bookIDs []string
func (_e *MockITunesStore_Expecter) MarkITunesSynced(bookIDs interface{}) *MockITunesStore_MarkITunesSynced_Call {
	return &MockITunesStore_MarkITunesSynced_Call{Call: _e.mock.On("MarkITunesSynced", bookIDs)}
}

func (_c *MockITunesStore_MarkITunesSynced_Call) Run(run func(bookIDs []string)) *MockITunesStore_MarkITunesSynced_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockITunesStore_MarkITunesSynced_Call) Return(n int64, err error) *MockITunesStore_MarkITunesSynced_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockITunesStore_MarkITunesSynced_Call) RunAndReturn(run func(bookIDs []string) (int64, error)) *MockITunesStore_MarkITunesSynced_Call {
	_c.Call.Return(run)
	return _c
}

// SearchBooks provides a mock function for the type MockITunesStore
func (_mock *MockITunesStore) SearchBooks(query string, limit int, offset int) ([]database.Book, error) {
	ret := _mock.Called(query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchBooks")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]database.Book, error)); ok {
		return returnFunc(query, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []database.Book); ok {
		r0 = returnFunc(query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = returnFunc(query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockITunesStore_SearchBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchBooks'
type MockITunesStore_SearchBooks_Call struct {
	*mock.Call
}

// SearchBooks is a helper method to define mock.On call
//   - query string
//   - limit int
//   - offset int
func (_e *MockITunesStore_Expecter) SearchBooks(query interface{}, limit interface{}, offset interface{}) *MockITunesStore_SearchBooks_Call {
	return &MockITunesStore_SearchBooks_Call{Call: _e.mock.On("SearchBooks", query, limit, offset)}
}

func (_c *MockITunesStore_SearchBooks_Call) Run(run func(query string, limit int, offset int)) *MockITunesStore_SearchBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockITunesStore_SearchBooks_Call) Return(books []database.Book, err error) *MockITunesStore_SearchBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockITunesStore_SearchBooks_Call) RunAndReturn(run func(query string, limit int, offset int) ([]database.Book, error)) *MockITunesStore_SearchBooks_Call {
	_c.Call.Return(run)
	return _c
}
