// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVersionsStore creates a new instance of MockVersionsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVersionsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVersionsStore {
	mock := &MockVersionsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVersionsStore is an autogenerated mock type for the VersionsStore type
type MockVersionsStore struct {
	mock.Mock
}

type MockVersionsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVersionsStore) EXPECT() *MockVersionsStore_Expecter {
	return &MockVersionsStore_Expecter{mock: &_m.Mock}
}

// CreateBook provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) CreateBook(book *database.Book) (*database.Book, error) {
	ret := _mock.Called(book)

	if len(ret) == 0 {
		panic("no return value specified for CreateBook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*database.Book) (*database.Book, error)); ok {
		return returnFunc(book)
	}
	if returnFunc, ok := ret.Get(0).(func(*database.Book) *database.Book); ok {
		r0 = returnFunc(book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*database.Book) error); ok {
		r1 = returnFunc(book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionsStore_CreateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateBook'
type MockVersionsStore_CreateBook_Call struct {
	*mock.Call
}

// CreateBook is a helper method to define mock.On call
//   - book *database.Book
func (_e *MockVersionsStore_Expecter) CreateBook(book interface{}) *MockVersionsStore_CreateBook_Call {
	return &MockVersionsStore_CreateBook_Call{Call: _e.mock.On("CreateBook", book)}
}

func (_c *MockVersionsStore_CreateBook_Call) Run(run func(book *database.Book)) *MockVersionsStore_CreateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.Book
		if args[0] != nil {
			arg0 = args[0].(*database.Book)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionsStore_CreateBook_Call) Return(book1 *database.Book, err error) *MockVersionsStore_CreateBook_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockVersionsStore_CreateBook_Call) RunAndReturn(run func(book *database.Book) (*database.Book, error)) *MockVersionsStore_CreateBook_Call {
	_c.Call.Return(run)
	return _c
}

// CreateExternalIDMapping provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) CreateExternalIDMapping(mapping *database.ExternalIDMapping) error {
	ret := _mock.Called(mapping)

	if len(ret) == 0 {
		panic("no return value specified for CreateExternalIDMapping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*database.ExternalIDMapping) error); ok {
		r0 = returnFunc(mapping)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVersionsStore_CreateExternalIDMapping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExternalIDMapping'
type MockVersionsStore_CreateExternalIDMapping_Call struct {
	*mock.Call
}

// CreateExternalIDMapping is a helper method to define mock.On call
//   - mapping *database.ExternalIDMapping
func (_e *MockVersionsStore_Expecter) CreateExternalIDMapping(mapping interface{}) *MockVersionsStore_CreateExternalIDMapping_Call {
	return &MockVersionsStore_CreateExternalIDMapping_Call{Call: _e.mock.On("CreateExternalIDMapping", mapping)}
}

func (_c *MockVersionsStore_CreateExternalIDMapping_Call) Run(run func(mapping *database.ExternalIDMapping)) *MockVersionsStore_CreateExternalIDMapping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.ExternalIDMapping
		if args[0] != nil {
			arg0 = args[0].(*database.ExternalIDMapping)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionsStore_CreateExternalIDMapping_Call) Return(err error) *MockVersionsStore_CreateExternalIDMapping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVersionsStore_CreateExternalIDMapping_Call) RunAndReturn(run func(mapping *database.ExternalIDMapping) error) *MockVersionsStore_CreateExternalIDMapping_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteRaw provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) DeleteRaw(key string) error {
	ret := _mock.Called(key)

	if len(ret) == 0 {
		panic("no return value specified for DeleteRaw")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(key)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVersionsStore_DeleteRaw_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteRaw'
type MockVersionsStore_DeleteRaw_Call struct {
	*mock.Call
}

// DeleteRaw is a helper method to define mock.On call
//   - key string
func (_e *MockVersionsStore_Expecter) DeleteRaw(key interface{}) *MockVersionsStore_DeleteRaw_Call {
	return &MockVersionsStore_DeleteRaw_Call{Call: _e.mock.On("DeleteRaw", key)}
}

func (_c *MockVersionsStore_DeleteRaw_Call) Run(run func(key string)) *MockVersionsStore_DeleteRaw_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionsStore_DeleteRaw_Call) Return(err error) *MockVersionsStore_DeleteRaw_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVersionsStore_DeleteRaw_Call) RunAndReturn(run func(key string) error) *MockVersionsStore_DeleteRaw_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookAuthors provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) GetBookAuthors(bookID string) ([]database.BookAuthor, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookAuthors")
	}

	var r0 []database.BookAuthor
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.BookAuthor, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.BookAuthor); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookAuthor)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionsStore_GetBookAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookAuthors'
type MockVersionsStore_GetBookAuthors_Call struct {
	*mock.Call
}

// GetBookAuthors is a helper method to define mock.On call
//   - bookID string
func (_e *MockVersionsStore_Expecter) GetBookAuthors(bookID interface{}) *MockVersionsStore_GetBookAuthors_Call {
	return &MockVersionsStore_GetBookAuthors_Call{Call: _e.mock.On("GetBookAuthors", bookID)}
}

func (_c *MockVersionsStore_GetBookAuthors_Call) Run(run func(bookID string)) *MockVersionsStore_GetBookAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionsStore_GetBookAuthors_Call) Return(bookAuthors []database.BookAuthor, err error) *MockVersionsStore_GetBookAuthors_Call {
	_c.Call.Return(bookAuthors, err)
	return _c
}

func (_c *MockVersionsStore_GetBookAuthors_Call) RunAndReturn(run func(bookID string) ([]database.BookAuthor, error)) *MockVersionsStore_GetBookAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByID provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) GetBookByID(id string) (*database.Book, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionsStore_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockVersionsStore_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - id string
func (_e *MockVersionsStore_Expecter) GetBookByID(id interface{}) *MockVersionsStore_GetBookByID_Call {
	return &MockVersionsStore_GetBookByID_Call{Call: _e.mock.On("GetBookByID", id)}
}

func (_c *MockVersionsStore_GetBookByID_Call) Run(run func(id string)) *MockVersionsStore_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionsStore_GetBookByID_Call) Return(book *database.Book, err error) *MockVersionsStore_GetBookByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockVersionsStore_GetBookByID_Call) RunAndReturn(run func(id string) (*database.Book, error)) *MockVersionsStore_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookFiles provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) GetBookFiles(bookID string) ([]database.BookFile, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookFiles")
	}

	var r0 []database.BookFile
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.BookFile, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.BookFile); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookFile)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionsStore_GetBookFiles_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookFiles'
type MockVersionsStore_GetBookFiles_Call struct {
	*mock.Call
}

// GetBookFiles is a helper method to define mock.On call
//   - bookID string
func (_e *MockVersionsStore_Expecter) GetBookFiles(bookID interface{}) *MockVersionsStore_GetBookFiles_Call {
	return &MockVersionsStore_GetBookFiles_Call{Call: _e.mock.On("GetBookFiles", bookID)}
}

func (_c *MockVersionsStore_GetBookFiles_Call) Run(run func(bookID string)) *MockVersionsStore_GetBookFiles_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionsStore_GetBookFiles_Call) Return(bookFiles []database.BookFile, err error) *MockVersionsStore_GetBookFiles_Call {
	_c.Call.Return(bookFiles, err)
	return _c
}

func (_c *MockVersionsStore_GetBookFiles_Call) RunAndReturn(run func(bookID string) ([]database.BookFile, error)) *MockVersionsStore_GetBookFiles_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByVersionGroup provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) GetBooksByVersionGroup(groupID string) ([]database.Book, error) {
	ret := _mock.Called(groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByVersionGroup")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.Book, error)); ok {
		return returnFunc(groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.Book); ok {
		r0 = returnFunc(groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionsStore_GetBooksByVersionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByVersionGroup'
type MockVersionsStore_GetBooksByVersionGroup_Call struct {
	*mock.Call
}

// GetBooksByVersionGroup is a helper method to define mock.On call
//   - groupID string
func (_e *MockVersionsStore_Expecter) GetBooksByVersionGroup(groupID interface{}) *MockVersionsStore_GetBooksByVersionGroup_Call {
	return &MockVersionsStore_GetBooksByVersionGroup_Call{Call: _e.mock.On("GetBooksByVersionGroup", groupID)}
}

func (_c *MockVersionsStore_GetBooksByVersionGroup_Call) Run(run func(groupID string)) *MockVersionsStore_GetBooksByVersionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionsStore_GetBooksByVersionGroup_Call) Return(books []database.Book, err error) *MockVersionsStore_GetBooksByVersionGroup_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockVersionsStore_GetBooksByVersionGroup_Call) RunAndReturn(run func(groupID string) ([]database.Book, error)) *MockVersionsStore_GetBooksByVersionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetExternalIDsForBook provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) GetExternalIDsForBook(bookID string) ([]database.ExternalIDMapping, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetExternalIDsForBook")
	}

	var r0 []database.ExternalIDMapping
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.ExternalIDMapping, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.ExternalIDMapping); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.ExternalIDMapping)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionsStore_GetExternalIDsForBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetExternalIDsForBook'
type MockVersionsStore_GetExternalIDsForBook_Call struct {
	*mock.Call
}

// GetExternalIDsForBook is a helper method to define mock.On call
//   - bookID string
func (_e *MockVersionsStore_Expecter) GetExternalIDsForBook(bookID interface{}) *MockVersionsStore_GetExternalIDsForBook_Call {
	return &MockVersionsStore_GetExternalIDsForBook_Call{Call: _e.mock.On("GetExternalIDsForBook", bookID)}
}

func (_c *MockVersionsStore_GetExternalIDsForBook_Call) Run(run func(bookID string)) *MockVersionsStore_GetExternalIDsForBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockVersionsStore_GetExternalIDsForBook_Call) Return(externalIDMappings []database.ExternalIDMapping, err error) *MockVersionsStore_GetExternalIDsForBook_Call {
	_c.Call.Return(externalIDMappings, err)
	return _c
}

func (_c *MockVersionsStore_GetExternalIDsForBook_Call) RunAndReturn(run func(bookID string) ([]database.ExternalIDMapping, error)) *MockVersionsStore_GetExternalIDsForBook_Call {
	_c.Call.Return(run)
	return _c
}

// MoveBookFilesToBook provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) MoveBookFilesToBook(fileIDs []string, sourceBookID string, targetBookID string) error {
	ret := _mock.Called(fileIDs, sourceBookID, targetBookID)

	if len(ret) == 0 {
		panic("no return value specified for MoveBookFilesToBook")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func([]string, string, string) error); ok {
		r0 = returnFunc(fileIDs, sourceBookID, targetBookID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVersionsStore_MoveBookFilesToBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MoveBookFilesToBook'
type MockVersionsStore_MoveBookFilesToBook_Call struct {
	*mock.Call
}

// MoveBookFilesToBook is a helper method to define mock.On call
//   - fileIDs []string
//   - sourceBookID string
//   - targetBookID string
func (_e *MockVersionsStore_Expecter) MoveBookFilesToBook(fileIDs interface{}, sourceBookID interface{}, targetBookID interface{}) *MockVersionsStore_MoveBookFilesToBook_Call {
	return &MockVersionsStore_MoveBookFilesToBook_Call{Call: _e.mock.On("MoveBookFilesToBook", fileIDs, sourceBookID, targetBookID)}
}

func (_c *MockVersionsStore_MoveBookFilesToBook_Call) Run(run func(fileIDs []string, sourceBookID string, targetBookID string)) *MockVersionsStore_MoveBookFilesToBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockVersionsStore_MoveBookFilesToBook_Call) Return(err error) *MockVersionsStore_MoveBookFilesToBook_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVersionsStore_MoveBookFilesToBook_Call) RunAndReturn(run func(fileIDs []string, sourceBookID string, targetBookID string) error) *MockVersionsStore_MoveBookFilesToBook_Call {
	_c.Call.Return(run)
	return _c
}

// SetBookAuthors provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) SetBookAuthors(bookID string, authors []database.BookAuthor) error {
	ret := _mock.Called(bookID, authors)

	if len(ret) == 0 {
		panic("no return value specified for SetBookAuthors")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []database.BookAuthor) error); ok {
		r0 = returnFunc(bookID, authors)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVersionsStore_SetBookAuthors_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetBookAuthors'
type MockVersionsStore_SetBookAuthors_Call struct {
	*mock.Call
}

// SetBookAuthors is a helper method to define mock.On call
//   - bookID string
//   - authors []database.BookAuthor
func (_e *MockVersionsStore_Expecter) SetBookAuthors(bookID interface{}, authors interface{}) *MockVersionsStore_SetBookAuthors_Call {
	return &MockVersionsStore_SetBookAuthors_Call{Call: _e.mock.On("SetBookAuthors", bookID, authors)}
}

func (_c *MockVersionsStore_SetBookAuthors_Call) Run(run func(bookID string, authors []database.BookAuthor)) *MockVersionsStore_SetBookAuthors_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 []database.BookAuthor
		if args[1] != nil {
			arg1 = args[1].([]database.BookAuthor)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVersionsStore_SetBookAuthors_Call) Return(err error) *MockVersionsStore_SetBookAuthors_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVersionsStore_SetBookAuthors_Call) RunAndReturn(run func(bookID string, authors []database.BookAuthor) error) *MockVersionsStore_SetBookAuthors_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBook provides a mock function for the type MockVersionsStore
func (_mock *MockVersionsStore) UpdateBook(id string, book *database.Book) (*database.Book, error) {
	ret := _mock.Called(id, book)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) (*database.Book, error)); ok {
		return returnFunc(id, book)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) *database.Book); ok {
		r0 = returnFunc(id, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *database.Book) error); ok {
		r1 = returnFunc(id, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVersionsStore_UpdateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBook'
type MockVersionsStore_UpdateBook_Call struct {
	*mock.Call
}

// UpdateBook is a helper method to define mock.On call
//   - id string
//   - book *database.Book
func (_e *MockVersionsStore_Expecter) UpdateBook(id interface{}, book interface{}) *MockVersionsStore_UpdateBook_Call {
	return &MockVersionsStore_UpdateBook_Call{Call: _e.mock.On("UpdateBook", id, book)}
}

func (_c *MockVersionsStore_UpdateBook_Call) Run(run func(id string, book *database.Book)) *MockVersionsStore_UpdateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *database.Book
		if args[1] != nil {
			arg1 = args[1].(*database.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockVersionsStore_UpdateBook_Call) Return(book1 *database.Book, err error) *MockVersionsStore_UpdateBook_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockVersionsStore_UpdateBook_Call) RunAndReturn(run func(id string, book *database.Book) (*database.Book, error)) *MockVersionsStore_UpdateBook_Call {
	_c.Call.Return(run)
	return _c
}
