// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/database"
	"github.com/falkcorp/audiobook-organizer/internal/logger"
	"github.com/falkcorp/audiobook-organizer/internal/organizer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOrganizeServicer creates a new instance of MockOrganizeServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOrganizeServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOrganizeServicer {
	mock := &MockOrganizeServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOrganizeServicer is an autogenerated mock type for the OrganizeServicer type
type MockOrganizeServicer struct {
	mock.Mock
}

type MockOrganizeServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOrganizeServicer) EXPECT() *MockOrganizeServicer_Expecter {
	return &MockOrganizeServicer_Expecter{mock: &_m.Mock}
}

// CreateOrganizedVersion provides a mock function for the type MockOrganizeServicer
func (_mock *MockOrganizeServicer) CreateOrganizedVersion(org *organizer.Organizer, book *database.Book, newPath string, isDir bool, operationID string, log logger.Logger) (*database.Book, error) {
	ret := _mock.Called(org, book, newPath, isDir, operationID, log)

	if len(ret) == 0 {
		panic("no return value specified for CreateOrganizedVersion")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*organizer.Organizer, *database.Book, string, bool, string, logger.Logger) (*database.Book, error)); ok {
		return returnFunc(org, book, newPath, isDir, operationID, log)
	}
	if returnFunc, ok := ret.Get(0).(func(*organizer.Organizer, *database.Book, string, bool, string, logger.Logger) *database.Book); ok {
		r0 = returnFunc(org, book, newPath, isDir, operationID, log)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*organizer.Organizer, *database.Book, string, bool, string, logger.Logger) error); ok {
		r1 = returnFunc(org, book, newPath, isDir, operationID, log)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizeServicer_CreateOrganizedVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOrganizedVersion'
type MockOrganizeServicer_CreateOrganizedVersion_Call struct {
	*mock.Call
}

// CreateOrganizedVersion is a helper method to define mock.On call
//   - org *organizer.Organizer
//   - book *database.Book
//   - newPath string
//   - isDir bool
//   - operationID string
//   - log logger.Logger
func (_e *MockOrganizeServicer_Expecter) CreateOrganizedVersion(org interface{}, book interface{}, newPath interface{}, isDir interface{}, operationID interface{}, log interface{}) *MockOrganizeServicer_CreateOrganizedVersion_Call {
	return &MockOrganizeServicer_CreateOrganizedVersion_Call{Call: _e.mock.On("CreateOrganizedVersion", org, book, newPath, isDir, operationID, log)}
}

func (_c *MockOrganizeServicer_CreateOrganizedVersion_Call) Run(run func(org *organizer.Organizer, book *database.Book, newPath string, isDir bool, operationID string, log logger.Logger)) *MockOrganizeServicer_CreateOrganizedVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *organizer.Organizer
		if args[0] != nil {
			arg0 = args[0].(*organizer.Organizer)
		}
		var arg1 *database.Book
		if args[1] != nil {
			arg1 = args[1].(*database.Book)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 logger.Logger
		if args[5] != nil {
			arg5 = args[5].(logger.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockOrganizeServicer_CreateOrganizedVersion_Call) Return(book1 *database.Book, err error) *MockOrganizeServicer_CreateOrganizedVersion_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockOrganizeServicer_CreateOrganizedVersion_Call) RunAndReturn(run func(org *organizer.Organizer, book *database.Book, newPath string, isDir bool, operationID string, log logger.Logger) (*database.Book, error)) *MockOrganizeServicer_CreateOrganizedVersion_Call {
	_c.Call.Return(run)
	return _c
}

// OrganizeDirectoryBook provides a mock function for the type MockOrganizeServicer
func (_mock *MockOrganizeServicer) OrganizeDirectoryBook(org *organizer.Organizer, book *database.Book, log logger.Logger) (string, error) {
	ret := _mock.Called(org, book, log)

	if len(ret) == 0 {
		panic("no return value specified for OrganizeDirectoryBook")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*organizer.Organizer, *database.Book, logger.Logger) (string, error)); ok {
		return returnFunc(org, book, log)
	}
	if returnFunc, ok := ret.Get(0).(func(*organizer.Organizer, *database.Book, logger.Logger) string); ok {
		r0 = returnFunc(org, book, log)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*organizer.Organizer, *database.Book, logger.Logger) error); ok {
		r1 = returnFunc(org, book, log)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizeServicer_OrganizeDirectoryBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'OrganizeDirectoryBook'
type MockOrganizeServicer_OrganizeDirectoryBook_Call struct {
	*mock.Call
}

// OrganizeDirectoryBook is a helper method to define mock.On call
//   - org *organizer.Organizer
//   - book *database.Book
//   - log logger.Logger
func (_e *MockOrganizeServicer_Expecter) OrganizeDirectoryBook(org interface{}, book interface{}, log interface{}) *MockOrganizeServicer_OrganizeDirectoryBook_Call {
	return &MockOrganizeServicer_OrganizeDirectoryBook_Call{Call: _e.mock.On("OrganizeDirectoryBook", org, book, log)}
}

func (_c *MockOrganizeServicer_OrganizeDirectoryBook_Call) Run(run func(org *organizer.Organizer, book *database.Book, log logger.Logger)) *MockOrganizeServicer_OrganizeDirectoryBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *organizer.Organizer
		if args[0] != nil {
			arg0 = args[0].(*organizer.Organizer)
		}
		var arg1 *database.Book
		if args[1] != nil {
			arg1 = args[1].(*database.Book)
		}
		var arg2 logger.Logger
		if args[2] != nil {
			arg2 = args[2].(logger.Logger)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockOrganizeServicer_OrganizeDirectoryBook_Call) Return(s string, err error) *MockOrganizeServicer_OrganizeDirectoryBook_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOrganizeServicer_OrganizeDirectoryBook_Call) RunAndReturn(run func(org *organizer.Organizer, book *database.Book, log logger.Logger) (string, error)) *MockOrganizeServicer_OrganizeDirectoryBook_Call {
	_c.Call.Return(run)
	return _c
}

// ReOrganizeInPlace provides a mock function for the type MockOrganizeServicer
func (_mock *MockOrganizeServicer) ReOrganizeInPlace(book *database.Book, log logger.Logger) (string, error) {
	ret := _mock.Called(book, log)

	if len(ret) == 0 {
		panic("no return value specified for ReOrganizeInPlace")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*database.Book, logger.Logger) (string, error)); ok {
		return returnFunc(book, log)
	}
	if returnFunc, ok := ret.Get(0).(func(*database.Book, logger.Logger) string); ok {
		r0 = returnFunc(book, log)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(*database.Book, logger.Logger) error); ok {
		r1 = returnFunc(book, log)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOrganizeServicer_ReOrganizeInPlace_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReOrganizeInPlace'
type MockOrganizeServicer_ReOrganizeInPlace_Call struct {
	*mock.Call
}

// ReOrganizeInPlace is a helper method to define mock.On call
//   - book *database.Book
//   - log logger.Logger
func (_e *MockOrganizeServicer_Expecter) ReOrganizeInPlace(book interface{}, log interface{}) *MockOrganizeServicer_ReOrganizeInPlace_Call {
	return &MockOrganizeServicer_ReOrganizeInPlace_Call{Call: _e.mock.On("ReOrganizeInPlace", book, log)}
}

func (_c *MockOrganizeServicer_ReOrganizeInPlace_Call) Run(run func(book *database.Book, log logger.Logger)) *MockOrganizeServicer_ReOrganizeInPlace_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.Book
		if args[0] != nil {
			arg0 = args[0].(*database.Book)
		}
		var arg1 logger.Logger
		if args[1] != nil {
			arg1 = args[1].(logger.Logger)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOrganizeServicer_ReOrganizeInPlace_Call) Return(s string, err error) *MockOrganizeServicer_ReOrganizeInPlace_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockOrganizeServicer_ReOrganizeInPlace_Call) RunAndReturn(run func(book *database.Book, log logger.Logger) (string, error)) *MockOrganizeServicer_ReOrganizeInPlace_Call {
	_c.Call.Return(run)
	return _c
}
