// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFilesystemStore creates a new instance of MockFilesystemStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFilesystemStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFilesystemStore {
	mock := &MockFilesystemStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFilesystemStore is an autogenerated mock type for the FilesystemStore type
type MockFilesystemStore struct {
	mock.Mock
}

type MockFilesystemStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFilesystemStore) EXPECT() *MockFilesystemStore_Expecter {
	return &MockFilesystemStore_Expecter{mock: &_m.Mock}
}

// CountBooksByPathPrefix provides a mock function for the type MockFilesystemStore
func (_mock *MockFilesystemStore) CountBooksByPathPrefix(prefix string) (int, error) {
	ret := _mock.Called(prefix)

	if len(ret) == 0 {
		panic("no return value specified for CountBooksByPathPrefix")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (int, error)); ok {
		return returnFunc(prefix)
	}
	if returnFunc, ok := ret.Get(0).(func(string) int); ok {
		r0 = returnFunc(prefix)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(prefix)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilesystemStore_CountBooksByPathPrefix_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBooksByPathPrefix'
type MockFilesystemStore_CountBooksByPathPrefix_Call struct {
	*mock.Call
}

// CountBooksByPathPrefix is a helper method to define mock.On call
//   - prefix string
func (_e *MockFilesystemStore_Expecter) CountBooksByPathPrefix(prefix interface{}) *MockFilesystemStore_CountBooksByPathPrefix_Call {
	return &MockFilesystemStore_CountBooksByPathPrefix_Call{Call: _e.mock.On("CountBooksByPathPrefix", prefix)}
}

func (_c *MockFilesystemStore_CountBooksByPathPrefix_Call) Run(run func(prefix string)) *MockFilesystemStore_CountBooksByPathPrefix_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFilesystemStore_CountBooksByPathPrefix_Call) Return(n int, err error) *MockFilesystemStore_CountBooksByPathPrefix_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockFilesystemStore_CountBooksByPathPrefix_Call) RunAndReturn(run func(prefix string) (int, error)) *MockFilesystemStore_CountBooksByPathPrefix_Call {
	_c.Call.Return(run)
	return _c
}

// CreateOperation provides a mock function for the type MockFilesystemStore
func (_mock *MockFilesystemStore) CreateOperation(id string, opType string, folderPath *string) (*database.Operation, error) {
	ret := _mock.Called(id, opType, folderPath)

	if len(ret) == 0 {
		panic("no return value specified for CreateOperation")
	}

	var r0 *database.Operation
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) (*database.Operation, error)); ok {
		return returnFunc(id, opType, folderPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, *string) *database.Operation); ok {
		r0 = returnFunc(id, opType, folderPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Operation)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, *string) error); ok {
		r1 = returnFunc(id, opType, folderPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilesystemStore_CreateOperation_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateOperation'
type MockFilesystemStore_CreateOperation_Call struct {
	*mock.Call
}

// CreateOperation is a helper method to define mock.On call
//   - id string
//   - opType string
//   - folderPath *string
func (_e *MockFilesystemStore_Expecter) CreateOperation(id interface{}, opType interface{}, folderPath interface{}) *MockFilesystemStore_CreateOperation_Call {
	return &MockFilesystemStore_CreateOperation_Call{Call: _e.mock.On("CreateOperation", id, opType, folderPath)}
}

func (_c *MockFilesystemStore_CreateOperation_Call) Run(run func(id string, opType string, folderPath *string)) *MockFilesystemStore_CreateOperation_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *string
		if args[2] != nil {
			arg2 = args[2].(*string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockFilesystemStore_CreateOperation_Call) Return(operation *database.Operation, err error) *MockFilesystemStore_CreateOperation_Call {
	_c.Call.Return(operation, err)
	return _c
}

func (_c *MockFilesystemStore_CreateOperation_Call) RunAndReturn(run func(id string, opType string, folderPath *string) (*database.Operation, error)) *MockFilesystemStore_CreateOperation_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteImportPath provides a mock function for the type MockFilesystemStore
func (_mock *MockFilesystemStore) DeleteImportPath(id int) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteImportPath")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFilesystemStore_DeleteImportPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteImportPath'
type MockFilesystemStore_DeleteImportPath_Call struct {
	*mock.Call
}

// DeleteImportPath is a helper method to define mock.On call
//   - id int
func (_e *MockFilesystemStore_Expecter) DeleteImportPath(id interface{}) *MockFilesystemStore_DeleteImportPath_Call {
	return &MockFilesystemStore_DeleteImportPath_Call{Call: _e.mock.On("DeleteImportPath", id)}
}

func (_c *MockFilesystemStore_DeleteImportPath_Call) Run(run func(id int)) *MockFilesystemStore_DeleteImportPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFilesystemStore_DeleteImportPath_Call) Return(err error) *MockFilesystemStore_DeleteImportPath_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFilesystemStore_DeleteImportPath_Call) RunAndReturn(run func(id int) error) *MockFilesystemStore_DeleteImportPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllImportPaths provides a mock function for the type MockFilesystemStore
func (_mock *MockFilesystemStore) GetAllImportPaths() ([]database.ImportPath, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetAllImportPaths")
	}

	var r0 []database.ImportPath
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.ImportPath, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.ImportPath); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.ImportPath)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilesystemStore_GetAllImportPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllImportPaths'
type MockFilesystemStore_GetAllImportPaths_Call struct {
	*mock.Call
}

// GetAllImportPaths is a helper method to define mock.On call
func (_e *MockFilesystemStore_Expecter) GetAllImportPaths() *MockFilesystemStore_GetAllImportPaths_Call {
	return &MockFilesystemStore_GetAllImportPaths_Call{Call: _e.mock.On("GetAllImportPaths")}
}

func (_c *MockFilesystemStore_GetAllImportPaths_Call) Run(run func()) *MockFilesystemStore_GetAllImportPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFilesystemStore_GetAllImportPaths_Call) Return(importPaths []database.ImportPath, err error) *MockFilesystemStore_GetAllImportPaths_Call {
	_c.Call.Return(importPaths, err)
	return _c
}

func (_c *MockFilesystemStore_GetAllImportPaths_Call) RunAndReturn(run func() ([]database.ImportPath, error)) *MockFilesystemStore_GetAllImportPaths_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByFilePath provides a mock function for the type MockFilesystemStore
func (_mock *MockFilesystemStore) GetBookByFilePath(path string) (*database.Book, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByFilePath")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilesystemStore_GetBookByFilePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByFilePath'
type MockFilesystemStore_GetBookByFilePath_Call struct {
	*mock.Call
}

// GetBookByFilePath is a helper method to define mock.On call
//   - path string
func (_e *MockFilesystemStore_Expecter) GetBookByFilePath(path interface{}) *MockFilesystemStore_GetBookByFilePath_Call {
	return &MockFilesystemStore_GetBookByFilePath_Call{Call: _e.mock.On("GetBookByFilePath", path)}
}

func (_c *MockFilesystemStore_GetBookByFilePath_Call) Run(run func(path string)) *MockFilesystemStore_GetBookByFilePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFilesystemStore_GetBookByFilePath_Call) Return(book *database.Book, err error) *MockFilesystemStore_GetBookByFilePath_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockFilesystemStore_GetBookByFilePath_Call) RunAndReturn(run func(path string) (*database.Book, error)) *MockFilesystemStore_GetBookByFilePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetDashboardStats provides a mock function for the type MockFilesystemStore
func (_mock *MockFilesystemStore) GetDashboardStats() (*database.DashboardStats, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDashboardStats")
	}

	var r0 *database.DashboardStats
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (*database.DashboardStats, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() *database.DashboardStats); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.DashboardStats)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilesystemStore_GetDashboardStats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDashboardStats'
type MockFilesystemStore_GetDashboardStats_Call struct {
	*mock.Call
}

// GetDashboardStats is a helper method to define mock.On call
func (_e *MockFilesystemStore_Expecter) GetDashboardStats() *MockFilesystemStore_GetDashboardStats_Call {
	return &MockFilesystemStore_GetDashboardStats_Call{Call: _e.mock.On("GetDashboardStats")}
}

func (_c *MockFilesystemStore_GetDashboardStats_Call) Run(run func()) *MockFilesystemStore_GetDashboardStats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockFilesystemStore_GetDashboardStats_Call) Return(v *database.DashboardStats, err error) *MockFilesystemStore_GetDashboardStats_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockFilesystemStore_GetDashboardStats_Call) RunAndReturn(run func() (*database.DashboardStats, error)) *MockFilesystemStore_GetDashboardStats_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateBook provides a mock function for the type MockFilesystemStore
func (_mock *MockFilesystemStore) UpdateBook(id string, book *database.Book) (*database.Book, error) {
	ret := _mock.Called(id, book)

	if len(ret) == 0 {
		panic("no return value specified for UpdateBook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) (*database.Book, error)); ok {
		return returnFunc(id, book)
	}
	if returnFunc, ok := ret.Get(0).(func(string, *database.Book) *database.Book); ok {
		r0 = returnFunc(id, book)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, *database.Book) error); ok {
		r1 = returnFunc(id, book)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFilesystemStore_UpdateBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateBook'
type MockFilesystemStore_UpdateBook_Call struct {
	*mock.Call
}

// UpdateBook is a helper method to define mock.On call
//   - id string
//   - book *database.Book
func (_e *MockFilesystemStore_Expecter) UpdateBook(id interface{}, book interface{}) *MockFilesystemStore_UpdateBook_Call {
	return &MockFilesystemStore_UpdateBook_Call{Call: _e.mock.On("UpdateBook", id, book)}
}

func (_c *MockFilesystemStore_UpdateBook_Call) Run(run func(id string, book *database.Book)) *MockFilesystemStore_UpdateBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 *database.Book
		if args[1] != nil {
			arg1 = args[1].(*database.Book)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilesystemStore_UpdateBook_Call) Return(book1 *database.Book, err error) *MockFilesystemStore_UpdateBook_Call {
	_c.Call.Return(book1, err)
	return _c
}

func (_c *MockFilesystemStore_UpdateBook_Call) RunAndReturn(run func(id string, book *database.Book) (*database.Book, error)) *MockFilesystemStore_UpdateBook_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImportPath provides a mock function for the type MockFilesystemStore
func (_mock *MockFilesystemStore) UpdateImportPath(id int, path *database.ImportPath) error {
	ret := _mock.Called(id, path)

	if len(ret) == 0 {
		panic("no return value specified for UpdateImportPath")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(int, *database.ImportPath) error); ok {
		r0 = returnFunc(id, path)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockFilesystemStore_UpdateImportPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImportPath'
type MockFilesystemStore_UpdateImportPath_Call struct {
	*mock.Call
}

// UpdateImportPath is a helper method to define mock.On call
//   - id int
//   - path *database.ImportPath
func (_e *MockFilesystemStore_Expecter) UpdateImportPath(id interface{}, path interface{}) *MockFilesystemStore_UpdateImportPath_Call {
	return &MockFilesystemStore_UpdateImportPath_Call{Call: _e.mock.On("UpdateImportPath", id, path)}
}

func (_c *MockFilesystemStore_UpdateImportPath_Call) Run(run func(id int, path *database.ImportPath)) *MockFilesystemStore_UpdateImportPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 *database.ImportPath
		if args[1] != nil {
			arg1 = args[1].(*database.ImportPath)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockFilesystemStore_UpdateImportPath_Call) Return(err error) *MockFilesystemStore_UpdateImportPath_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockFilesystemStore_UpdateImportPath_Call) RunAndReturn(run func(id int, path *database.ImportPath) error) *MockFilesystemStore_UpdateImportPath_Call {
	_c.Call.Return(run)
	return _c
}
