// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDiagnosticsService creates a new instance of MockDiagnosticsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDiagnosticsService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDiagnosticsService {
	mock := &MockDiagnosticsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDiagnosticsService is an autogenerated mock type for the DiagnosticsService type
type MockDiagnosticsService struct {
	mock.Mock
}

type MockDiagnosticsService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDiagnosticsService) EXPECT() *MockDiagnosticsService_Expecter {
	return &MockDiagnosticsService_Expecter{mock: &_m.Mock}
}

// CollectAllBooks provides a mock function for the type MockDiagnosticsService
func (_mock *MockDiagnosticsService) CollectAllBooks() ([]database.Book, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CollectAllBooks")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Book, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Book); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDiagnosticsService_CollectAllBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectAllBooks'
type MockDiagnosticsService_CollectAllBooks_Call struct {
	*mock.Call
}

// CollectAllBooks is a helper method to define mock.On call
func (_e *MockDiagnosticsService_Expecter) CollectAllBooks() *MockDiagnosticsService_CollectAllBooks_Call {
	return &MockDiagnosticsService_CollectAllBooks_Call{Call: _e.mock.On("CollectAllBooks")}
}

func (_c *MockDiagnosticsService_CollectAllBooks_Call) Run(run func()) *MockDiagnosticsService_CollectAllBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockDiagnosticsService_CollectAllBooks_Call) Return(books []database.Book, err error) *MockDiagnosticsService_CollectAllBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockDiagnosticsService_CollectAllBooks_Call) RunAndReturn(run func() ([]database.Book, error)) *MockDiagnosticsService_CollectAllBooks_Call {
	_c.Call.Return(run)
	return _c
}
