// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/importer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockFileImporter creates a new instance of MockFileImporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockFileImporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockFileImporter {
	mock := &MockFileImporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockFileImporter is an autogenerated mock type for the FileImporter type
type MockFileImporter struct {
	mock.Mock
}

type MockFileImporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockFileImporter) EXPECT() *MockFileImporter_Expecter {
	return &MockFileImporter_Expecter{mock: &_m.Mock}
}

// ImportFile provides a mock function for the type MockFileImporter
func (_mock *MockFileImporter) ImportFile(req *importer.ImportFileRequest) (*importer.ImportFileResponse, error) {
	ret := _mock.Called(req)

	if len(ret) == 0 {
		panic("no return value specified for ImportFile")
	}

	var r0 *importer.ImportFileResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*importer.ImportFileRequest) (*importer.ImportFileResponse, error)); ok {
		return returnFunc(req)
	}
	if returnFunc, ok := ret.Get(0).(func(*importer.ImportFileRequest) *importer.ImportFileResponse); ok {
		r0 = returnFunc(req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*importer.ImportFileResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*importer.ImportFileRequest) error); ok {
		r1 = returnFunc(req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockFileImporter_ImportFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ImportFile'
type MockFileImporter_ImportFile_Call struct {
	*mock.Call
}

// ImportFile is a helper method to define mock.On call
//   - req *importer.ImportFileRequest
func (_e *MockFileImporter_Expecter) ImportFile(req interface{}) *MockFileImporter_ImportFile_Call {
	return &MockFileImporter_ImportFile_Call{Call: _e.mock.On("ImportFile", req)}
}

func (_c *MockFileImporter_ImportFile_Call) Run(run func(req *importer.ImportFileRequest)) *MockFileImporter_ImportFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *importer.ImportFileRequest
		if args[0] != nil {
			arg0 = args[0].(*importer.ImportFileRequest)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockFileImporter_ImportFile_Call) Return(importFileResponse *importer.ImportFileResponse, err error) *MockFileImporter_ImportFile_Call {
	_c.Call.Return(importFileResponse, err)
	return _c
}

func (_c *MockFileImporter_ImportFile_Call) RunAndReturn(run func(req *importer.ImportFileRequest) (*importer.ImportFileResponse, error)) *MockFileImporter_ImportFile_Call {
	_c.Call.Return(run)
	return _c
}
