// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"time"

	"github.com/jdfalk/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPlaylistStore creates a new instance of MockPlaylistStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPlaylistStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPlaylistStore {
	mock := &MockPlaylistStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPlaylistStore is an autogenerated mock type for the PlaylistStore type
type MockPlaylistStore struct {
	mock.Mock
}

type MockPlaylistStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPlaylistStore) EXPECT() *MockPlaylistStore_Expecter {
	return &MockPlaylistStore_Expecter{mock: &_m.Mock}
}

// ClearUserPositions provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ClearUserPositions(userID string, bookID string) error {
	ret := _mock.Called(userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for ClearUserPositions")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(userID, bookID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlaylistStore_ClearUserPositions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ClearUserPositions'
type MockPlaylistStore_ClearUserPositions_Call struct {
	*mock.Call
}

// ClearUserPositions is a helper method to define mock.On call
//   - userID string
//   - bookID string
func (_e *MockPlaylistStore_Expecter) ClearUserPositions(userID interface{}, bookID interface{}) *MockPlaylistStore_ClearUserPositions_Call {
	return &MockPlaylistStore_ClearUserPositions_Call{Call: _e.mock.On("ClearUserPositions", userID, bookID)}
}

func (_c *MockPlaylistStore_ClearUserPositions_Call) Run(run func(userID string, bookID string)) *MockPlaylistStore_ClearUserPositions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_ClearUserPositions_Call) Return(err error) *MockPlaylistStore_ClearUserPositions_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlaylistStore_ClearUserPositions_Call) RunAndReturn(run func(userID string, bookID string) error) *MockPlaylistStore_ClearUserPositions_Call {
	_c.Call.Return(run)
	return _c
}

// CountBooks provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) CountBooks() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountBooks")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_CountBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountBooks'
type MockPlaylistStore_CountBooks_Call struct {
	*mock.Call
}

// CountBooks is a helper method to define mock.On call
func (_e *MockPlaylistStore_Expecter) CountBooks() *MockPlaylistStore_CountBooks_Call {
	return &MockPlaylistStore_CountBooks_Call{Call: _e.mock.On("CountBooks")}
}

func (_c *MockPlaylistStore_CountBooks_Call) Run(run func()) *MockPlaylistStore_CountBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaylistStore_CountBooks_Call) Return(n int, err error) *MockPlaylistStore_CountBooks_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPlaylistStore_CountBooks_Call) RunAndReturn(run func() (int, error)) *MockPlaylistStore_CountBooks_Call {
	_c.Call.Return(run)
	return _c
}

// CountQuarantinedBooks provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) CountQuarantinedBooks() (int, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CountQuarantinedBooks")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (int, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_CountQuarantinedBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountQuarantinedBooks'
type MockPlaylistStore_CountQuarantinedBooks_Call struct {
	*mock.Call
}

// CountQuarantinedBooks is a helper method to define mock.On call
func (_e *MockPlaylistStore_Expecter) CountQuarantinedBooks() *MockPlaylistStore_CountQuarantinedBooks_Call {
	return &MockPlaylistStore_CountQuarantinedBooks_Call{Call: _e.mock.On("CountQuarantinedBooks")}
}

func (_c *MockPlaylistStore_CountQuarantinedBooks_Call) Run(run func()) *MockPlaylistStore_CountQuarantinedBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaylistStore_CountQuarantinedBooks_Call) Return(n int, err error) *MockPlaylistStore_CountQuarantinedBooks_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockPlaylistStore_CountQuarantinedBooks_Call) RunAndReturn(run func() (int, error)) *MockPlaylistStore_CountQuarantinedBooks_Call {
	_c.Call.Return(run)
	return _c
}

// CreateUserPlaylist provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) CreateUserPlaylist(pl *database.UserPlaylist) (*database.UserPlaylist, error) {
	ret := _mock.Called(pl)

	if len(ret) == 0 {
		panic("no return value specified for CreateUserPlaylist")
	}

	var r0 *database.UserPlaylist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*database.UserPlaylist) (*database.UserPlaylist, error)); ok {
		return returnFunc(pl)
	}
	if returnFunc, ok := ret.Get(0).(func(*database.UserPlaylist) *database.UserPlaylist); ok {
		r0 = returnFunc(pl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserPlaylist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*database.UserPlaylist) error); ok {
		r1 = returnFunc(pl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_CreateUserPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateUserPlaylist'
type MockPlaylistStore_CreateUserPlaylist_Call struct {
	*mock.Call
}

// CreateUserPlaylist is a helper method to define mock.On call
//   - pl *database.UserPlaylist
func (_e *MockPlaylistStore_Expecter) CreateUserPlaylist(pl interface{}) *MockPlaylistStore_CreateUserPlaylist_Call {
	return &MockPlaylistStore_CreateUserPlaylist_Call{Call: _e.mock.On("CreateUserPlaylist", pl)}
}

func (_c *MockPlaylistStore_CreateUserPlaylist_Call) Run(run func(pl *database.UserPlaylist)) *MockPlaylistStore_CreateUserPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.UserPlaylist
		if args[0] != nil {
			arg0 = args[0].(*database.UserPlaylist)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_CreateUserPlaylist_Call) Return(userPlaylist *database.UserPlaylist, err error) *MockPlaylistStore_CreateUserPlaylist_Call {
	_c.Call.Return(userPlaylist, err)
	return _c
}

func (_c *MockPlaylistStore_CreateUserPlaylist_Call) RunAndReturn(run func(pl *database.UserPlaylist) (*database.UserPlaylist, error)) *MockPlaylistStore_CreateUserPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUserPlaylist provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) DeleteUserPlaylist(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for DeleteUserPlaylist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlaylistStore_DeleteUserPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUserPlaylist'
type MockPlaylistStore_DeleteUserPlaylist_Call struct {
	*mock.Call
}

// DeleteUserPlaylist is a helper method to define mock.On call
//   - id string
func (_e *MockPlaylistStore_Expecter) DeleteUserPlaylist(id interface{}) *MockPlaylistStore_DeleteUserPlaylist_Call {
	return &MockPlaylistStore_DeleteUserPlaylist_Call{Call: _e.mock.On("DeleteUserPlaylist", id)}
}

func (_c *MockPlaylistStore_DeleteUserPlaylist_Call) Run(run func(id string)) *MockPlaylistStore_DeleteUserPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_DeleteUserPlaylist_Call) Return(err error) *MockPlaylistStore_DeleteUserPlaylist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlaylistStore_DeleteUserPlaylist_Call) RunAndReturn(run func(id string) error) *MockPlaylistStore_DeleteUserPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBookSummaries provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetAllBookSummaries(limit int, offset int) ([]database.BookSummary, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBookSummaries")
	}

	var r0 []database.BookSummary
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]database.BookSummary, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []database.BookSummary); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookSummary)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetAllBookSummaries_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBookSummaries'
type MockPlaylistStore_GetAllBookSummaries_Call struct {
	*mock.Call
}

// GetAllBookSummaries is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockPlaylistStore_Expecter) GetAllBookSummaries(limit interface{}, offset interface{}) *MockPlaylistStore_GetAllBookSummaries_Call {
	return &MockPlaylistStore_GetAllBookSummaries_Call{Call: _e.mock.On("GetAllBookSummaries", limit, offset)}
}

func (_c *MockPlaylistStore_GetAllBookSummaries_Call) Run(run func(limit int, offset int)) *MockPlaylistStore_GetAllBookSummaries_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetAllBookSummaries_Call) Return(bookSummarys []database.BookSummary, err error) *MockPlaylistStore_GetAllBookSummaries_Call {
	_c.Call.Return(bookSummarys, err)
	return _c
}

func (_c *MockPlaylistStore_GetAllBookSummaries_Call) RunAndReturn(run func(limit int, offset int) ([]database.BookSummary, error)) *MockPlaylistStore_GetAllBookSummaries_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllBooks provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetAllBooks(limit int, offset int) ([]database.Book, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetAllBooks")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]database.Book, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []database.Book); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetAllBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllBooks'
type MockPlaylistStore_GetAllBooks_Call struct {
	*mock.Call
}

// GetAllBooks is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockPlaylistStore_Expecter) GetAllBooks(limit interface{}, offset interface{}) *MockPlaylistStore_GetAllBooks_Call {
	return &MockPlaylistStore_GetAllBooks_Call{Call: _e.mock.On("GetAllBooks", limit, offset)}
}

func (_c *MockPlaylistStore_GetAllBooks_Call) Run(run func(limit int, offset int)) *MockPlaylistStore_GetAllBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetAllBooks_Call) Return(books []database.Book, err error) *MockPlaylistStore_GetAllBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_GetAllBooks_Call) RunAndReturn(run func(limit int, offset int) ([]database.Book, error)) *MockPlaylistStore_GetAllBooks_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookAtVersion provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBookAtVersion(id string, ts time.Time) (*database.Book, error) {
	ret := _mock.Called(id, ts)

	if len(ret) == 0 {
		panic("no return value specified for GetBookAtVersion")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) (*database.Book, error)); ok {
		return returnFunc(id, ts)
	}
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) *database.Book); ok {
		r0 = returnFunc(id, ts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = returnFunc(id, ts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBookAtVersion_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookAtVersion'
type MockPlaylistStore_GetBookAtVersion_Call struct {
	*mock.Call
}

// GetBookAtVersion is a helper method to define mock.On call
//   - id string
//   - ts time.Time
func (_e *MockPlaylistStore_Expecter) GetBookAtVersion(id interface{}, ts interface{}) *MockPlaylistStore_GetBookAtVersion_Call {
	return &MockPlaylistStore_GetBookAtVersion_Call{Call: _e.mock.On("GetBookAtVersion", id, ts)}
}

func (_c *MockPlaylistStore_GetBookAtVersion_Call) Run(run func(id string, ts time.Time)) *MockPlaylistStore_GetBookAtVersion_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBookAtVersion_Call) Return(book *database.Book, err error) *MockPlaylistStore_GetBookAtVersion_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockPlaylistStore_GetBookAtVersion_Call) RunAndReturn(run func(id string, ts time.Time) (*database.Book, error)) *MockPlaylistStore_GetBookAtVersion_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByFileHash provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBookByFileHash(hash string) (*database.Book, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByFileHash")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBookByFileHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByFileHash'
type MockPlaylistStore_GetBookByFileHash_Call struct {
	*mock.Call
}

// GetBookByFileHash is a helper method to define mock.On call
//   - hash string
func (_e *MockPlaylistStore_Expecter) GetBookByFileHash(hash interface{}) *MockPlaylistStore_GetBookByFileHash_Call {
	return &MockPlaylistStore_GetBookByFileHash_Call{Call: _e.mock.On("GetBookByFileHash", hash)}
}

func (_c *MockPlaylistStore_GetBookByFileHash_Call) Run(run func(hash string)) *MockPlaylistStore_GetBookByFileHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBookByFileHash_Call) Return(book *database.Book, err error) *MockPlaylistStore_GetBookByFileHash_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockPlaylistStore_GetBookByFileHash_Call) RunAndReturn(run func(hash string) (*database.Book, error)) *MockPlaylistStore_GetBookByFileHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByFilePath provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBookByFilePath(path string) (*database.Book, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByFilePath")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(path)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBookByFilePath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByFilePath'
type MockPlaylistStore_GetBookByFilePath_Call struct {
	*mock.Call
}

// GetBookByFilePath is a helper method to define mock.On call
//   - path string
func (_e *MockPlaylistStore_Expecter) GetBookByFilePath(path interface{}) *MockPlaylistStore_GetBookByFilePath_Call {
	return &MockPlaylistStore_GetBookByFilePath_Call{Call: _e.mock.On("GetBookByFilePath", path)}
}

func (_c *MockPlaylistStore_GetBookByFilePath_Call) Run(run func(path string)) *MockPlaylistStore_GetBookByFilePath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBookByFilePath_Call) Return(book *database.Book, err error) *MockPlaylistStore_GetBookByFilePath_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockPlaylistStore_GetBookByFilePath_Call) RunAndReturn(run func(path string) (*database.Book, error)) *MockPlaylistStore_GetBookByFilePath_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByID provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBookByID(id string) (*database.Book, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByID")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBookByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByID'
type MockPlaylistStore_GetBookByID_Call struct {
	*mock.Call
}

// GetBookByID is a helper method to define mock.On call
//   - id string
func (_e *MockPlaylistStore_Expecter) GetBookByID(id interface{}) *MockPlaylistStore_GetBookByID_Call {
	return &MockPlaylistStore_GetBookByID_Call{Call: _e.mock.On("GetBookByID", id)}
}

func (_c *MockPlaylistStore_GetBookByID_Call) Run(run func(id string)) *MockPlaylistStore_GetBookByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBookByID_Call) Return(book *database.Book, err error) *MockPlaylistStore_GetBookByID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockPlaylistStore_GetBookByID_Call) RunAndReturn(run func(id string) (*database.Book, error)) *MockPlaylistStore_GetBookByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByITunesPersistentID provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBookByITunesPersistentID(persistentID string) (*database.Book, error) {
	ret := _mock.Called(persistentID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByITunesPersistentID")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(persistentID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(persistentID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(persistentID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBookByITunesPersistentID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByITunesPersistentID'
type MockPlaylistStore_GetBookByITunesPersistentID_Call struct {
	*mock.Call
}

// GetBookByITunesPersistentID is a helper method to define mock.On call
//   - persistentID string
func (_e *MockPlaylistStore_Expecter) GetBookByITunesPersistentID(persistentID interface{}) *MockPlaylistStore_GetBookByITunesPersistentID_Call {
	return &MockPlaylistStore_GetBookByITunesPersistentID_Call{Call: _e.mock.On("GetBookByITunesPersistentID", persistentID)}
}

func (_c *MockPlaylistStore_GetBookByITunesPersistentID_Call) Run(run func(persistentID string)) *MockPlaylistStore_GetBookByITunesPersistentID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBookByITunesPersistentID_Call) Return(book *database.Book, err error) *MockPlaylistStore_GetBookByITunesPersistentID_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockPlaylistStore_GetBookByITunesPersistentID_Call) RunAndReturn(run func(persistentID string) (*database.Book, error)) *MockPlaylistStore_GetBookByITunesPersistentID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByOrganizedHash provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBookByOrganizedHash(hash string) (*database.Book, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByOrganizedHash")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBookByOrganizedHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByOrganizedHash'
type MockPlaylistStore_GetBookByOrganizedHash_Call struct {
	*mock.Call
}

// GetBookByOrganizedHash is a helper method to define mock.On call
//   - hash string
func (_e *MockPlaylistStore_Expecter) GetBookByOrganizedHash(hash interface{}) *MockPlaylistStore_GetBookByOrganizedHash_Call {
	return &MockPlaylistStore_GetBookByOrganizedHash_Call{Call: _e.mock.On("GetBookByOrganizedHash", hash)}
}

func (_c *MockPlaylistStore_GetBookByOrganizedHash_Call) Run(run func(hash string)) *MockPlaylistStore_GetBookByOrganizedHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBookByOrganizedHash_Call) Return(book *database.Book, err error) *MockPlaylistStore_GetBookByOrganizedHash_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockPlaylistStore_GetBookByOrganizedHash_Call) RunAndReturn(run func(hash string) (*database.Book, error)) *MockPlaylistStore_GetBookByOrganizedHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookByOriginalHash provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBookByOriginalHash(hash string) (*database.Book, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBookByOriginalHash")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBookByOriginalHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookByOriginalHash'
type MockPlaylistStore_GetBookByOriginalHash_Call struct {
	*mock.Call
}

// GetBookByOriginalHash is a helper method to define mock.On call
//   - hash string
func (_e *MockPlaylistStore_Expecter) GetBookByOriginalHash(hash interface{}) *MockPlaylistStore_GetBookByOriginalHash_Call {
	return &MockPlaylistStore_GetBookByOriginalHash_Call{Call: _e.mock.On("GetBookByOriginalHash", hash)}
}

func (_c *MockPlaylistStore_GetBookByOriginalHash_Call) Run(run func(hash string)) *MockPlaylistStore_GetBookByOriginalHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBookByOriginalHash_Call) Return(book *database.Book, err error) *MockPlaylistStore_GetBookByOriginalHash_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockPlaylistStore_GetBookByOriginalHash_Call) RunAndReturn(run func(hash string) (*database.Book, error)) *MockPlaylistStore_GetBookByOriginalHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookSnapshots provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBookSnapshots(id string, limit int) ([]database.BookSnapshot, error) {
	ret := _mock.Called(id, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetBookSnapshots")
	}

	var r0 []database.BookSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int) ([]database.BookSnapshot, error)); ok {
		return returnFunc(id, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int) []database.BookSnapshot); ok {
		r0 = returnFunc(id, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.BookSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int) error); ok {
		r1 = returnFunc(id, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBookSnapshots_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookSnapshots'
type MockPlaylistStore_GetBookSnapshots_Call struct {
	*mock.Call
}

// GetBookSnapshots is a helper method to define mock.On call
//   - id string
//   - limit int
func (_e *MockPlaylistStore_Expecter) GetBookSnapshots(id interface{}, limit interface{}) *MockPlaylistStore_GetBookSnapshots_Call {
	return &MockPlaylistStore_GetBookSnapshots_Call{Call: _e.mock.On("GetBookSnapshots", id, limit)}
}

func (_c *MockPlaylistStore_GetBookSnapshots_Call) Run(run func(id string, limit int)) *MockPlaylistStore_GetBookSnapshots_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBookSnapshots_Call) Return(bookSnapshots []database.BookSnapshot, err error) *MockPlaylistStore_GetBookSnapshots_Call {
	_c.Call.Return(bookSnapshots, err)
	return _c
}

func (_c *MockPlaylistStore_GetBookSnapshots_Call) RunAndReturn(run func(id string, limit int) ([]database.BookSnapshot, error)) *MockPlaylistStore_GetBookSnapshots_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookTombstone provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBookTombstone(id string) (*database.Book, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetBookTombstone")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.Book, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.Book); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBookTombstone_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookTombstone'
type MockPlaylistStore_GetBookTombstone_Call struct {
	*mock.Call
}

// GetBookTombstone is a helper method to define mock.On call
//   - id string
func (_e *MockPlaylistStore_Expecter) GetBookTombstone(id interface{}) *MockPlaylistStore_GetBookTombstone_Call {
	return &MockPlaylistStore_GetBookTombstone_Call{Call: _e.mock.On("GetBookTombstone", id)}
}

func (_c *MockPlaylistStore_GetBookTombstone_Call) Run(run func(id string)) *MockPlaylistStore_GetBookTombstone_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBookTombstone_Call) Return(book *database.Book, err error) *MockPlaylistStore_GetBookTombstone_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockPlaylistStore_GetBookTombstone_Call) RunAndReturn(run func(id string) (*database.Book, error)) *MockPlaylistStore_GetBookTombstone_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByAuthorID provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBooksByAuthorID(authorID int) ([]database.Book, error) {
	ret := _mock.Called(authorID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByAuthorID")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.Book, error)); ok {
		return returnFunc(authorID)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.Book); ok {
		r0 = returnFunc(authorID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(authorID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBooksByAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByAuthorID'
type MockPlaylistStore_GetBooksByAuthorID_Call struct {
	*mock.Call
}

// GetBooksByAuthorID is a helper method to define mock.On call
//   - authorID int
func (_e *MockPlaylistStore_Expecter) GetBooksByAuthorID(authorID interface{}) *MockPlaylistStore_GetBooksByAuthorID_Call {
	return &MockPlaylistStore_GetBooksByAuthorID_Call{Call: _e.mock.On("GetBooksByAuthorID", authorID)}
}

func (_c *MockPlaylistStore_GetBooksByAuthorID_Call) Run(run func(authorID int)) *MockPlaylistStore_GetBooksByAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBooksByAuthorID_Call) Return(books []database.Book, err error) *MockPlaylistStore_GetBooksByAuthorID_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_GetBooksByAuthorID_Call) RunAndReturn(run func(authorID int) ([]database.Book, error)) *MockPlaylistStore_GetBooksByAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByMetadataSourceHash provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBooksByMetadataSourceHash(hash string) ([]database.Book, error) {
	ret := _mock.Called(hash)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByMetadataSourceHash")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.Book, error)); ok {
		return returnFunc(hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.Book); ok {
		r0 = returnFunc(hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBooksByMetadataSourceHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByMetadataSourceHash'
type MockPlaylistStore_GetBooksByMetadataSourceHash_Call struct {
	*mock.Call
}

// GetBooksByMetadataSourceHash is a helper method to define mock.On call
//   - hash string
func (_e *MockPlaylistStore_Expecter) GetBooksByMetadataSourceHash(hash interface{}) *MockPlaylistStore_GetBooksByMetadataSourceHash_Call {
	return &MockPlaylistStore_GetBooksByMetadataSourceHash_Call{Call: _e.mock.On("GetBooksByMetadataSourceHash", hash)}
}

func (_c *MockPlaylistStore_GetBooksByMetadataSourceHash_Call) Run(run func(hash string)) *MockPlaylistStore_GetBooksByMetadataSourceHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBooksByMetadataSourceHash_Call) Return(books []database.Book, err error) *MockPlaylistStore_GetBooksByMetadataSourceHash_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_GetBooksByMetadataSourceHash_Call) RunAndReturn(run func(hash string) ([]database.Book, error)) *MockPlaylistStore_GetBooksByMetadataSourceHash_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksBySeriesID provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBooksBySeriesID(seriesID int) ([]database.Book, error) {
	ret := _mock.Called(seriesID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksBySeriesID")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.Book, error)); ok {
		return returnFunc(seriesID)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.Book); ok {
		r0 = returnFunc(seriesID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(seriesID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBooksBySeriesID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksBySeriesID'
type MockPlaylistStore_GetBooksBySeriesID_Call struct {
	*mock.Call
}

// GetBooksBySeriesID is a helper method to define mock.On call
//   - seriesID int
func (_e *MockPlaylistStore_Expecter) GetBooksBySeriesID(seriesID interface{}) *MockPlaylistStore_GetBooksBySeriesID_Call {
	return &MockPlaylistStore_GetBooksBySeriesID_Call{Call: _e.mock.On("GetBooksBySeriesID", seriesID)}
}

func (_c *MockPlaylistStore_GetBooksBySeriesID_Call) Run(run func(seriesID int)) *MockPlaylistStore_GetBooksBySeriesID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBooksBySeriesID_Call) Return(books []database.Book, err error) *MockPlaylistStore_GetBooksBySeriesID_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_GetBooksBySeriesID_Call) RunAndReturn(run func(seriesID int) ([]database.Book, error)) *MockPlaylistStore_GetBooksBySeriesID_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByTitleInDir provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBooksByTitleInDir(normalizedTitle string, dirPath string) ([]database.Book, error) {
	ret := _mock.Called(normalizedTitle, dirPath)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByTitleInDir")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]database.Book, error)); ok {
		return returnFunc(normalizedTitle, dirPath)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []database.Book); ok {
		r0 = returnFunc(normalizedTitle, dirPath)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(normalizedTitle, dirPath)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBooksByTitleInDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByTitleInDir'
type MockPlaylistStore_GetBooksByTitleInDir_Call struct {
	*mock.Call
}

// GetBooksByTitleInDir is a helper method to define mock.On call
//   - normalizedTitle string
//   - dirPath string
func (_e *MockPlaylistStore_Expecter) GetBooksByTitleInDir(normalizedTitle interface{}, dirPath interface{}) *MockPlaylistStore_GetBooksByTitleInDir_Call {
	return &MockPlaylistStore_GetBooksByTitleInDir_Call{Call: _e.mock.On("GetBooksByTitleInDir", normalizedTitle, dirPath)}
}

func (_c *MockPlaylistStore_GetBooksByTitleInDir_Call) Run(run func(normalizedTitle string, dirPath string)) *MockPlaylistStore_GetBooksByTitleInDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBooksByTitleInDir_Call) Return(books []database.Book, err error) *MockPlaylistStore_GetBooksByTitleInDir_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_GetBooksByTitleInDir_Call) RunAndReturn(run func(normalizedTitle string, dirPath string) ([]database.Book, error)) *MockPlaylistStore_GetBooksByTitleInDir_Call {
	_c.Call.Return(run)
	return _c
}

// GetBooksByVersionGroup provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetBooksByVersionGroup(groupID string) ([]database.Book, error) {
	ret := _mock.Called(groupID)

	if len(ret) == 0 {
		panic("no return value specified for GetBooksByVersionGroup")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]database.Book, error)); ok {
		return returnFunc(groupID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []database.Book); ok {
		r0 = returnFunc(groupID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(groupID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetBooksByVersionGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBooksByVersionGroup'
type MockPlaylistStore_GetBooksByVersionGroup_Call struct {
	*mock.Call
}

// GetBooksByVersionGroup is a helper method to define mock.On call
//   - groupID string
func (_e *MockPlaylistStore_Expecter) GetBooksByVersionGroup(groupID interface{}) *MockPlaylistStore_GetBooksByVersionGroup_Call {
	return &MockPlaylistStore_GetBooksByVersionGroup_Call{Call: _e.mock.On("GetBooksByVersionGroup", groupID)}
}

func (_c *MockPlaylistStore_GetBooksByVersionGroup_Call) Run(run func(groupID string)) *MockPlaylistStore_GetBooksByVersionGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetBooksByVersionGroup_Call) Return(books []database.Book, err error) *MockPlaylistStore_GetBooksByVersionGroup_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_GetBooksByVersionGroup_Call) RunAndReturn(run func(groupID string) ([]database.Book, error)) *MockPlaylistStore_GetBooksByVersionGroup_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistinctGenres provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetDistinctGenres() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDistinctGenres")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetDistinctGenres_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistinctGenres'
type MockPlaylistStore_GetDistinctGenres_Call struct {
	*mock.Call
}

// GetDistinctGenres is a helper method to define mock.On call
func (_e *MockPlaylistStore_Expecter) GetDistinctGenres() *MockPlaylistStore_GetDistinctGenres_Call {
	return &MockPlaylistStore_GetDistinctGenres_Call{Call: _e.mock.On("GetDistinctGenres")}
}

func (_c *MockPlaylistStore_GetDistinctGenres_Call) Run(run func()) *MockPlaylistStore_GetDistinctGenres_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaylistStore_GetDistinctGenres_Call) Return(strings []string, err error) *MockPlaylistStore_GetDistinctGenres_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockPlaylistStore_GetDistinctGenres_Call) RunAndReturn(run func() ([]string, error)) *MockPlaylistStore_GetDistinctGenres_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistinctLanguages provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetDistinctLanguages() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDistinctLanguages")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetDistinctLanguages_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistinctLanguages'
type MockPlaylistStore_GetDistinctLanguages_Call struct {
	*mock.Call
}

// GetDistinctLanguages is a helper method to define mock.On call
func (_e *MockPlaylistStore_Expecter) GetDistinctLanguages() *MockPlaylistStore_GetDistinctLanguages_Call {
	return &MockPlaylistStore_GetDistinctLanguages_Call{Call: _e.mock.On("GetDistinctLanguages")}
}

func (_c *MockPlaylistStore_GetDistinctLanguages_Call) Run(run func()) *MockPlaylistStore_GetDistinctLanguages_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaylistStore_GetDistinctLanguages_Call) Return(strings []string, err error) *MockPlaylistStore_GetDistinctLanguages_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockPlaylistStore_GetDistinctLanguages_Call) RunAndReturn(run func() ([]string, error)) *MockPlaylistStore_GetDistinctLanguages_Call {
	_c.Call.Return(run)
	return _c
}

// GetDuplicateBooks provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetDuplicateBooks() ([][]database.Book, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetDuplicateBooks")
	}

	var r0 [][]database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([][]database.Book, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() [][]database.Book); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetDuplicateBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuplicateBooks'
type MockPlaylistStore_GetDuplicateBooks_Call struct {
	*mock.Call
}

// GetDuplicateBooks is a helper method to define mock.On call
func (_e *MockPlaylistStore_Expecter) GetDuplicateBooks() *MockPlaylistStore_GetDuplicateBooks_Call {
	return &MockPlaylistStore_GetDuplicateBooks_Call{Call: _e.mock.On("GetDuplicateBooks")}
}

func (_c *MockPlaylistStore_GetDuplicateBooks_Call) Run(run func()) *MockPlaylistStore_GetDuplicateBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaylistStore_GetDuplicateBooks_Call) Return(bookss [][]database.Book, err error) *MockPlaylistStore_GetDuplicateBooks_Call {
	_c.Call.Return(bookss, err)
	return _c
}

func (_c *MockPlaylistStore_GetDuplicateBooks_Call) RunAndReturn(run func() ([][]database.Book, error)) *MockPlaylistStore_GetDuplicateBooks_Call {
	_c.Call.Return(run)
	return _c
}

// GetDuplicateBooksByMetadata provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetDuplicateBooksByMetadata(threshold float64) ([][]database.Book, error) {
	ret := _mock.Called(threshold)

	if len(ret) == 0 {
		panic("no return value specified for GetDuplicateBooksByMetadata")
	}

	var r0 [][]database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(float64) ([][]database.Book, error)); ok {
		return returnFunc(threshold)
	}
	if returnFunc, ok := ret.Get(0).(func(float64) [][]database.Book); ok {
		r0 = returnFunc(threshold)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(float64) error); ok {
		r1 = returnFunc(threshold)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetDuplicateBooksByMetadata_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDuplicateBooksByMetadata'
type MockPlaylistStore_GetDuplicateBooksByMetadata_Call struct {
	*mock.Call
}

// GetDuplicateBooksByMetadata is a helper method to define mock.On call
//   - threshold float64
func (_e *MockPlaylistStore_Expecter) GetDuplicateBooksByMetadata(threshold interface{}) *MockPlaylistStore_GetDuplicateBooksByMetadata_Call {
	return &MockPlaylistStore_GetDuplicateBooksByMetadata_Call{Call: _e.mock.On("GetDuplicateBooksByMetadata", threshold)}
}

func (_c *MockPlaylistStore_GetDuplicateBooksByMetadata_Call) Run(run func(threshold float64)) *MockPlaylistStore_GetDuplicateBooksByMetadata_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 float64
		if args[0] != nil {
			arg0 = args[0].(float64)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetDuplicateBooksByMetadata_Call) Return(bookss [][]database.Book, err error) *MockPlaylistStore_GetDuplicateBooksByMetadata_Call {
	_c.Call.Return(bookss, err)
	return _c
}

func (_c *MockPlaylistStore_GetDuplicateBooksByMetadata_Call) RunAndReturn(run func(threshold float64) ([][]database.Book, error)) *MockPlaylistStore_GetDuplicateBooksByMetadata_Call {
	_c.Call.Return(run)
	return _c
}

// GetFolderDuplicates provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetFolderDuplicates() ([][]database.Book, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetFolderDuplicates")
	}

	var r0 [][]database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([][]database.Book, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() [][]database.Book); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([][]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetFolderDuplicates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFolderDuplicates'
type MockPlaylistStore_GetFolderDuplicates_Call struct {
	*mock.Call
}

// GetFolderDuplicates is a helper method to define mock.On call
func (_e *MockPlaylistStore_Expecter) GetFolderDuplicates() *MockPlaylistStore_GetFolderDuplicates_Call {
	return &MockPlaylistStore_GetFolderDuplicates_Call{Call: _e.mock.On("GetFolderDuplicates")}
}

func (_c *MockPlaylistStore_GetFolderDuplicates_Call) Run(run func()) *MockPlaylistStore_GetFolderDuplicates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaylistStore_GetFolderDuplicates_Call) Return(bookss [][]database.Book, err error) *MockPlaylistStore_GetFolderDuplicates_Call {
	_c.Call.Return(bookss, err)
	return _c
}

func (_c *MockPlaylistStore_GetFolderDuplicates_Call) RunAndReturn(run func() ([][]database.Book, error)) *MockPlaylistStore_GetFolderDuplicates_Call {
	_c.Call.Return(run)
	return _c
}

// GetITunesDirtyBooks provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetITunesDirtyBooks() ([]database.Book, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetITunesDirtyBooks")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Book, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Book); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetITunesDirtyBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetITunesDirtyBooks'
type MockPlaylistStore_GetITunesDirtyBooks_Call struct {
	*mock.Call
}

// GetITunesDirtyBooks is a helper method to define mock.On call
func (_e *MockPlaylistStore_Expecter) GetITunesDirtyBooks() *MockPlaylistStore_GetITunesDirtyBooks_Call {
	return &MockPlaylistStore_GetITunesDirtyBooks_Call{Call: _e.mock.On("GetITunesDirtyBooks")}
}

func (_c *MockPlaylistStore_GetITunesDirtyBooks_Call) Run(run func()) *MockPlaylistStore_GetITunesDirtyBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaylistStore_GetITunesDirtyBooks_Call) Return(books []database.Book, err error) *MockPlaylistStore_GetITunesDirtyBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_GetITunesDirtyBooks_Call) RunAndReturn(run func() ([]database.Book, error)) *MockPlaylistStore_GetITunesDirtyBooks_Call {
	_c.Call.Return(run)
	return _c
}

// GetITunesPurgePendingBooks provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetITunesPurgePendingBooks() ([]database.Book, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetITunesPurgePendingBooks")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Book, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Book); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetITunesPurgePendingBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetITunesPurgePendingBooks'
type MockPlaylistStore_GetITunesPurgePendingBooks_Call struct {
	*mock.Call
}

// GetITunesPurgePendingBooks is a helper method to define mock.On call
func (_e *MockPlaylistStore_Expecter) GetITunesPurgePendingBooks() *MockPlaylistStore_GetITunesPurgePendingBooks_Call {
	return &MockPlaylistStore_GetITunesPurgePendingBooks_Call{Call: _e.mock.On("GetITunesPurgePendingBooks")}
}

func (_c *MockPlaylistStore_GetITunesPurgePendingBooks_Call) Run(run func()) *MockPlaylistStore_GetITunesPurgePendingBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaylistStore_GetITunesPurgePendingBooks_Call) Return(books []database.Book, err error) *MockPlaylistStore_GetITunesPurgePendingBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_GetITunesPurgePendingBooks_Call) RunAndReturn(run func() ([]database.Book, error)) *MockPlaylistStore_GetITunesPurgePendingBooks_Call {
	_c.Call.Return(run)
	return _c
}

// GetQuarantinedBooks provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetQuarantinedBooks(limit int, offset int) ([]database.Book, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for GetQuarantinedBooks")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]database.Book, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []database.Book); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetQuarantinedBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetQuarantinedBooks'
type MockPlaylistStore_GetQuarantinedBooks_Call struct {
	*mock.Call
}

// GetQuarantinedBooks is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockPlaylistStore_Expecter) GetQuarantinedBooks(limit interface{}, offset interface{}) *MockPlaylistStore_GetQuarantinedBooks_Call {
	return &MockPlaylistStore_GetQuarantinedBooks_Call{Call: _e.mock.On("GetQuarantinedBooks", limit, offset)}
}

func (_c *MockPlaylistStore_GetQuarantinedBooks_Call) Run(run func(limit int, offset int)) *MockPlaylistStore_GetQuarantinedBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetQuarantinedBooks_Call) Return(books []database.Book, err error) *MockPlaylistStore_GetQuarantinedBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_GetQuarantinedBooks_Call) RunAndReturn(run func(limit int, offset int) ([]database.Book, error)) *MockPlaylistStore_GetQuarantinedBooks_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserBookState provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetUserBookState(userID string, bookID string) (*database.UserBookState, error) {
	ret := _mock.Called(userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserBookState")
	}

	var r0 *database.UserBookState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*database.UserBookState, error)); ok {
		return returnFunc(userID, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *database.UserBookState); ok {
		r0 = returnFunc(userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserBookState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetUserBookState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserBookState'
type MockPlaylistStore_GetUserBookState_Call struct {
	*mock.Call
}

// GetUserBookState is a helper method to define mock.On call
//   - userID string
//   - bookID string
func (_e *MockPlaylistStore_Expecter) GetUserBookState(userID interface{}, bookID interface{}) *MockPlaylistStore_GetUserBookState_Call {
	return &MockPlaylistStore_GetUserBookState_Call{Call: _e.mock.On("GetUserBookState", userID, bookID)}
}

func (_c *MockPlaylistStore_GetUserBookState_Call) Run(run func(userID string, bookID string)) *MockPlaylistStore_GetUserBookState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetUserBookState_Call) Return(userBookState *database.UserBookState, err error) *MockPlaylistStore_GetUserBookState_Call {
	_c.Call.Return(userBookState, err)
	return _c
}

func (_c *MockPlaylistStore_GetUserBookState_Call) RunAndReturn(run func(userID string, bookID string) (*database.UserBookState, error)) *MockPlaylistStore_GetUserBookState_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPlaylist provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetUserPlaylist(id string) (*database.UserPlaylist, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPlaylist")
	}

	var r0 *database.UserPlaylist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.UserPlaylist, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.UserPlaylist); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserPlaylist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetUserPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPlaylist'
type MockPlaylistStore_GetUserPlaylist_Call struct {
	*mock.Call
}

// GetUserPlaylist is a helper method to define mock.On call
//   - id string
func (_e *MockPlaylistStore_Expecter) GetUserPlaylist(id interface{}) *MockPlaylistStore_GetUserPlaylist_Call {
	return &MockPlaylistStore_GetUserPlaylist_Call{Call: _e.mock.On("GetUserPlaylist", id)}
}

func (_c *MockPlaylistStore_GetUserPlaylist_Call) Run(run func(id string)) *MockPlaylistStore_GetUserPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetUserPlaylist_Call) Return(userPlaylist *database.UserPlaylist, err error) *MockPlaylistStore_GetUserPlaylist_Call {
	_c.Call.Return(userPlaylist, err)
	return _c
}

func (_c *MockPlaylistStore_GetUserPlaylist_Call) RunAndReturn(run func(id string) (*database.UserPlaylist, error)) *MockPlaylistStore_GetUserPlaylist_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPlaylistByITunesPID provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetUserPlaylistByITunesPID(pid string) (*database.UserPlaylist, error) {
	ret := _mock.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPlaylistByITunesPID")
	}

	var r0 *database.UserPlaylist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.UserPlaylist, error)); ok {
		return returnFunc(pid)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.UserPlaylist); ok {
		r0 = returnFunc(pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserPlaylist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(pid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetUserPlaylistByITunesPID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPlaylistByITunesPID'
type MockPlaylistStore_GetUserPlaylistByITunesPID_Call struct {
	*mock.Call
}

// GetUserPlaylistByITunesPID is a helper method to define mock.On call
//   - pid string
func (_e *MockPlaylistStore_Expecter) GetUserPlaylistByITunesPID(pid interface{}) *MockPlaylistStore_GetUserPlaylistByITunesPID_Call {
	return &MockPlaylistStore_GetUserPlaylistByITunesPID_Call{Call: _e.mock.On("GetUserPlaylistByITunesPID", pid)}
}

func (_c *MockPlaylistStore_GetUserPlaylistByITunesPID_Call) Run(run func(pid string)) *MockPlaylistStore_GetUserPlaylistByITunesPID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetUserPlaylistByITunesPID_Call) Return(userPlaylist *database.UserPlaylist, err error) *MockPlaylistStore_GetUserPlaylistByITunesPID_Call {
	_c.Call.Return(userPlaylist, err)
	return _c
}

func (_c *MockPlaylistStore_GetUserPlaylistByITunesPID_Call) RunAndReturn(run func(pid string) (*database.UserPlaylist, error)) *MockPlaylistStore_GetUserPlaylistByITunesPID_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPlaylistByName provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetUserPlaylistByName(name string) (*database.UserPlaylist, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPlaylistByName")
	}

	var r0 *database.UserPlaylist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.UserPlaylist, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.UserPlaylist); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserPlaylist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetUserPlaylistByName_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPlaylistByName'
type MockPlaylistStore_GetUserPlaylistByName_Call struct {
	*mock.Call
}

// GetUserPlaylistByName is a helper method to define mock.On call
//   - name string
func (_e *MockPlaylistStore_Expecter) GetUserPlaylistByName(name interface{}) *MockPlaylistStore_GetUserPlaylistByName_Call {
	return &MockPlaylistStore_GetUserPlaylistByName_Call{Call: _e.mock.On("GetUserPlaylistByName", name)}
}

func (_c *MockPlaylistStore_GetUserPlaylistByName_Call) Run(run func(name string)) *MockPlaylistStore_GetUserPlaylistByName_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetUserPlaylistByName_Call) Return(userPlaylist *database.UserPlaylist, err error) *MockPlaylistStore_GetUserPlaylistByName_Call {
	_c.Call.Return(userPlaylist, err)
	return _c
}

func (_c *MockPlaylistStore_GetUserPlaylistByName_Call) RunAndReturn(run func(name string) (*database.UserPlaylist, error)) *MockPlaylistStore_GetUserPlaylistByName_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserPosition provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) GetUserPosition(userID string, bookID string) (*database.UserPosition, error) {
	ret := _mock.Called(userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetUserPosition")
	}

	var r0 *database.UserPosition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*database.UserPosition, error)); ok {
		return returnFunc(userID, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *database.UserPosition); ok {
		r0 = returnFunc(userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.UserPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_GetUserPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserPosition'
type MockPlaylistStore_GetUserPosition_Call struct {
	*mock.Call
}

// GetUserPosition is a helper method to define mock.On call
//   - userID string
//   - bookID string
func (_e *MockPlaylistStore_Expecter) GetUserPosition(userID interface{}, bookID interface{}) *MockPlaylistStore_GetUserPosition_Call {
	return &MockPlaylistStore_GetUserPosition_Call{Call: _e.mock.On("GetUserPosition", userID, bookID)}
}

func (_c *MockPlaylistStore_GetUserPosition_Call) Run(run func(userID string, bookID string)) *MockPlaylistStore_GetUserPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_GetUserPosition_Call) Return(userPosition *database.UserPosition, err error) *MockPlaylistStore_GetUserPosition_Call {
	_c.Call.Return(userPosition, err)
	return _c
}

func (_c *MockPlaylistStore_GetUserPosition_Call) RunAndReturn(run func(userID string, bookID string) (*database.UserPosition, error)) *MockPlaylistStore_GetUserPosition_Call {
	_c.Call.Return(run)
	return _c
}

// ListBookIDs provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ListBookIDs() ([]string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListBookIDs")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []string); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_ListBookIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookIDs'
type MockPlaylistStore_ListBookIDs_Call struct {
	*mock.Call
}

// ListBookIDs is a helper method to define mock.On call
func (_e *MockPlaylistStore_Expecter) ListBookIDs() *MockPlaylistStore_ListBookIDs_Call {
	return &MockPlaylistStore_ListBookIDs_Call{Call: _e.mock.On("ListBookIDs")}
}

func (_c *MockPlaylistStore_ListBookIDs_Call) Run(run func()) *MockPlaylistStore_ListBookIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaylistStore_ListBookIDs_Call) Return(strings []string, err error) *MockPlaylistStore_ListBookIDs_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockPlaylistStore_ListBookIDs_Call) RunAndReturn(run func() ([]string, error)) *MockPlaylistStore_ListBookIDs_Call {
	_c.Call.Return(run)
	return _c
}

// ListBookTombstones provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ListBookTombstones(limit int) ([]database.Book, error) {
	ret := _mock.Called(limit)

	if len(ret) == 0 {
		panic("no return value specified for ListBookTombstones")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) ([]database.Book, error)); ok {
		return returnFunc(limit)
	}
	if returnFunc, ok := ret.Get(0).(func(int) []database.Book); ok {
		r0 = returnFunc(limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_ListBookTombstones_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBookTombstones'
type MockPlaylistStore_ListBookTombstones_Call struct {
	*mock.Call
}

// ListBookTombstones is a helper method to define mock.On call
//   - limit int
func (_e *MockPlaylistStore_Expecter) ListBookTombstones(limit interface{}) *MockPlaylistStore_ListBookTombstones_Call {
	return &MockPlaylistStore_ListBookTombstones_Call{Call: _e.mock.On("ListBookTombstones", limit)}
}

func (_c *MockPlaylistStore_ListBookTombstones_Call) Run(run func(limit int)) *MockPlaylistStore_ListBookTombstones_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_ListBookTombstones_Call) Return(books []database.Book, err error) *MockPlaylistStore_ListBookTombstones_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_ListBookTombstones_Call) RunAndReturn(run func(limit int) ([]database.Book, error)) *MockPlaylistStore_ListBookTombstones_Call {
	_c.Call.Return(run)
	return _c
}

// ListBooksByITunesPID provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ListBooksByITunesPID(limit int, offset int) ([]database.Book, error) {
	ret := _mock.Called(limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListBooksByITunesPID")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int) ([]database.Book, error)); ok {
		return returnFunc(limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int) []database.Book); ok {
		r0 = returnFunc(limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int) error); ok {
		r1 = returnFunc(limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_ListBooksByITunesPID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListBooksByITunesPID'
type MockPlaylistStore_ListBooksByITunesPID_Call struct {
	*mock.Call
}

// ListBooksByITunesPID is a helper method to define mock.On call
//   - limit int
//   - offset int
func (_e *MockPlaylistStore_Expecter) ListBooksByITunesPID(limit interface{}, offset interface{}) *MockPlaylistStore_ListBooksByITunesPID_Call {
	return &MockPlaylistStore_ListBooksByITunesPID_Call{Call: _e.mock.On("ListBooksByITunesPID", limit, offset)}
}

func (_c *MockPlaylistStore_ListBooksByITunesPID_Call) Run(run func(limit int, offset int)) *MockPlaylistStore_ListBooksByITunesPID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_ListBooksByITunesPID_Call) Return(books []database.Book, err error) *MockPlaylistStore_ListBooksByITunesPID_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_ListBooksByITunesPID_Call) RunAndReturn(run func(limit int, offset int) ([]database.Book, error)) *MockPlaylistStore_ListBooksByITunesPID_Call {
	_c.Call.Return(run)
	return _c
}

// ListDirtyUserPlaylists provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ListDirtyUserPlaylists() ([]database.UserPlaylist, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListDirtyUserPlaylists")
	}

	var r0 []database.UserPlaylist
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.UserPlaylist, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.UserPlaylist); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.UserPlaylist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_ListDirtyUserPlaylists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListDirtyUserPlaylists'
type MockPlaylistStore_ListDirtyUserPlaylists_Call struct {
	*mock.Call
}

// ListDirtyUserPlaylists is a helper method to define mock.On call
func (_e *MockPlaylistStore_Expecter) ListDirtyUserPlaylists() *MockPlaylistStore_ListDirtyUserPlaylists_Call {
	return &MockPlaylistStore_ListDirtyUserPlaylists_Call{Call: _e.mock.On("ListDirtyUserPlaylists")}
}

func (_c *MockPlaylistStore_ListDirtyUserPlaylists_Call) Run(run func()) *MockPlaylistStore_ListDirtyUserPlaylists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPlaylistStore_ListDirtyUserPlaylists_Call) Return(userPlaylists []database.UserPlaylist, err error) *MockPlaylistStore_ListDirtyUserPlaylists_Call {
	_c.Call.Return(userPlaylists, err)
	return _c
}

func (_c *MockPlaylistStore_ListDirtyUserPlaylists_Call) RunAndReturn(run func() ([]database.UserPlaylist, error)) *MockPlaylistStore_ListDirtyUserPlaylists_Call {
	_c.Call.Return(run)
	return _c
}

// ListSoftDeletedBooks provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ListSoftDeletedBooks(limit int, offset int, olderThan *time.Time) ([]database.Book, error) {
	ret := _mock.Called(limit, offset, olderThan)

	if len(ret) == 0 {
		panic("no return value specified for ListSoftDeletedBooks")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int, int, *time.Time) ([]database.Book, error)); ok {
		return returnFunc(limit, offset, olderThan)
	}
	if returnFunc, ok := ret.Get(0).(func(int, int, *time.Time) []database.Book); ok {
		r0 = returnFunc(limit, offset, olderThan)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int, int, *time.Time) error); ok {
		r1 = returnFunc(limit, offset, olderThan)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_ListSoftDeletedBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListSoftDeletedBooks'
type MockPlaylistStore_ListSoftDeletedBooks_Call struct {
	*mock.Call
}

// ListSoftDeletedBooks is a helper method to define mock.On call
//   - limit int
//   - offset int
//   - olderThan *time.Time
func (_e *MockPlaylistStore_Expecter) ListSoftDeletedBooks(limit interface{}, offset interface{}, olderThan interface{}) *MockPlaylistStore_ListSoftDeletedBooks_Call {
	return &MockPlaylistStore_ListSoftDeletedBooks_Call{Call: _e.mock.On("ListSoftDeletedBooks", limit, offset, olderThan)}
}

func (_c *MockPlaylistStore_ListSoftDeletedBooks_Call) Run(run func(limit int, offset int, olderThan *time.Time)) *MockPlaylistStore_ListSoftDeletedBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 int
		if args[0] != nil {
			arg0 = args[0].(int)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 *time.Time
		if args[2] != nil {
			arg2 = args[2].(*time.Time)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_ListSoftDeletedBooks_Call) Return(books []database.Book, err error) *MockPlaylistStore_ListSoftDeletedBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_ListSoftDeletedBooks_Call) RunAndReturn(run func(limit int, offset int, olderThan *time.Time) ([]database.Book, error)) *MockPlaylistStore_ListSoftDeletedBooks_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserBookStatesByStatus provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ListUserBookStatesByStatus(userID string, status string, limit int, offset int) ([]database.UserBookState, error) {
	ret := _mock.Called(userID, status, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUserBookStatesByStatus")
	}

	var r0 []database.UserBookState
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) ([]database.UserBookState, error)); ok {
		return returnFunc(userID, status, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, int, int) []database.UserBookState); ok {
		r0 = returnFunc(userID, status, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.UserBookState)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, int, int) error); ok {
		r1 = returnFunc(userID, status, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_ListUserBookStatesByStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserBookStatesByStatus'
type MockPlaylistStore_ListUserBookStatesByStatus_Call struct {
	*mock.Call
}

// ListUserBookStatesByStatus is a helper method to define mock.On call
//   - userID string
//   - status string
//   - limit int
//   - offset int
func (_e *MockPlaylistStore_Expecter) ListUserBookStatesByStatus(userID interface{}, status interface{}, limit interface{}, offset interface{}) *MockPlaylistStore_ListUserBookStatesByStatus_Call {
	return &MockPlaylistStore_ListUserBookStatesByStatus_Call{Call: _e.mock.On("ListUserBookStatesByStatus", userID, status, limit, offset)}
}

func (_c *MockPlaylistStore_ListUserBookStatesByStatus_Call) Run(run func(userID string, status string, limit int, offset int)) *MockPlaylistStore_ListUserBookStatesByStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_ListUserBookStatesByStatus_Call) Return(userBookStates []database.UserBookState, err error) *MockPlaylistStore_ListUserBookStatesByStatus_Call {
	_c.Call.Return(userBookStates, err)
	return _c
}

func (_c *MockPlaylistStore_ListUserBookStatesByStatus_Call) RunAndReturn(run func(userID string, status string, limit int, offset int) ([]database.UserBookState, error)) *MockPlaylistStore_ListUserBookStatesByStatus_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserPlaylists provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ListUserPlaylists(playlistType string, limit int, offset int) ([]database.UserPlaylist, int, error) {
	ret := _mock.Called(playlistType, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListUserPlaylists")
	}

	var r0 []database.UserPlaylist
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]database.UserPlaylist, int, error)); ok {
		return returnFunc(playlistType, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []database.UserPlaylist); ok {
		r0 = returnFunc(playlistType, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.UserPlaylist)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) int); ok {
		r1 = returnFunc(playlistType, limit, offset)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(string, int, int) error); ok {
		r2 = returnFunc(playlistType, limit, offset)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockPlaylistStore_ListUserPlaylists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserPlaylists'
type MockPlaylistStore_ListUserPlaylists_Call struct {
	*mock.Call
}

// ListUserPlaylists is a helper method to define mock.On call
//   - playlistType string
//   - limit int
//   - offset int
func (_e *MockPlaylistStore_Expecter) ListUserPlaylists(playlistType interface{}, limit interface{}, offset interface{}) *MockPlaylistStore_ListUserPlaylists_Call {
	return &MockPlaylistStore_ListUserPlaylists_Call{Call: _e.mock.On("ListUserPlaylists", playlistType, limit, offset)}
}

func (_c *MockPlaylistStore_ListUserPlaylists_Call) Run(run func(playlistType string, limit int, offset int)) *MockPlaylistStore_ListUserPlaylists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_ListUserPlaylists_Call) Return(userPlaylists []database.UserPlaylist, n int, err error) *MockPlaylistStore_ListUserPlaylists_Call {
	_c.Call.Return(userPlaylists, n, err)
	return _c
}

func (_c *MockPlaylistStore_ListUserPlaylists_Call) RunAndReturn(run func(playlistType string, limit int, offset int) ([]database.UserPlaylist, int, error)) *MockPlaylistStore_ListUserPlaylists_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserPositionsForBook provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ListUserPositionsForBook(userID string, bookID string) ([]database.UserPosition, error) {
	ret := _mock.Called(userID, bookID)

	if len(ret) == 0 {
		panic("no return value specified for ListUserPositionsForBook")
	}

	var r0 []database.UserPosition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) ([]database.UserPosition, error)); ok {
		return returnFunc(userID, bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) []database.UserPosition); ok {
		r0 = returnFunc(userID, bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.UserPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(userID, bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_ListUserPositionsForBook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserPositionsForBook'
type MockPlaylistStore_ListUserPositionsForBook_Call struct {
	*mock.Call
}

// ListUserPositionsForBook is a helper method to define mock.On call
//   - userID string
//   - bookID string
func (_e *MockPlaylistStore_Expecter) ListUserPositionsForBook(userID interface{}, bookID interface{}) *MockPlaylistStore_ListUserPositionsForBook_Call {
	return &MockPlaylistStore_ListUserPositionsForBook_Call{Call: _e.mock.On("ListUserPositionsForBook", userID, bookID)}
}

func (_c *MockPlaylistStore_ListUserPositionsForBook_Call) Run(run func(userID string, bookID string)) *MockPlaylistStore_ListUserPositionsForBook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_ListUserPositionsForBook_Call) Return(userPositions []database.UserPosition, err error) *MockPlaylistStore_ListUserPositionsForBook_Call {
	_c.Call.Return(userPositions, err)
	return _c
}

func (_c *MockPlaylistStore_ListUserPositionsForBook_Call) RunAndReturn(run func(userID string, bookID string) ([]database.UserPosition, error)) *MockPlaylistStore_ListUserPositionsForBook_Call {
	_c.Call.Return(run)
	return _c
}

// ListUserPositionsSince provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) ListUserPositionsSince(userID string, t time.Time) ([]database.UserPosition, error) {
	ret := _mock.Called(userID, t)

	if len(ret) == 0 {
		panic("no return value specified for ListUserPositionsSince")
	}

	var r0 []database.UserPosition
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) ([]database.UserPosition, error)); ok {
		return returnFunc(userID, t)
	}
	if returnFunc, ok := ret.Get(0).(func(string, time.Time) []database.UserPosition); ok {
		r0 = returnFunc(userID, t)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.UserPosition)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, time.Time) error); ok {
		r1 = returnFunc(userID, t)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_ListUserPositionsSince_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUserPositionsSince'
type MockPlaylistStore_ListUserPositionsSince_Call struct {
	*mock.Call
}

// ListUserPositionsSince is a helper method to define mock.On call
//   - userID string
//   - t time.Time
func (_e *MockPlaylistStore_Expecter) ListUserPositionsSince(userID interface{}, t interface{}) *MockPlaylistStore_ListUserPositionsSince_Call {
	return &MockPlaylistStore_ListUserPositionsSince_Call{Call: _e.mock.On("ListUserPositionsSince", userID, t)}
}

func (_c *MockPlaylistStore_ListUserPositionsSince_Call) Run(run func(userID string, t time.Time)) *MockPlaylistStore_ListUserPositionsSince_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_ListUserPositionsSince_Call) Return(userPositions []database.UserPosition, err error) *MockPlaylistStore_ListUserPositionsSince_Call {
	_c.Call.Return(userPositions, err)
	return _c
}

func (_c *MockPlaylistStore_ListUserPositionsSince_Call) RunAndReturn(run func(userID string, t time.Time) ([]database.UserPosition, error)) *MockPlaylistStore_ListUserPositionsSince_Call {
	_c.Call.Return(run)
	return _c
}

// SearchBooks provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) SearchBooks(query string, limit int, offset int) ([]database.Book, error) {
	ret := _mock.Called(query, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for SearchBooks")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, int, int) ([]database.Book, error)); ok {
		return returnFunc(query, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(string, int, int) []database.Book); ok {
		r0 = returnFunc(query, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = returnFunc(query, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockPlaylistStore_SearchBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SearchBooks'
type MockPlaylistStore_SearchBooks_Call struct {
	*mock.Call
}

// SearchBooks is a helper method to define mock.On call
//   - query string
//   - limit int
//   - offset int
func (_e *MockPlaylistStore_Expecter) SearchBooks(query interface{}, limit interface{}, offset interface{}) *MockPlaylistStore_SearchBooks_Call {
	return &MockPlaylistStore_SearchBooks_Call{Call: _e.mock.On("SearchBooks", query, limit, offset)}
}

func (_c *MockPlaylistStore_SearchBooks_Call) Run(run func(query string, limit int, offset int)) *MockPlaylistStore_SearchBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_SearchBooks_Call) Return(books []database.Book, err error) *MockPlaylistStore_SearchBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockPlaylistStore_SearchBooks_Call) RunAndReturn(run func(query string, limit int, offset int) ([]database.Book, error)) *MockPlaylistStore_SearchBooks_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserBookState provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) SetUserBookState(state *database.UserBookState) error {
	ret := _mock.Called(state)

	if len(ret) == 0 {
		panic("no return value specified for SetUserBookState")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*database.UserBookState) error); ok {
		r0 = returnFunc(state)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlaylistStore_SetUserBookState_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserBookState'
type MockPlaylistStore_SetUserBookState_Call struct {
	*mock.Call
}

// SetUserBookState is a helper method to define mock.On call
//   - state *database.UserBookState
func (_e *MockPlaylistStore_Expecter) SetUserBookState(state interface{}) *MockPlaylistStore_SetUserBookState_Call {
	return &MockPlaylistStore_SetUserBookState_Call{Call: _e.mock.On("SetUserBookState", state)}
}

func (_c *MockPlaylistStore_SetUserBookState_Call) Run(run func(state *database.UserBookState)) *MockPlaylistStore_SetUserBookState_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.UserBookState
		if args[0] != nil {
			arg0 = args[0].(*database.UserBookState)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_SetUserBookState_Call) Return(err error) *MockPlaylistStore_SetUserBookState_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlaylistStore_SetUserBookState_Call) RunAndReturn(run func(state *database.UserBookState) error) *MockPlaylistStore_SetUserBookState_Call {
	_c.Call.Return(run)
	return _c
}

// SetUserPosition provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) SetUserPosition(userID string, bookID string, segmentID string, positionSeconds float64) error {
	ret := _mock.Called(userID, bookID, segmentID, positionSeconds)

	if len(ret) == 0 {
		panic("no return value specified for SetUserPosition")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, float64) error); ok {
		r0 = returnFunc(userID, bookID, segmentID, positionSeconds)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlaylistStore_SetUserPosition_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetUserPosition'
type MockPlaylistStore_SetUserPosition_Call struct {
	*mock.Call
}

// SetUserPosition is a helper method to define mock.On call
//   - userID string
//   - bookID string
//   - segmentID string
//   - positionSeconds float64
func (_e *MockPlaylistStore_Expecter) SetUserPosition(userID interface{}, bookID interface{}, segmentID interface{}, positionSeconds interface{}) *MockPlaylistStore_SetUserPosition_Call {
	return &MockPlaylistStore_SetUserPosition_Call{Call: _e.mock.On("SetUserPosition", userID, bookID, segmentID, positionSeconds)}
}

func (_c *MockPlaylistStore_SetUserPosition_Call) Run(run func(userID string, bookID string, segmentID string, positionSeconds float64)) *MockPlaylistStore_SetUserPosition_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 float64
		if args[3] != nil {
			arg3 = args[3].(float64)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_SetUserPosition_Call) Return(err error) *MockPlaylistStore_SetUserPosition_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlaylistStore_SetUserPosition_Call) RunAndReturn(run func(userID string, bookID string, segmentID string, positionSeconds float64) error) *MockPlaylistStore_SetUserPosition_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUserPlaylist provides a mock function for the type MockPlaylistStore
func (_mock *MockPlaylistStore) UpdateUserPlaylist(pl *database.UserPlaylist) error {
	ret := _mock.Called(pl)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUserPlaylist")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*database.UserPlaylist) error); ok {
		r0 = returnFunc(pl)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockPlaylistStore_UpdateUserPlaylist_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUserPlaylist'
type MockPlaylistStore_UpdateUserPlaylist_Call struct {
	*mock.Call
}

// UpdateUserPlaylist is a helper method to define mock.On call
//   - pl *database.UserPlaylist
func (_e *MockPlaylistStore_Expecter) UpdateUserPlaylist(pl interface{}) *MockPlaylistStore_UpdateUserPlaylist_Call {
	return &MockPlaylistStore_UpdateUserPlaylist_Call{Call: _e.mock.On("UpdateUserPlaylist", pl)}
}

func (_c *MockPlaylistStore_UpdateUserPlaylist_Call) Run(run func(pl *database.UserPlaylist)) *MockPlaylistStore_UpdateUserPlaylist_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.UserPlaylist
		if args[0] != nil {
			arg0 = args[0].(*database.UserPlaylist)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPlaylistStore_UpdateUserPlaylist_Call) Return(err error) *MockPlaylistStore_UpdateUserPlaylist_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockPlaylistStore_UpdateUserPlaylist_Call) RunAndReturn(run func(pl *database.UserPlaylist) error) *MockPlaylistStore_UpdateUserPlaylist_Call {
	_c.Call.Return(run)
	return _c
}
