// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"

	"github.com/falkcorp/audiobook-organizer/internal/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEventPublisher creates a new instance of MockEventPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEventPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEventPublisher {
	mock := &MockEventPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEventPublisher is an autogenerated mock type for the EventPublisher type
type MockEventPublisher struct {
	mock.Mock
}

type MockEventPublisher_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEventPublisher) EXPECT() *MockEventPublisher_Expecter {
	return &MockEventPublisher_Expecter{mock: &_m.Mock}
}

// Publish provides a mock function for the type MockEventPublisher
func (_mock *MockEventPublisher) Publish(ctx context.Context, event plugin.Event) {
	_mock.Called(ctx, event)
	return
}

// MockEventPublisher_Publish_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Publish'
type MockEventPublisher_Publish_Call struct {
	*mock.Call
}

// Publish is a helper method to define mock.On call
//   - ctx context.Context
//   - event plugin.Event
func (_e *MockEventPublisher_Expecter) Publish(ctx interface{}, event interface{}) *MockEventPublisher_Publish_Call {
	return &MockEventPublisher_Publish_Call{Call: _e.mock.On("Publish", ctx, event)}
}

func (_c *MockEventPublisher_Publish_Call) Run(run func(ctx context.Context, event plugin.Event)) *MockEventPublisher_Publish_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 plugin.Event
		if args[1] != nil {
			arg1 = args[1].(plugin.Event)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockEventPublisher_Publish_Call) Return() *MockEventPublisher_Publish_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockEventPublisher_Publish_Call) RunAndReturn(run func(ctx context.Context, event plugin.Event)) *MockEventPublisher_Publish_Call {
	_c.Run(run)
	return _c
}
