// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/plugin"
	mock "github.com/stretchr/testify/mock"
)

// NewMockPluginRegistrar creates a new instance of MockPluginRegistrar. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockPluginRegistrar(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockPluginRegistrar {
	mock := &MockPluginRegistrar{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockPluginRegistrar is an autogenerated mock type for the PluginRegistrar type
type MockPluginRegistrar struct {
	mock.Mock
}

type MockPluginRegistrar_Expecter struct {
	mock *mock.Mock
}

func (_m *MockPluginRegistrar) EXPECT() *MockPluginRegistrar_Expecter {
	return &MockPluginRegistrar_Expecter{mock: &_m.Mock}
}

// All provides a mock function for the type MockPluginRegistrar
func (_mock *MockPluginRegistrar) All() []plugin.Plugin {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for All")
	}

	var r0 []plugin.Plugin
	if returnFunc, ok := ret.Get(0).(func() []plugin.Plugin); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]plugin.Plugin)
		}
	}
	return r0
}

// MockPluginRegistrar_All_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'All'
type MockPluginRegistrar_All_Call struct {
	*mock.Call
}

// All is a helper method to define mock.On call
func (_e *MockPluginRegistrar_Expecter) All() *MockPluginRegistrar_All_Call {
	return &MockPluginRegistrar_All_Call{Call: _e.mock.On("All")}
}

func (_c *MockPluginRegistrar_All_Call) Run(run func()) *MockPluginRegistrar_All_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockPluginRegistrar_All_Call) Return(plugins []plugin.Plugin) *MockPluginRegistrar_All_Call {
	_c.Call.Return(plugins)
	return _c
}

func (_c *MockPluginRegistrar_All_Call) RunAndReturn(run func() []plugin.Plugin) *MockPluginRegistrar_All_Call {
	_c.Call.Return(run)
	return _c
}

// Disable provides a mock function for the type MockPluginRegistrar
func (_mock *MockPluginRegistrar) Disable(id string) {
	_mock.Called(id)
	return
}

// MockPluginRegistrar_Disable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Disable'
type MockPluginRegistrar_Disable_Call struct {
	*mock.Call
}

// Disable is a helper method to define mock.On call
//   - id string
func (_e *MockPluginRegistrar_Expecter) Disable(id interface{}) *MockPluginRegistrar_Disable_Call {
	return &MockPluginRegistrar_Disable_Call{Call: _e.mock.On("Disable", id)}
}

func (_c *MockPluginRegistrar_Disable_Call) Run(run func(id string)) *MockPluginRegistrar_Disable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPluginRegistrar_Disable_Call) Return() *MockPluginRegistrar_Disable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPluginRegistrar_Disable_Call) RunAndReturn(run func(id string)) *MockPluginRegistrar_Disable_Call {
	_c.Run(run)
	return _c
}

// Enable provides a mock function for the type MockPluginRegistrar
func (_mock *MockPluginRegistrar) Enable(id string) {
	_mock.Called(id)
	return
}

// MockPluginRegistrar_Enable_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Enable'
type MockPluginRegistrar_Enable_Call struct {
	*mock.Call
}

// Enable is a helper method to define mock.On call
//   - id string
func (_e *MockPluginRegistrar_Expecter) Enable(id interface{}) *MockPluginRegistrar_Enable_Call {
	return &MockPluginRegistrar_Enable_Call{Call: _e.mock.On("Enable", id)}
}

func (_c *MockPluginRegistrar_Enable_Call) Run(run func(id string)) *MockPluginRegistrar_Enable_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPluginRegistrar_Enable_Call) Return() *MockPluginRegistrar_Enable_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockPluginRegistrar_Enable_Call) RunAndReturn(run func(id string)) *MockPluginRegistrar_Enable_Call {
	_c.Run(run)
	return _c
}

// Get provides a mock function for the type MockPluginRegistrar
func (_mock *MockPluginRegistrar) Get(id string) (plugin.Plugin, bool) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 plugin.Plugin
	var r1 bool
	if returnFunc, ok := ret.Get(0).(func(string) (plugin.Plugin, bool)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) plugin.Plugin); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(plugin.Plugin)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) bool); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Get(1).(bool)
	}
	return r0, r1
}

// MockPluginRegistrar_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockPluginRegistrar_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockPluginRegistrar_Expecter) Get(id interface{}) *MockPluginRegistrar_Get_Call {
	return &MockPluginRegistrar_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockPluginRegistrar_Get_Call) Run(run func(id string)) *MockPluginRegistrar_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPluginRegistrar_Get_Call) Return(plugin1 plugin.Plugin, b bool) *MockPluginRegistrar_Get_Call {
	_c.Call.Return(plugin1, b)
	return _c
}

func (_c *MockPluginRegistrar_Get_Call) RunAndReturn(run func(id string) (plugin.Plugin, bool)) *MockPluginRegistrar_Get_Call {
	_c.Call.Return(run)
	return _c
}

// IsEnabled provides a mock function for the type MockPluginRegistrar
func (_mock *MockPluginRegistrar) IsEnabled(id string) bool {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for IsEnabled")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(string) bool); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockPluginRegistrar_IsEnabled_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsEnabled'
type MockPluginRegistrar_IsEnabled_Call struct {
	*mock.Call
}

// IsEnabled is a helper method to define mock.On call
//   - id string
func (_e *MockPluginRegistrar_Expecter) IsEnabled(id interface{}) *MockPluginRegistrar_IsEnabled_Call {
	return &MockPluginRegistrar_IsEnabled_Call{Call: _e.mock.On("IsEnabled", id)}
}

func (_c *MockPluginRegistrar_IsEnabled_Call) Run(run func(id string)) *MockPluginRegistrar_IsEnabled_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockPluginRegistrar_IsEnabled_Call) Return(b bool) *MockPluginRegistrar_IsEnabled_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockPluginRegistrar_IsEnabled_Call) RunAndReturn(run func(id string) bool) *MockPluginRegistrar_IsEnabled_Call {
	_c.Call.Return(run)
	return _c
}
