// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"context"
	"time"

	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActivityService creates a new instance of MockActivityService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActivityService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActivityService {
	mock := &MockActivityService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActivityService is an autogenerated mock type for the ActivityService type
type MockActivityService struct {
	mock.Mock
}

type MockActivityService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActivityService) EXPECT() *MockActivityService_Expecter {
	return &MockActivityService_Expecter{mock: &_m.Mock}
}

// CompactByDay provides a mock function for the type MockActivityService
func (_mock *MockActivityService) CompactByDay(ctx context.Context, cutoff time.Time) (database.CompactResult, error) {
	ret := _mock.Called(ctx, cutoff)

	if len(ret) == 0 {
		panic("no return value specified for CompactByDay")
	}

	var r0 database.CompactResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) (database.CompactResult, error)); ok {
		return returnFunc(ctx, cutoff)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, time.Time) database.CompactResult); ok {
		r0 = returnFunc(ctx, cutoff)
	} else {
		r0 = ret.Get(0).(database.CompactResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, time.Time) error); ok {
		r1 = returnFunc(ctx, cutoff)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityService_CompactByDay_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CompactByDay'
type MockActivityService_CompactByDay_Call struct {
	*mock.Call
}

// CompactByDay is a helper method to define mock.On call
//   - ctx context.Context
//   - cutoff time.Time
func (_e *MockActivityService_Expecter) CompactByDay(ctx interface{}, cutoff interface{}) *MockActivityService_CompactByDay_Call {
	return &MockActivityService_CompactByDay_Call{Call: _e.mock.On("CompactByDay", ctx, cutoff)}
}

func (_c *MockActivityService_CompactByDay_Call) Run(run func(ctx context.Context, cutoff time.Time)) *MockActivityService_CompactByDay_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActivityService_CompactByDay_Call) Return(compactResult database.CompactResult, err error) *MockActivityService_CompactByDay_Call {
	_c.Call.Return(compactResult, err)
	return _c
}

func (_c *MockActivityService_CompactByDay_Call) RunAndReturn(run func(ctx context.Context, cutoff time.Time) (database.CompactResult, error)) *MockActivityService_CompactByDay_Call {
	_c.Call.Return(run)
	return _c
}

// GetDistinctSources provides a mock function for the type MockActivityService
func (_mock *MockActivityService) GetDistinctSources(filter database.ActivityFilter) ([]database.SourceCount, error) {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for GetDistinctSources")
	}

	var r0 []database.SourceCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(database.ActivityFilter) ([]database.SourceCount, error)); ok {
		return returnFunc(filter)
	}
	if returnFunc, ok := ret.Get(0).(func(database.ActivityFilter) []database.SourceCount); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.SourceCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(database.ActivityFilter) error); ok {
		r1 = returnFunc(filter)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityService_GetDistinctSources_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetDistinctSources'
type MockActivityService_GetDistinctSources_Call struct {
	*mock.Call
}

// GetDistinctSources is a helper method to define mock.On call
//   - filter database.ActivityFilter
func (_e *MockActivityService_Expecter) GetDistinctSources(filter interface{}) *MockActivityService_GetDistinctSources_Call {
	return &MockActivityService_GetDistinctSources_Call{Call: _e.mock.On("GetDistinctSources", filter)}
}

func (_c *MockActivityService_GetDistinctSources_Call) Run(run func(filter database.ActivityFilter)) *MockActivityService_GetDistinctSources_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.ActivityFilter
		if args[0] != nil {
			arg0 = args[0].(database.ActivityFilter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActivityService_GetDistinctSources_Call) Return(sourceCounts []database.SourceCount, err error) *MockActivityService_GetDistinctSources_Call {
	_c.Call.Return(sourceCounts, err)
	return _c
}

func (_c *MockActivityService_GetDistinctSources_Call) RunAndReturn(run func(filter database.ActivityFilter) ([]database.SourceCount, error)) *MockActivityService_GetDistinctSources_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type MockActivityService
func (_mock *MockActivityService) Query(filter database.ActivityFilter) ([]database.ActivityEntry, int, error) {
	ret := _mock.Called(filter)

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 []database.ActivityEntry
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(database.ActivityFilter) ([]database.ActivityEntry, int, error)); ok {
		return returnFunc(filter)
	}
	if returnFunc, ok := ret.Get(0).(func(database.ActivityFilter) []database.ActivityEntry); ok {
		r0 = returnFunc(filter)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.ActivityEntry)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(database.ActivityFilter) int); ok {
		r1 = returnFunc(filter)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(database.ActivityFilter) error); ok {
		r2 = returnFunc(filter)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockActivityService_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type MockActivityService_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - filter database.ActivityFilter
func (_e *MockActivityService_Expecter) Query(filter interface{}) *MockActivityService_Query_Call {
	return &MockActivityService_Query_Call{Call: _e.mock.On("Query", filter)}
}

func (_c *MockActivityService_Query_Call) Run(run func(filter database.ActivityFilter)) *MockActivityService_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 database.ActivityFilter
		if args[0] != nil {
			arg0 = args[0].(database.ActivityFilter)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActivityService_Query_Call) Return(activityEntrys []database.ActivityEntry, n int, err error) *MockActivityService_Query_Call {
	_c.Call.Return(activityEntrys, n, err)
	return _c
}

func (_c *MockActivityService_Query_Call) RunAndReturn(run func(filter database.ActivityFilter) ([]database.ActivityEntry, int, error)) *MockActivityService_Query_Call {
	_c.Call.Return(run)
	return _c
}

// RecompactDigests provides a mock function for the type MockActivityService
func (_mock *MockActivityService) RecompactDigests(ctx context.Context) (database.RecompactResult, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for RecompactDigests")
	}

	var r0 database.RecompactResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (database.RecompactResult, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) database.RecompactResult); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(database.RecompactResult)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockActivityService_RecompactDigests_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RecompactDigests'
type MockActivityService_RecompactDigests_Call struct {
	*mock.Call
}

// RecompactDigests is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockActivityService_Expecter) RecompactDigests(ctx interface{}) *MockActivityService_RecompactDigests_Call {
	return &MockActivityService_RecompactDigests_Call{Call: _e.mock.On("RecompactDigests", ctx)}
}

func (_c *MockActivityService_RecompactDigests_Call) Run(run func(ctx context.Context)) *MockActivityService_RecompactDigests_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockActivityService_RecompactDigests_Call) Return(recompactResult database.RecompactResult, err error) *MockActivityService_RecompactDigests_Call {
	_c.Call.Return(recompactResult, err)
	return _c
}

func (_c *MockActivityService_RecompactDigests_Call) RunAndReturn(run func(ctx context.Context) (database.RecompactResult, error)) *MockActivityService_RecompactDigests_Call {
	_c.Call.Return(run)
	return _c
}
