// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/dedup"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSplitBookCandidateStore creates a new instance of MockSplitBookCandidateStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSplitBookCandidateStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSplitBookCandidateStore {
	mock := &MockSplitBookCandidateStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSplitBookCandidateStore is an autogenerated mock type for the SplitBookCandidateStore type
type MockSplitBookCandidateStore struct {
	mock.Mock
}

type MockSplitBookCandidateStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSplitBookCandidateStore) EXPECT() *MockSplitBookCandidateStore_Expecter {
	return &MockSplitBookCandidateStore_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockSplitBookCandidateStore
func (_mock *MockSplitBookCandidateStore) Delete(id string) error {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSplitBookCandidateStore_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockSplitBookCandidateStore_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - id string
func (_e *MockSplitBookCandidateStore_Expecter) Delete(id interface{}) *MockSplitBookCandidateStore_Delete_Call {
	return &MockSplitBookCandidateStore_Delete_Call{Call: _e.mock.On("Delete", id)}
}

func (_c *MockSplitBookCandidateStore_Delete_Call) Run(run func(id string)) *MockSplitBookCandidateStore_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSplitBookCandidateStore_Delete_Call) Return(err error) *MockSplitBookCandidateStore_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSplitBookCandidateStore_Delete_Call) RunAndReturn(run func(id string) error) *MockSplitBookCandidateStore_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type MockSplitBookCandidateStore
func (_mock *MockSplitBookCandidateStore) Get(id string) (*dedup.SplitBookCandidate, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *dedup.SplitBookCandidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*dedup.SplitBookCandidate, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *dedup.SplitBookCandidate); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dedup.SplitBookCandidate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSplitBookCandidateStore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type MockSplitBookCandidateStore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - id string
func (_e *MockSplitBookCandidateStore_Expecter) Get(id interface{}) *MockSplitBookCandidateStore_Get_Call {
	return &MockSplitBookCandidateStore_Get_Call{Call: _e.mock.On("Get", id)}
}

func (_c *MockSplitBookCandidateStore_Get_Call) Run(run func(id string)) *MockSplitBookCandidateStore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockSplitBookCandidateStore_Get_Call) Return(splitBookCandidate *dedup.SplitBookCandidate, err error) *MockSplitBookCandidateStore_Get_Call {
	_c.Call.Return(splitBookCandidate, err)
	return _c
}

func (_c *MockSplitBookCandidateStore_Get_Call) RunAndReturn(run func(id string) (*dedup.SplitBookCandidate, error)) *MockSplitBookCandidateStore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockSplitBookCandidateStore
func (_mock *MockSplitBookCandidateStore) List() ([]dedup.SplitBookCandidate, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []dedup.SplitBookCandidate
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]dedup.SplitBookCandidate, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []dedup.SplitBookCandidate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]dedup.SplitBookCandidate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSplitBookCandidateStore_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockSplitBookCandidateStore_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
func (_e *MockSplitBookCandidateStore_Expecter) List() *MockSplitBookCandidateStore_List_Call {
	return &MockSplitBookCandidateStore_List_Call{Call: _e.mock.On("List")}
}

func (_c *MockSplitBookCandidateStore_List_Call) Run(run func()) *MockSplitBookCandidateStore_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSplitBookCandidateStore_List_Call) Return(splitBookCandidates []dedup.SplitBookCandidate, err error) *MockSplitBookCandidateStore_List_Call {
	_c.Call.Return(splitBookCandidates, err)
	return _c
}

func (_c *MockSplitBookCandidateStore_List_Call) RunAndReturn(run func() ([]dedup.SplitBookCandidate, error)) *MockSplitBookCandidateStore_List_Call {
	_c.Call.Return(run)
	return _c
}
