// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/itunes"
	"github.com/falkcorp/audiobook-organizer/internal/itunes/service"
	mock "github.com/stretchr/testify/mock"
)

// NewMockITunesImporter creates a new instance of MockITunesImporter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockITunesImporter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockITunesImporter {
	mock := &MockITunesImporter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockITunesImporter is an autogenerated mock type for the ITunesImporter type
type MockITunesImporter struct {
	mock.Mock
}

type MockITunesImporter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockITunesImporter) EXPECT() *MockITunesImporter_Expecter {
	return &MockITunesImporter_Expecter{mock: &_m.Mock}
}

// CollectITLUpdatesWithBookIDs provides a mock function for the type MockITunesImporter
func (_mock *MockITunesImporter) CollectITLUpdatesWithBookIDs() ([]itunes.ITLLocationUpdate, []string) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for CollectITLUpdatesWithBookIDs")
	}

	var r0 []itunes.ITLLocationUpdate
	var r1 []string
	if returnFunc, ok := ret.Get(0).(func() ([]itunes.ITLLocationUpdate, []string)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []itunes.ITLLocationUpdate); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]itunes.ITLLocationUpdate)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() []string); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]string)
		}
	}
	return r0, r1
}

// MockITunesImporter_CollectITLUpdatesWithBookIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectITLUpdatesWithBookIDs'
type MockITunesImporter_CollectITLUpdatesWithBookIDs_Call struct {
	*mock.Call
}

// CollectITLUpdatesWithBookIDs is a helper method to define mock.On call
func (_e *MockITunesImporter_Expecter) CollectITLUpdatesWithBookIDs() *MockITunesImporter_CollectITLUpdatesWithBookIDs_Call {
	return &MockITunesImporter_CollectITLUpdatesWithBookIDs_Call{Call: _e.mock.On("CollectITLUpdatesWithBookIDs")}
}

func (_c *MockITunesImporter_CollectITLUpdatesWithBookIDs_Call) Run(run func()) *MockITunesImporter_CollectITLUpdatesWithBookIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockITunesImporter_CollectITLUpdatesWithBookIDs_Call) Return(iTLLocationUpdates []itunes.ITLLocationUpdate, strings []string) *MockITunesImporter_CollectITLUpdatesWithBookIDs_Call {
	_c.Call.Return(iTLLocationUpdates, strings)
	return _c
}

func (_c *MockITunesImporter_CollectITLUpdatesWithBookIDs_Call) RunAndReturn(run func() ([]itunes.ITLLocationUpdate, []string)) *MockITunesImporter_CollectITLUpdatesWithBookIDs_Call {
	_c.Call.Return(run)
	return _c
}

// DiscoverLibraryPath provides a mock function for the type MockITunesImporter
func (_mock *MockITunesImporter) DiscoverLibraryPath() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for DiscoverLibraryPath")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockITunesImporter_DiscoverLibraryPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DiscoverLibraryPath'
type MockITunesImporter_DiscoverLibraryPath_Call struct {
	*mock.Call
}

// DiscoverLibraryPath is a helper method to define mock.On call
func (_e *MockITunesImporter_Expecter) DiscoverLibraryPath() *MockITunesImporter_DiscoverLibraryPath_Call {
	return &MockITunesImporter_DiscoverLibraryPath_Call{Call: _e.mock.On("DiscoverLibraryPath")}
}

func (_c *MockITunesImporter_DiscoverLibraryPath_Call) Run(run func()) *MockITunesImporter_DiscoverLibraryPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockITunesImporter_DiscoverLibraryPath_Call) Return(s string) *MockITunesImporter_DiscoverLibraryPath_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockITunesImporter_DiscoverLibraryPath_Call) RunAndReturn(run func() string) *MockITunesImporter_DiscoverLibraryPath_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatus provides a mock function for the type MockITunesImporter
func (_mock *MockITunesImporter) GetStatus(opID string) *itunesservice.ImportStatusSnapshot {
	ret := _mock.Called(opID)

	if len(ret) == 0 {
		panic("no return value specified for GetStatus")
	}

	var r0 *itunesservice.ImportStatusSnapshot
	if returnFunc, ok := ret.Get(0).(func(string) *itunesservice.ImportStatusSnapshot); ok {
		r0 = returnFunc(opID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*itunesservice.ImportStatusSnapshot)
		}
	}
	return r0
}

// MockITunesImporter_GetStatus_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatus'
type MockITunesImporter_GetStatus_Call struct {
	*mock.Call
}

// GetStatus is a helper method to define mock.On call
//   - opID string
func (_e *MockITunesImporter_Expecter) GetStatus(opID interface{}) *MockITunesImporter_GetStatus_Call {
	return &MockITunesImporter_GetStatus_Call{Call: _e.mock.On("GetStatus", opID)}
}

func (_c *MockITunesImporter_GetStatus_Call) Run(run func(opID string)) *MockITunesImporter_GetStatus_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockITunesImporter_GetStatus_Call) Return(importStatusSnapshot *itunesservice.ImportStatusSnapshot) *MockITunesImporter_GetStatus_Call {
	_c.Call.Return(importStatusSnapshot)
	return _c
}

func (_c *MockITunesImporter_GetStatus_Call) RunAndReturn(run func(opID string) *itunesservice.ImportStatusSnapshot) *MockITunesImporter_GetStatus_Call {
	_c.Call.Return(run)
	return _c
}

// GetStatusBulk provides a mock function for the type MockITunesImporter
func (_mock *MockITunesImporter) GetStatusBulk(ids []string) map[string]*itunesservice.ImportStatusSnapshot {
	ret := _mock.Called(ids)

	if len(ret) == 0 {
		panic("no return value specified for GetStatusBulk")
	}

	var r0 map[string]*itunesservice.ImportStatusSnapshot
	if returnFunc, ok := ret.Get(0).(func([]string) map[string]*itunesservice.ImportStatusSnapshot); ok {
		r0 = returnFunc(ids)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*itunesservice.ImportStatusSnapshot)
		}
	}
	return r0
}

// MockITunesImporter_GetStatusBulk_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetStatusBulk'
type MockITunesImporter_GetStatusBulk_Call struct {
	*mock.Call
}

// GetStatusBulk is a helper method to define mock.On call
//   - ids []string
func (_e *MockITunesImporter_Expecter) GetStatusBulk(ids interface{}) *MockITunesImporter_GetStatusBulk_Call {
	return &MockITunesImporter_GetStatusBulk_Call{Call: _e.mock.On("GetStatusBulk", ids)}
}

func (_c *MockITunesImporter_GetStatusBulk_Call) Run(run func(ids []string)) *MockITunesImporter_GetStatusBulk_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockITunesImporter_GetStatusBulk_Call) Return(stringToImportStatusSnapshot map[string]*itunesservice.ImportStatusSnapshot) *MockITunesImporter_GetStatusBulk_Call {
	_c.Call.Return(stringToImportStatusSnapshot)
	return _c
}

func (_c *MockITunesImporter_GetStatusBulk_Call) RunAndReturn(run func(ids []string) map[string]*itunesservice.ImportStatusSnapshot) *MockITunesImporter_GetStatusBulk_Call {
	_c.Call.Return(run)
	return _c
}
