// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/falkcorp/audiobook-organizer/internal/organizer"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRenameServicer creates a new instance of MockRenameServicer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRenameServicer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRenameServicer {
	mock := &MockRenameServicer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRenameServicer is an autogenerated mock type for the RenameServicer type
type MockRenameServicer struct {
	mock.Mock
}

type MockRenameServicer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRenameServicer) EXPECT() *MockRenameServicer_Expecter {
	return &MockRenameServicer_Expecter{mock: &_m.Mock}
}

// ApplyRename provides a mock function for the type MockRenameServicer
func (_mock *MockRenameServicer) ApplyRename(bookID string, operationID string) (*organizer.RenameApplyResult, error) {
	ret := _mock.Called(bookID, operationID)

	if len(ret) == 0 {
		panic("no return value specified for ApplyRename")
	}

	var r0 *organizer.RenameApplyResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string) (*organizer.RenameApplyResult, error)); ok {
		return returnFunc(bookID, operationID)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string) *organizer.RenameApplyResult); ok {
		r0 = returnFunc(bookID, operationID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*organizer.RenameApplyResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string) error); ok {
		r1 = returnFunc(bookID, operationID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenameServicer_ApplyRename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ApplyRename'
type MockRenameServicer_ApplyRename_Call struct {
	*mock.Call
}

// ApplyRename is a helper method to define mock.On call
//   - bookID string
//   - operationID string
func (_e *MockRenameServicer_Expecter) ApplyRename(bookID interface{}, operationID interface{}) *MockRenameServicer_ApplyRename_Call {
	return &MockRenameServicer_ApplyRename_Call{Call: _e.mock.On("ApplyRename", bookID, operationID)}
}

func (_c *MockRenameServicer_ApplyRename_Call) Run(run func(bookID string, operationID string)) *MockRenameServicer_ApplyRename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRenameServicer_ApplyRename_Call) Return(renameApplyResult *organizer.RenameApplyResult, err error) *MockRenameServicer_ApplyRename_Call {
	_c.Call.Return(renameApplyResult, err)
	return _c
}

func (_c *MockRenameServicer_ApplyRename_Call) RunAndReturn(run func(bookID string, operationID string) (*organizer.RenameApplyResult, error)) *MockRenameServicer_ApplyRename_Call {
	_c.Call.Return(run)
	return _c
}

// PreviewRename provides a mock function for the type MockRenameServicer
func (_mock *MockRenameServicer) PreviewRename(bookID string) (*organizer.RenamePreview, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for PreviewRename")
	}

	var r0 *organizer.RenamePreview
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*organizer.RenamePreview, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *organizer.RenamePreview); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*organizer.RenamePreview)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRenameServicer_PreviewRename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreviewRename'
type MockRenameServicer_PreviewRename_Call struct {
	*mock.Call
}

// PreviewRename is a helper method to define mock.On call
//   - bookID string
func (_e *MockRenameServicer_Expecter) PreviewRename(bookID interface{}) *MockRenameServicer_PreviewRename_Call {
	return &MockRenameServicer_PreviewRename_Call{Call: _e.mock.On("PreviewRename", bookID)}
}

func (_c *MockRenameServicer_PreviewRename_Call) Run(run func(bookID string)) *MockRenameServicer_PreviewRename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockRenameServicer_PreviewRename_Call) Return(renamePreview *organizer.RenamePreview, err error) *MockRenameServicer_PreviewRename_Call {
	_c.Call.Return(renamePreview, err)
	return _c
}

func (_c *MockRenameServicer_PreviewRename_Call) RunAndReturn(run func(bookID string) (*organizer.RenamePreview, error)) *MockRenameServicer_PreviewRename_Call {
	_c.Call.Return(run)
	return _c
}
