// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"time"

	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockCacheMetricsStore creates a new instance of MockCacheMetricsStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCacheMetricsStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCacheMetricsStore {
	mock := &MockCacheMetricsStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCacheMetricsStore is an autogenerated mock type for the CacheMetricsStore type
type MockCacheMetricsStore struct {
	mock.Mock
}

type MockCacheMetricsStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCacheMetricsStore) EXPECT() *MockCacheMetricsStore_Expecter {
	return &MockCacheMetricsStore_Expecter{mock: &_m.Mock}
}

// GetCacheStatsHistory provides a mock function for the type MockCacheMetricsStore
func (_mock *MockCacheMetricsStore) GetCacheStatsHistory(cacheName string, since time.Time, limit int) ([]database.CacheStatsSnapshot, error) {
	ret := _mock.Called(cacheName, since, limit)

	if len(ret) == 0 {
		panic("no return value specified for GetCacheStatsHistory")
	}

	var r0 []database.CacheStatsSnapshot
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, time.Time, int) ([]database.CacheStatsSnapshot, error)); ok {
		return returnFunc(cacheName, since, limit)
	}
	if returnFunc, ok := ret.Get(0).(func(string, time.Time, int) []database.CacheStatsSnapshot); ok {
		r0 = returnFunc(cacheName, since, limit)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.CacheStatsSnapshot)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, time.Time, int) error); ok {
		r1 = returnFunc(cacheName, since, limit)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCacheMetricsStore_GetCacheStatsHistory_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCacheStatsHistory'
type MockCacheMetricsStore_GetCacheStatsHistory_Call struct {
	*mock.Call
}

// GetCacheStatsHistory is a helper method to define mock.On call
//   - cacheName string
//   - since time.Time
//   - limit int
func (_e *MockCacheMetricsStore_Expecter) GetCacheStatsHistory(cacheName interface{}, since interface{}, limit interface{}) *MockCacheMetricsStore_GetCacheStatsHistory_Call {
	return &MockCacheMetricsStore_GetCacheStatsHistory_Call{Call: _e.mock.On("GetCacheStatsHistory", cacheName, since, limit)}
}

func (_c *MockCacheMetricsStore_GetCacheStatsHistory_Call) Run(run func(cacheName string, since time.Time, limit int)) *MockCacheMetricsStore_GetCacheStatsHistory_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 time.Time
		if args[1] != nil {
			arg1 = args[1].(time.Time)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockCacheMetricsStore_GetCacheStatsHistory_Call) Return(cacheStatsSnapshots []database.CacheStatsSnapshot, err error) *MockCacheMetricsStore_GetCacheStatsHistory_Call {
	_c.Call.Return(cacheStatsSnapshots, err)
	return _c
}

func (_c *MockCacheMetricsStore_GetCacheStatsHistory_Call) RunAndReturn(run func(cacheName string, since time.Time, limit int) ([]database.CacheStatsSnapshot, error)) *MockCacheMetricsStore_GetCacheStatsHistory_Call {
	_c.Call.Return(run)
	return _c
}
