// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"github.com/jdfalk/audiobook-organizer/internal/operations/registry"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOperationsEventHub creates a new instance of MockOperationsEventHub. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOperationsEventHub(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOperationsEventHub {
	mock := &MockOperationsEventHub{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOperationsEventHub is an autogenerated mock type for the OperationsEventHub type
type MockOperationsEventHub struct {
	mock.Mock
}

type MockOperationsEventHub_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOperationsEventHub) EXPECT() *MockOperationsEventHub_Expecter {
	return &MockOperationsEventHub_Expecter{mock: &_m.Mock}
}

// Subscribe provides a mock function for the type MockOperationsEventHub
func (_mock *MockOperationsEventHub) Subscribe() (<-chan registry.Event, func()) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Subscribe")
	}

	var r0 <-chan registry.Event
	var r1 func()
	if returnFunc, ok := ret.Get(0).(func() (<-chan registry.Event, func())); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() <-chan registry.Event); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan registry.Event)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() func()); ok {
		r1 = returnFunc()
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).(func())
		}
	}
	return r0, r1
}

// MockOperationsEventHub_Subscribe_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Subscribe'
type MockOperationsEventHub_Subscribe_Call struct {
	*mock.Call
}

// Subscribe is a helper method to define mock.On call
func (_e *MockOperationsEventHub_Expecter) Subscribe() *MockOperationsEventHub_Subscribe_Call {
	return &MockOperationsEventHub_Subscribe_Call{Call: _e.mock.On("Subscribe")}
}

func (_c *MockOperationsEventHub_Subscribe_Call) Run(run func()) *MockOperationsEventHub_Subscribe_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockOperationsEventHub_Subscribe_Call) Return(eventCh <-chan registry.Event, fn func()) *MockOperationsEventHub_Subscribe_Call {
	_c.Call.Return(eventCh, fn)
	return _c
}

func (_c *MockOperationsEventHub_Subscribe_Call) RunAndReturn(run func() (<-chan registry.Event, func())) *MockOperationsEventHub_Subscribe_Call {
	_c.Call.Return(run)
	return _c
}
