// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package handlersmocks

import (
	"time"

	"github.com/jdfalk/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockUserStore creates a new instance of MockUserStore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockUserStore(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockUserStore {
	mock := &MockUserStore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockUserStore is an autogenerated mock type for the UserStore type
type MockUserStore struct {
	mock.Mock
}

type MockUserStore_Expecter struct {
	mock *mock.Mock
}

func (_m *MockUserStore) EXPECT() *MockUserStore_Expecter {
	return &MockUserStore_Expecter{mock: &_m.Mock}
}

// ConsumeInvite provides a mock function for the type MockUserStore
func (_mock *MockUserStore) ConsumeInvite(token string, algo string, hash string) (*database.User, error) {
	ret := _mock.Called(token, algo, hash)

	if len(ret) == 0 {
		panic("no return value specified for ConsumeInvite")
	}

	var r0 *database.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string) (*database.User, error)); ok {
		return returnFunc(token, algo, hash)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string) *database.User); ok {
		r0 = returnFunc(token, algo, hash)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string) error); ok {
		r1 = returnFunc(token, algo, hash)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_ConsumeInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConsumeInvite'
type MockUserStore_ConsumeInvite_Call struct {
	*mock.Call
}

// ConsumeInvite is a helper method to define mock.On call
//   - token string
//   - algo string
//   - hash string
func (_e *MockUserStore_Expecter) ConsumeInvite(token interface{}, algo interface{}, hash interface{}) *MockUserStore_ConsumeInvite_Call {
	return &MockUserStore_ConsumeInvite_Call{Call: _e.mock.On("ConsumeInvite", token, algo, hash)}
}

func (_c *MockUserStore_ConsumeInvite_Call) Run(run func(token string, algo string, hash string)) *MockUserStore_ConsumeInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockUserStore_ConsumeInvite_Call) Return(user *database.User, err error) *MockUserStore_ConsumeInvite_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStore_ConsumeInvite_Call) RunAndReturn(run func(token string, algo string, hash string) (*database.User, error)) *MockUserStore_ConsumeInvite_Call {
	_c.Call.Return(run)
	return _c
}

// CreateInvite provides a mock function for the type MockUserStore
func (_mock *MockUserStore) CreateInvite(invite *database.Invite) (*database.Invite, error) {
	ret := _mock.Called(invite)

	if len(ret) == 0 {
		panic("no return value specified for CreateInvite")
	}

	var r0 *database.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(*database.Invite) (*database.Invite, error)); ok {
		return returnFunc(invite)
	}
	if returnFunc, ok := ret.Get(0).(func(*database.Invite) *database.Invite); ok {
		r0 = returnFunc(invite)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(*database.Invite) error); ok {
		r1 = returnFunc(invite)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_CreateInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateInvite'
type MockUserStore_CreateInvite_Call struct {
	*mock.Call
}

// CreateInvite is a helper method to define mock.On call
//   - invite *database.Invite
func (_e *MockUserStore_Expecter) CreateInvite(invite interface{}) *MockUserStore_CreateInvite_Call {
	return &MockUserStore_CreateInvite_Call{Call: _e.mock.On("CreateInvite", invite)}
}

func (_c *MockUserStore_CreateInvite_Call) Run(run func(invite *database.Invite)) *MockUserStore_CreateInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.Invite
		if args[0] != nil {
			arg0 = args[0].(*database.Invite)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserStore_CreateInvite_Call) Return(invite1 *database.Invite, err error) *MockUserStore_CreateInvite_Call {
	_c.Call.Return(invite1, err)
	return _c
}

func (_c *MockUserStore_CreateInvite_Call) RunAndReturn(run func(invite *database.Invite) (*database.Invite, error)) *MockUserStore_CreateInvite_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type MockUserStore
func (_mock *MockUserStore) CreateSession(userID string, ip string, ua string, ttl time.Duration) (*database.Session, error) {
	ret := _mock.Called(userID, ip, ua, ttl)

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *database.Session
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string, string, string, time.Duration) (*database.Session, error)); ok {
		return returnFunc(userID, ip, ua, ttl)
	}
	if returnFunc, ok := ret.Get(0).(func(string, string, string, time.Duration) *database.Session); ok {
		r0 = returnFunc(userID, ip, ua, ttl)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Session)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string, string, string, time.Duration) error); ok {
		r1 = returnFunc(userID, ip, ua, ttl)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockUserStore_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - userID string
//   - ip string
//   - ua string
//   - ttl time.Duration
func (_e *MockUserStore_Expecter) CreateSession(userID interface{}, ip interface{}, ua interface{}, ttl interface{}) *MockUserStore_CreateSession_Call {
	return &MockUserStore_CreateSession_Call{Call: _e.mock.On("CreateSession", userID, ip, ua, ttl)}
}

func (_c *MockUserStore_CreateSession_Call) Run(run func(userID string, ip string, ua string, ttl time.Duration)) *MockUserStore_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 time.Duration
		if args[3] != nil {
			arg3 = args[3].(time.Duration)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockUserStore_CreateSession_Call) Return(session *database.Session, err error) *MockUserStore_CreateSession_Call {
	_c.Call.Return(session, err)
	return _c
}

func (_c *MockUserStore_CreateSession_Call) RunAndReturn(run func(userID string, ip string, ua string, ttl time.Duration) (*database.Session, error)) *MockUserStore_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteInvite provides a mock function for the type MockUserStore
func (_mock *MockUserStore) DeleteInvite(token string) error {
	ret := _mock.Called(token)

	if len(ret) == 0 {
		panic("no return value specified for DeleteInvite")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(token)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserStore_DeleteInvite_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteInvite'
type MockUserStore_DeleteInvite_Call struct {
	*mock.Call
}

// DeleteInvite is a helper method to define mock.On call
//   - token string
func (_e *MockUserStore_Expecter) DeleteInvite(token interface{}) *MockUserStore_DeleteInvite_Call {
	return &MockUserStore_DeleteInvite_Call{Call: _e.mock.On("DeleteInvite", token)}
}

func (_c *MockUserStore_DeleteInvite_Call) Run(run func(token string)) *MockUserStore_DeleteInvite_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserStore_DeleteInvite_Call) Return(err error) *MockUserStore_DeleteInvite_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserStore_DeleteInvite_Call) RunAndReturn(run func(token string) error) *MockUserStore_DeleteInvite_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserByID provides a mock function for the type MockUserStore
func (_mock *MockUserStore) GetUserByID(id string) (*database.User, error) {
	ret := _mock.Called(id)

	if len(ret) == 0 {
		panic("no return value specified for GetUserByID")
	}

	var r0 *database.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (*database.User, error)); ok {
		return returnFunc(id)
	}
	if returnFunc, ok := ret.Get(0).(func(string) *database.User); ok {
		r0 = returnFunc(id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_GetUserByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserByID'
type MockUserStore_GetUserByID_Call struct {
	*mock.Call
}

// GetUserByID is a helper method to define mock.On call
//   - id string
func (_e *MockUserStore_Expecter) GetUserByID(id interface{}) *MockUserStore_GetUserByID_Call {
	return &MockUserStore_GetUserByID_Call{Call: _e.mock.On("GetUserByID", id)}
}

func (_c *MockUserStore_GetUserByID_Call) Run(run func(id string)) *MockUserStore_GetUserByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserStore_GetUserByID_Call) Return(user *database.User, err error) *MockUserStore_GetUserByID_Call {
	_c.Call.Return(user, err)
	return _c
}

func (_c *MockUserStore_GetUserByID_Call) RunAndReturn(run func(id string) (*database.User, error)) *MockUserStore_GetUserByID_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveInvites provides a mock function for the type MockUserStore
func (_mock *MockUserStore) ListActiveInvites() ([]database.Invite, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListActiveInvites")
	}

	var r0 []database.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.Invite, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.Invite); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_ListActiveInvites_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveInvites'
type MockUserStore_ListActiveInvites_Call struct {
	*mock.Call
}

// ListActiveInvites is a helper method to define mock.On call
func (_e *MockUserStore_Expecter) ListActiveInvites() *MockUserStore_ListActiveInvites_Call {
	return &MockUserStore_ListActiveInvites_Call{Call: _e.mock.On("ListActiveInvites")}
}

func (_c *MockUserStore_ListActiveInvites_Call) Run(run func()) *MockUserStore_ListActiveInvites_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserStore_ListActiveInvites_Call) Return(invites []database.Invite, err error) *MockUserStore_ListActiveInvites_Call {
	_c.Call.Return(invites, err)
	return _c
}

func (_c *MockUserStore_ListActiveInvites_Call) RunAndReturn(run func() ([]database.Invite, error)) *MockUserStore_ListActiveInvites_Call {
	_c.Call.Return(run)
	return _c
}

// ListUsers provides a mock function for the type MockUserStore
func (_mock *MockUserStore) ListUsers() ([]database.User, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListUsers")
	}

	var r0 []database.User
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.User, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.User); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.User)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockUserStore_ListUsers_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListUsers'
type MockUserStore_ListUsers_Call struct {
	*mock.Call
}

// ListUsers is a helper method to define mock.On call
func (_e *MockUserStore_Expecter) ListUsers() *MockUserStore_ListUsers_Call {
	return &MockUserStore_ListUsers_Call{Call: _e.mock.On("ListUsers")}
}

func (_c *MockUserStore_ListUsers_Call) Run(run func()) *MockUserStore_ListUsers_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockUserStore_ListUsers_Call) Return(users []database.User, err error) *MockUserStore_ListUsers_Call {
	_c.Call.Return(users, err)
	return _c
}

func (_c *MockUserStore_ListUsers_Call) RunAndReturn(run func() ([]database.User, error)) *MockUserStore_ListUsers_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateUser provides a mock function for the type MockUserStore
func (_mock *MockUserStore) UpdateUser(user *database.User) error {
	ret := _mock.Called(user)

	if len(ret) == 0 {
		panic("no return value specified for UpdateUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(*database.User) error); ok {
		r0 = returnFunc(user)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockUserStore_UpdateUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateUser'
type MockUserStore_UpdateUser_Call struct {
	*mock.Call
}

// UpdateUser is a helper method to define mock.On call
//   - user *database.User
func (_e *MockUserStore_Expecter) UpdateUser(user interface{}) *MockUserStore_UpdateUser_Call {
	return &MockUserStore_UpdateUser_Call{Call: _e.mock.On("UpdateUser", user)}
}

func (_c *MockUserStore_UpdateUser_Call) Run(run func(user *database.User)) *MockUserStore_UpdateUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 *database.User
		if args[0] != nil {
			arg0 = args[0].(*database.User)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockUserStore_UpdateUser_Call) Return(err error) *MockUserStore_UpdateUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockUserStore_UpdateUser_Call) RunAndReturn(run func(user *database.User) error) *MockUserStore_UpdateUser_Call {
	_c.Call.Return(run)
	return _c
}
