// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audiobooksmocks

import (
	"context"

	"github.com/jdfalk/audiobook-organizer/internal/audiobooks"
	"github.com/jdfalk/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAudiobookService creates a new instance of MockAudiobookService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudiobookService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudiobookService {
	mock := &MockAudiobookService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAudiobookService is an autogenerated mock type for the AudiobookService type
type MockAudiobookService struct {
	mock.Mock
}

type MockAudiobookService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudiobookService) EXPECT() *MockAudiobookService_Expecter {
	return &MockAudiobookService_Expecter{mock: &_m.Mock}
}

// BatchUpdateUserTags provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) BatchUpdateUserTags(bookIDs []string, addTags []string, removeTags []string) (int, error) {
	ret := _mock.Called(bookIDs, addTags, removeTags)

	if len(ret) == 0 {
		panic("no return value specified for BatchUpdateUserTags")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string, []string, []string) (int, error)); ok {
		return returnFunc(bookIDs, addTags, removeTags)
	}
	if returnFunc, ok := ret.Get(0).(func([]string, []string, []string) int); ok {
		r0 = returnFunc(bookIDs, addTags, removeTags)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]string, []string, []string) error); ok {
		r1 = returnFunc(bookIDs, addTags, removeTags)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_BatchUpdateUserTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BatchUpdateUserTags'
type MockAudiobookService_BatchUpdateUserTags_Call struct {
	*mock.Call
}

// BatchUpdateUserTags is a helper method to define mock.On call
//   - bookIDs []string
//   - addTags []string
//   - removeTags []string
func (_e *MockAudiobookService_Expecter) BatchUpdateUserTags(bookIDs interface{}, addTags interface{}, removeTags interface{}) *MockAudiobookService_BatchUpdateUserTags_Call {
	return &MockAudiobookService_BatchUpdateUserTags_Call{Call: _e.mock.On("BatchUpdateUserTags", bookIDs, addTags, removeTags)}
}

func (_c *MockAudiobookService_BatchUpdateUserTags_Call) Run(run func(bookIDs []string, addTags []string, removeTags []string)) *MockAudiobookService_BatchUpdateUserTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAudiobookService_BatchUpdateUserTags_Call) Return(n int, err error) *MockAudiobookService_BatchUpdateUserTags_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAudiobookService_BatchUpdateUserTags_Call) RunAndReturn(run func(bookIDs []string, addTags []string, removeTags []string) (int, error)) *MockAudiobookService_BatchUpdateUserTags_Call {
	_c.Call.Return(run)
	return _c
}

// CountAudiobooks provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) CountAudiobooks(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for CountAudiobooks")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_CountAudiobooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountAudiobooks'
type MockAudiobookService_CountAudiobooks_Call struct {
	*mock.Call
}

// CountAudiobooks is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockAudiobookService_Expecter) CountAudiobooks(ctx interface{}) *MockAudiobookService_CountAudiobooks_Call {
	return &MockAudiobookService_CountAudiobooks_Call{Call: _e.mock.On("CountAudiobooks", ctx)}
}

func (_c *MockAudiobookService_CountAudiobooks_Call) Run(run func(ctx context.Context)) *MockAudiobookService_CountAudiobooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAudiobookService_CountAudiobooks_Call) Return(n int, err error) *MockAudiobookService_CountAudiobooks_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockAudiobookService_CountAudiobooks_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockAudiobookService_CountAudiobooks_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAudiobook provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) DeleteAudiobook(ctx context.Context, id string, opts *audiobooks.DeleteAudiobookOptions) (map[string]any, error) {
	ret := _mock.Called(ctx, id, opts)

	if len(ret) == 0 {
		panic("no return value specified for DeleteAudiobook")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *audiobooks.DeleteAudiobookOptions) (map[string]any, error)); ok {
		return returnFunc(ctx, id, opts)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, *audiobooks.DeleteAudiobookOptions) map[string]any); ok {
		r0 = returnFunc(ctx, id, opts)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, *audiobooks.DeleteAudiobookOptions) error); ok {
		r1 = returnFunc(ctx, id, opts)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_DeleteAudiobook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAudiobook'
type MockAudiobookService_DeleteAudiobook_Call struct {
	*mock.Call
}

// DeleteAudiobook is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - opts *audiobooks.DeleteAudiobookOptions
func (_e *MockAudiobookService_Expecter) DeleteAudiobook(ctx interface{}, id interface{}, opts interface{}) *MockAudiobookService_DeleteAudiobook_Call {
	return &MockAudiobookService_DeleteAudiobook_Call{Call: _e.mock.On("DeleteAudiobook", ctx, id, opts)}
}

func (_c *MockAudiobookService_DeleteAudiobook_Call) Run(run func(ctx context.Context, id string, opts *audiobooks.DeleteAudiobookOptions)) *MockAudiobookService_DeleteAudiobook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 *audiobooks.DeleteAudiobookOptions
		if args[2] != nil {
			arg2 = args[2].(*audiobooks.DeleteAudiobookOptions)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAudiobookService_DeleteAudiobook_Call) Return(stringToV map[string]any, err error) *MockAudiobookService_DeleteAudiobook_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockAudiobookService_DeleteAudiobook_Call) RunAndReturn(run func(ctx context.Context, id string, opts *audiobooks.DeleteAudiobookOptions) (map[string]any, error)) *MockAudiobookService_DeleteAudiobook_Call {
	_c.Call.Return(run)
	return _c
}

// EnrichAudiobooksWithNames provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) EnrichAudiobooksWithNames(books []database.Book) []audiobooks.AudiobookDetail {
	ret := _mock.Called(books)

	if len(ret) == 0 {
		panic("no return value specified for EnrichAudiobooksWithNames")
	}

	var r0 []audiobooks.AudiobookDetail
	if returnFunc, ok := ret.Get(0).(func([]database.Book) []audiobooks.AudiobookDetail); ok {
		r0 = returnFunc(books)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]audiobooks.AudiobookDetail)
		}
	}
	return r0
}

// MockAudiobookService_EnrichAudiobooksWithNames_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EnrichAudiobooksWithNames'
type MockAudiobookService_EnrichAudiobooksWithNames_Call struct {
	*mock.Call
}

// EnrichAudiobooksWithNames is a helper method to define mock.On call
//   - books []database.Book
func (_e *MockAudiobookService_Expecter) EnrichAudiobooksWithNames(books interface{}) *MockAudiobookService_EnrichAudiobooksWithNames_Call {
	return &MockAudiobookService_EnrichAudiobooksWithNames_Call{Call: _e.mock.On("EnrichAudiobooksWithNames", books)}
}

func (_c *MockAudiobookService_EnrichAudiobooksWithNames_Call) Run(run func(books []database.Book)) *MockAudiobookService_EnrichAudiobooksWithNames_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []database.Book
		if args[0] != nil {
			arg0 = args[0].([]database.Book)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAudiobookService_EnrichAudiobooksWithNames_Call) Return(audiobookDetails []audiobooks.AudiobookDetail) *MockAudiobookService_EnrichAudiobooksWithNames_Call {
	_c.Call.Return(audiobookDetails)
	return _c
}

func (_c *MockAudiobookService_EnrichAudiobooksWithNames_Call) RunAndReturn(run func(books []database.Book) []audiobooks.AudiobookDetail) *MockAudiobookService_EnrichAudiobooksWithNames_Call {
	_c.Call.Return(run)
	return _c
}

// GetAudiobook provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) GetAudiobook(ctx context.Context, id string) (*database.Book, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for GetAudiobook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*database.Book, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *database.Book); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_GetAudiobook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAudiobook'
type MockAudiobookService_GetAudiobook_Call struct {
	*mock.Call
}

// GetAudiobook is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAudiobookService_Expecter) GetAudiobook(ctx interface{}, id interface{}) *MockAudiobookService_GetAudiobook_Call {
	return &MockAudiobookService_GetAudiobook_Call{Call: _e.mock.On("GetAudiobook", ctx, id)}
}

func (_c *MockAudiobookService_GetAudiobook_Call) Run(run func(ctx context.Context, id string)) *MockAudiobookService_GetAudiobook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudiobookService_GetAudiobook_Call) Return(book *database.Book, err error) *MockAudiobookService_GetAudiobook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockAudiobookService_GetAudiobook_Call) RunAndReturn(run func(ctx context.Context, id string) (*database.Book, error)) *MockAudiobookService_GetAudiobook_Call {
	_c.Call.Return(run)
	return _c
}

// GetAudiobookTags provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) GetAudiobookTags(ctx context.Context, id string, compareID string, snapshotTS string) (map[string]any, error) {
	ret := _mock.Called(ctx, id, compareID, snapshotTS)

	if len(ret) == 0 {
		panic("no return value specified for GetAudiobookTags")
	}

	var r0 map[string]any
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (map[string]any, error)); ok {
		return returnFunc(ctx, id, compareID, snapshotTS)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) map[string]any); ok {
		r0 = returnFunc(ctx, id, compareID, snapshotTS)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]any)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, id, compareID, snapshotTS)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_GetAudiobookTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAudiobookTags'
type MockAudiobookService_GetAudiobookTags_Call struct {
	*mock.Call
}

// GetAudiobookTags is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - compareID string
//   - snapshotTS string
func (_e *MockAudiobookService_Expecter) GetAudiobookTags(ctx interface{}, id interface{}, compareID interface{}, snapshotTS interface{}) *MockAudiobookService_GetAudiobookTags_Call {
	return &MockAudiobookService_GetAudiobookTags_Call{Call: _e.mock.On("GetAudiobookTags", ctx, id, compareID, snapshotTS)}
}

func (_c *MockAudiobookService_GetAudiobookTags_Call) Run(run func(ctx context.Context, id string, compareID string, snapshotTS string)) *MockAudiobookService_GetAudiobookTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAudiobookService_GetAudiobookTags_Call) Return(stringToV map[string]any, err error) *MockAudiobookService_GetAudiobookTags_Call {
	_c.Call.Return(stringToV, err)
	return _c
}

func (_c *MockAudiobookService_GetAudiobookTags_Call) RunAndReturn(run func(ctx context.Context, id string, compareID string, snapshotTS string) (map[string]any, error)) *MockAudiobookService_GetAudiobookTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetBookUserTags provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) GetBookUserTags(bookID string) ([]string, error) {
	ret := _mock.Called(bookID)

	if len(ret) == 0 {
		panic("no return value specified for GetBookUserTags")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]string, error)); ok {
		return returnFunc(bookID)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []string); ok {
		r0 = returnFunc(bookID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(bookID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_GetBookUserTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetBookUserTags'
type MockAudiobookService_GetBookUserTags_Call struct {
	*mock.Call
}

// GetBookUserTags is a helper method to define mock.On call
//   - bookID string
func (_e *MockAudiobookService_Expecter) GetBookUserTags(bookID interface{}) *MockAudiobookService_GetBookUserTags_Call {
	return &MockAudiobookService_GetBookUserTags_Call{Call: _e.mock.On("GetBookUserTags", bookID)}
}

func (_c *MockAudiobookService_GetBookUserTags_Call) Run(run func(bookID string)) *MockAudiobookService_GetBookUserTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockAudiobookService_GetBookUserTags_Call) Return(strings []string, err error) *MockAudiobookService_GetBookUserTags_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockAudiobookService_GetBookUserTags_Call) RunAndReturn(run func(bookID string) ([]string, error)) *MockAudiobookService_GetBookUserTags_Call {
	_c.Call.Return(run)
	return _c
}

// GetSoftDeletedBooks provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) GetSoftDeletedBooks(ctx context.Context, limit int, offset int, olderThanDays *int) ([]database.Book, error) {
	ret := _mock.Called(ctx, limit, offset, olderThanDays)

	if len(ret) == 0 {
		panic("no return value specified for GetSoftDeletedBooks")
	}

	var r0 []database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *int) ([]database.Book, error)); ok {
		return returnFunc(ctx, limit, offset, olderThanDays)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, int, int, *int) []database.Book); ok {
		r0 = returnFunc(ctx, limit, offset, olderThanDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, int, int, *int) error); ok {
		r1 = returnFunc(ctx, limit, offset, olderThanDays)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_GetSoftDeletedBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSoftDeletedBooks'
type MockAudiobookService_GetSoftDeletedBooks_Call struct {
	*mock.Call
}

// GetSoftDeletedBooks is a helper method to define mock.On call
//   - ctx context.Context
//   - limit int
//   - offset int
//   - olderThanDays *int
func (_e *MockAudiobookService_Expecter) GetSoftDeletedBooks(ctx interface{}, limit interface{}, offset interface{}, olderThanDays interface{}) *MockAudiobookService_GetSoftDeletedBooks_Call {
	return &MockAudiobookService_GetSoftDeletedBooks_Call{Call: _e.mock.On("GetSoftDeletedBooks", ctx, limit, offset, olderThanDays)}
}

func (_c *MockAudiobookService_GetSoftDeletedBooks_Call) Run(run func(ctx context.Context, limit int, offset int, olderThanDays *int)) *MockAudiobookService_GetSoftDeletedBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 int
		if args[1] != nil {
			arg1 = args[1].(int)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 *int
		if args[3] != nil {
			arg3 = args[3].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockAudiobookService_GetSoftDeletedBooks_Call) Return(books []database.Book, err error) *MockAudiobookService_GetSoftDeletedBooks_Call {
	_c.Call.Return(books, err)
	return _c
}

func (_c *MockAudiobookService_GetSoftDeletedBooks_Call) RunAndReturn(run func(ctx context.Context, limit int, offset int, olderThanDays *int) ([]database.Book, error)) *MockAudiobookService_GetSoftDeletedBooks_Call {
	_c.Call.Return(run)
	return _c
}

// InvalidateBookCaches provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) InvalidateBookCaches() {
	_mock.Called()
	return
}

// MockAudiobookService_InvalidateBookCaches_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InvalidateBookCaches'
type MockAudiobookService_InvalidateBookCaches_Call struct {
	*mock.Call
}

// InvalidateBookCaches is a helper method to define mock.On call
func (_e *MockAudiobookService_Expecter) InvalidateBookCaches() *MockAudiobookService_InvalidateBookCaches_Call {
	return &MockAudiobookService_InvalidateBookCaches_Call{Call: _e.mock.On("InvalidateBookCaches")}
}

func (_c *MockAudiobookService_InvalidateBookCaches_Call) Run(run func()) *MockAudiobookService_InvalidateBookCaches_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAudiobookService_InvalidateBookCaches_Call) Return() *MockAudiobookService_InvalidateBookCaches_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockAudiobookService_InvalidateBookCaches_Call) RunAndReturn(run func()) *MockAudiobookService_InvalidateBookCaches_Call {
	_c.Run(run)
	return _c
}

// ListAllUserTags provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) ListAllUserTags() ([]database.TagWithCount, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ListAllUserTags")
	}

	var r0 []database.TagWithCount
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]database.TagWithCount, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []database.TagWithCount); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]database.TagWithCount)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_ListAllUserTags_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListAllUserTags'
type MockAudiobookService_ListAllUserTags_Call struct {
	*mock.Call
}

// ListAllUserTags is a helper method to define mock.On call
func (_e *MockAudiobookService_Expecter) ListAllUserTags() *MockAudiobookService_ListAllUserTags_Call {
	return &MockAudiobookService_ListAllUserTags_Call{Call: _e.mock.On("ListAllUserTags")}
}

func (_c *MockAudiobookService_ListAllUserTags_Call) Run(run func()) *MockAudiobookService_ListAllUserTags_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockAudiobookService_ListAllUserTags_Call) Return(tagWithCounts []database.TagWithCount, err error) *MockAudiobookService_ListAllUserTags_Call {
	_c.Call.Return(tagWithCounts, err)
	return _c
}

func (_c *MockAudiobookService_ListAllUserTags_Call) RunAndReturn(run func() ([]database.TagWithCount, error)) *MockAudiobookService_ListAllUserTags_Call {
	_c.Call.Return(run)
	return _c
}

// PurgeSoftDeletedBooks provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) PurgeSoftDeletedBooks(ctx context.Context, deleteFiles bool, olderThanDays *int) (*audiobooks.PurgeResult, error) {
	ret := _mock.Called(ctx, deleteFiles, olderThanDays)

	if len(ret) == 0 {
		panic("no return value specified for PurgeSoftDeletedBooks")
	}

	var r0 *audiobooks.PurgeResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *int) (*audiobooks.PurgeResult, error)); ok {
		return returnFunc(ctx, deleteFiles, olderThanDays)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, bool, *int) *audiobooks.PurgeResult); ok {
		r0 = returnFunc(ctx, deleteFiles, olderThanDays)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*audiobooks.PurgeResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, bool, *int) error); ok {
		r1 = returnFunc(ctx, deleteFiles, olderThanDays)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_PurgeSoftDeletedBooks_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PurgeSoftDeletedBooks'
type MockAudiobookService_PurgeSoftDeletedBooks_Call struct {
	*mock.Call
}

// PurgeSoftDeletedBooks is a helper method to define mock.On call
//   - ctx context.Context
//   - deleteFiles bool
//   - olderThanDays *int
func (_e *MockAudiobookService_Expecter) PurgeSoftDeletedBooks(ctx interface{}, deleteFiles interface{}, olderThanDays interface{}) *MockAudiobookService_PurgeSoftDeletedBooks_Call {
	return &MockAudiobookService_PurgeSoftDeletedBooks_Call{Call: _e.mock.On("PurgeSoftDeletedBooks", ctx, deleteFiles, olderThanDays)}
}

func (_c *MockAudiobookService_PurgeSoftDeletedBooks_Call) Run(run func(ctx context.Context, deleteFiles bool, olderThanDays *int)) *MockAudiobookService_PurgeSoftDeletedBooks_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 bool
		if args[1] != nil {
			arg1 = args[1].(bool)
		}
		var arg2 *int
		if args[2] != nil {
			arg2 = args[2].(*int)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAudiobookService_PurgeSoftDeletedBooks_Call) Return(purgeResult *audiobooks.PurgeResult, err error) *MockAudiobookService_PurgeSoftDeletedBooks_Call {
	_c.Call.Return(purgeResult, err)
	return _c
}

func (_c *MockAudiobookService_PurgeSoftDeletedBooks_Call) RunAndReturn(run func(ctx context.Context, deleteFiles bool, olderThanDays *int) (*audiobooks.PurgeResult, error)) *MockAudiobookService_PurgeSoftDeletedBooks_Call {
	_c.Call.Return(run)
	return _c
}

// RestoreAudiobook provides a mock function for the type MockAudiobookService
func (_mock *MockAudiobookService) RestoreAudiobook(ctx context.Context, id string) (*database.Book, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for RestoreAudiobook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (*database.Book, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) *database.Book); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookService_RestoreAudiobook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RestoreAudiobook'
type MockAudiobookService_RestoreAudiobook_Call struct {
	*mock.Call
}

// RestoreAudiobook is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
func (_e *MockAudiobookService_Expecter) RestoreAudiobook(ctx interface{}, id interface{}) *MockAudiobookService_RestoreAudiobook_Call {
	return &MockAudiobookService_RestoreAudiobook_Call{Call: _e.mock.On("RestoreAudiobook", ctx, id)}
}

func (_c *MockAudiobookService_RestoreAudiobook_Call) Run(run func(ctx context.Context, id string)) *MockAudiobookService_RestoreAudiobook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockAudiobookService_RestoreAudiobook_Call) Return(book *database.Book, err error) *MockAudiobookService_RestoreAudiobook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockAudiobookService_RestoreAudiobook_Call) RunAndReturn(run func(ctx context.Context, id string) (*database.Book, error)) *MockAudiobookService_RestoreAudiobook_Call {
	_c.Call.Return(run)
	return _c
}
