// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package audiobooksmocks

import (
	"context"

	"github.com/falkcorp/audiobook-organizer/internal/database"
	mock "github.com/stretchr/testify/mock"
)

// NewMockAudiobookUpdater creates a new instance of MockAudiobookUpdater. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudiobookUpdater(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudiobookUpdater {
	mock := &MockAudiobookUpdater{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAudiobookUpdater is an autogenerated mock type for the AudiobookUpdater type
type MockAudiobookUpdater struct {
	mock.Mock
}

type MockAudiobookUpdater_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudiobookUpdater) EXPECT() *MockAudiobookUpdater_Expecter {
	return &MockAudiobookUpdater_Expecter{mock: &_m.Mock}
}

// UpdateAudiobook provides a mock function for the type MockAudiobookUpdater
func (_mock *MockAudiobookUpdater) UpdateAudiobook(ctx context.Context, id string, payload map[string]any) (*database.Book, error) {
	ret := _mock.Called(ctx, id, payload)

	if len(ret) == 0 {
		panic("no return value specified for UpdateAudiobook")
	}

	var r0 *database.Book
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) (*database.Book, error)); ok {
		return returnFunc(ctx, id, payload)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, map[string]any) *database.Book); ok {
		r0 = returnFunc(ctx, id, payload)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*database.Book)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, map[string]any) error); ok {
		r1 = returnFunc(ctx, id, payload)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockAudiobookUpdater_UpdateAudiobook_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateAudiobook'
type MockAudiobookUpdater_UpdateAudiobook_Call struct {
	*mock.Call
}

// UpdateAudiobook is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - payload map[string]any
func (_e *MockAudiobookUpdater_Expecter) UpdateAudiobook(ctx interface{}, id interface{}, payload interface{}) *MockAudiobookUpdater_UpdateAudiobook_Call {
	return &MockAudiobookUpdater_UpdateAudiobook_Call{Call: _e.mock.On("UpdateAudiobook", ctx, id, payload)}
}

func (_c *MockAudiobookUpdater_UpdateAudiobook_Call) Run(run func(ctx context.Context, id string, payload map[string]any)) *MockAudiobookUpdater_UpdateAudiobook_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 map[string]any
		if args[2] != nil {
			arg2 = args[2].(map[string]any)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockAudiobookUpdater_UpdateAudiobook_Call) Return(book *database.Book, err error) *MockAudiobookUpdater_UpdateAudiobook_Call {
	_c.Call.Return(book, err)
	return _c
}

func (_c *MockAudiobookUpdater_UpdateAudiobook_Call) RunAndReturn(run func(ctx context.Context, id string, payload map[string]any) (*database.Book, error)) *MockAudiobookUpdater_UpdateAudiobook_Call {
	_c.Call.Return(run)
	return _c
}
