// file: scripts/query_books.go
// version: 1.0.1
// guid: 8a9b0c1d-2e3f-4a5b-6c7d-8e9f0a1b2c3d

package main









































































}	}		}			}				break				fmt.Println("(showing first 20 keys)")			if keyCount >= 20 {			keyCount++			fmt.Printf("%s\n", string(iter2.Key()))		for iter2.First(); iter2.Valid(); iter2.Next() {		keyCount := 0		defer iter2.Close()		iter2 := db.NewIter(nil)		fmt.Println("\nAll keys in database:")		// Try listing all keys				fmt.Println("No books found in database")	if count == 0 {	}		log.Fatal(err)	if err := iter.Error(); err != nil {	}		}			break		if count >= 5 {		count++				fmt.Println("---")		}			fmt.Printf("Value: %s\n", valStr)			}				valStr = valStr[:500] + "..."			if len(valStr) > 500 {			valStr := string(value)		if len(value) > 0 {		// Show first 500 chars of value if it contains file_path				fmt.Printf("Value length: %d bytes\n", len(value))		fmt.Printf("Key: %s\n", key)				value := iter.Value()		key := string(iter.Key())	for iter.First(); iter.Valid(); iter.Next() {	count := 0	defer iter.Close()	})		UpperBound: []byte("book;"), // Next character after ':'		LowerBound: []byte("book:"),	iter := db.NewIter(&pebble.IterOptions{	// Iterate through all keys with "book:" prefix	defer db.Close()	}		log.Fatal(err)	if err != nil {	db, err := pebble.Open("audiobooks.pebble", &pebble.Options{})func main() {)	"github.com/cockroachdb/pebble"	"os"	"log"	"fmt"import (package main// guid: 8a9b0c1d-2e3f-4a5b-6c7d-8e9f0a1b2c3d// version: 1.0.0
