import pathlib
import sys

pebble_path = pathlib.Path("internal/database/pebble_store.go")
sqlite_path = pathlib.Path("internal/database/sqlite_store_books.go")

old_pebble = """func (p *PebbleStore) GetAcoustIDStats() (*AcoustIDStats, error) {\n\tfiles, err := p.GetAllBookFiles()\n\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"GetAcoustIDStats: %w\", err)\n\t}\n\n\t// Build bookID -> source_import_path for library grouping.\n\tallBooks, _ := p.GetAllBooks(0, 0)\n\tbookLib := make(map[string]string, len(allBooks))\n\tfor _, b := range allBooks {\n\t\tif b.SourceImportPath != nil && *b.SourceImportPath != \"\" {\n\t\t\tbookLib[b.ID] = *b.SourceImportPath\n\t\t}\n\t}\n\n\tbyLib := make(map[string]*AcoustIDStatsByLibrary)\n\tstats := &AcoustIDStats{}\n\n\tfor _, f := range files {\n\t\tstats.TotalFiles++\n\t\thasFP := f.AcoustIDSeg0 != \"\" || f.AcoustIDSeg1 != \"\" || f.AcoustIDSeg2 != \"\" ||\n\t\t\tf.AcoustIDSeg3 != \"\" || f.AcoustIDSeg4 != \"\" || f.AcoustIDSeg5 != \"\" || f.AcoustIDSeg6 != \"\"\n\t\tif hasFP {\n\t\t\tstats.WithFingerprint++\n\t\t}\n\n\t\troot := bookLib[f.BookID]\n\t\tif root == \"\" {\n\t\t\troot = \"(unknown)\"\n\t\t}\n\t\tlib := byLib[root]\n\t\tif lib == nil {\n\t\t\tlib = &AcoustIDStatsByLibrary{LibraryRoot: root}\n\t\t\tbyLib[root] = lib\n\t\t}\n\t\tlib.TotalFiles++\n\t\tif hasFP {\n\t\t\tlib.WithFingerprint++\n\t\t}\n\t}\n\n\tfor _, v := range byLib {\n\t\tstats.ByLibrary = append(stats.ByLibrary, *v)\n\t}\n\tsort.Slice(stats.ByLibrary, func(i, j int) bool {\n\t\treturn stats.ByLibrary[i].LibraryRoot < stats.ByLibrary[j].LibraryRoot\n\t})\n\treturn stats, nil\n}\n"""

new_pebble = """func (p *PebbleStore) GetAcoustIDStats() (*AcoustIDStats, error) {\n\tfiles, err := p.GetAllBookFiles()\n\tif err != nil {\n\t\treturn nil, fmt.Errorf(\"GetAcoustIDStats: %w\", err)\n\t}\n\n\timportPaths, ipErr := p.GetAllImportPaths()\n\tif ipErr != nil {\n\t\tslog.Warn(\"acoustid stats import paths scan failed\", \"error\", ipErr)\n\t}\n\troots := buildLibraryRootCandidates(p.rootDir, importPaths)\n\n\tstats := &AcoustIDStats{}\n\tbyLibrary := make(map[string]*AcoustIDStatsByLibrary)\n\n\tfor _, f := range files {\n\t\tstats.TotalFiles++\n\t\thasSegments := bookFileHasAcoustIDSegments(&f)\n\t\tif hasSegments {\n\t\t\tstats.WithFingerprint++\n\t\t}\n\t\troot := libraryRootForPath(f.FilePath, roots)\n\t\tif root == \"\" {\n\t\t\troot = \"<unknown>\"\n\t\t}\n\t\tentry := byLibrary[root]\n\t\tif entry == nil {\n\t\t\tentry = &AcoustIDStatsByLibrary{LibraryRoot: root}\n\t\t\tbyLibrary[root] = entry\n\t\t}\n\t\tentry.TotalFiles++\n\t\tif hasSegments {\n\t\t\tentry.WithFingerprint++\n\t\t}\n\t}\n\n\tstats.ByLibrary = flattenAcoustIDStats(byLibrary)\n\treturn stats, nil\n}\n"""

old_sqlite = """func (s *SQLiteStore) GetAcoustIDStats() (*AcoustIDStats, error) {\n\treturn &AcoustIDStats{}, nil\n}\n"""

new_sqlite = """func (s *SQLiteStore) GetAcoustIDStats() (*AcoustIDStats, error) {\n\timportPaths, ipErr := s.GetAllImportPaths()\n\tif ipErr != nil {\n\t\tslog.Warn(\"acoustid stats import paths scan failed\", \"error\", ipErr)\n\t}\n\trows, err := s.db.Query(`\nSELECT file_path,\n       acoustid_seg0, acoustid_seg1, acoustid_seg2,\n       acoustid_seg3, acoustid_seg4, acoustid_seg5, acoustid_seg6\nFROM book_files\n`)\n\tif err != nil {\n\t\treturn nil, err\n\t}\n\tdefer rows.Close()\n\n\troots := buildLibraryRootCandidates(s.rootDir, importPaths)\n\tstats := &AcoustIDStats{}\n\tbyLibrary := make(map[string]*AcoustIDStatsByLibrary)\n\n\tfor rows.Next() {\n\t\tvar filePath string\n\t\tvar seg0, seg1, seg2, seg3, seg4, seg5, seg6 sql.NullString\n\t\tif err := rows.Scan(&filePath, &seg0, &seg1, &seg2, &seg3, &seg4, &seg5, &seg6); err != nil {\n\t\t\treturn nil, fmt.Errorf(\"GetAcoustIDStats scan: %w\", err)\n\t\t}\n\t\tstats.TotalFiles++\n\t\thasSegments := hasAcoustIDNullSegments(seg0, seg1, seg2, seg3, seg4, seg5, seg6)\n\t\tif hasSegments {\n\t\t\tstats.WithFingerprint++\n\t\t}\n\t\troot := libraryRootForPath(filePath, roots)\n\t\tif root == \"\" {\n\t\t\troot = \"<unknown>\"\n\t\t}\n\t\tentry := byLibrary[root]\n\t\tif entry == nil {\n\t\t\tentry = &AcoustIDStatsByLibrary{LibraryRoot: root}\n\t\t\tbyLibrary[root] = entry\n\t\t}\n\t\tentry.TotalFiles++\n\t\tif hasSegments {\n\t\t\tentry.WithFingerprint++\n\t\t}\n\t}\n\tif err := rows.Err(); err != nil {\n\t\treturn nil, fmt.Errorf(\"GetAcoustIDStats rows: %w\", err)\n\t}\n\tstats.ByLibrary = flattenAcoustIDStats(byLibrary)\n\treturn stats, nil\n}\n"""

def replace(path, old, new):\n    text = path.read_text()\n    if old not in text:\n        print(f"pattern not found in {path}", file=sys.stderr)\n        sys.exit(1)\n    path.write_text(text.replace(old, new, 1))\n
replace(pebble_path, old_pebble, new_pebble)\nreplace(sqlite_path, old_sqlite, new_sqlite)\npathlib.Path(__file__).unlink()\n